/* Banco de perguntas — 250 questões em 25 categorias
   Formato: q(id, categoria, pergunta, [certa], [errada1], [errada2], [errada3])
   O jogo embaralha as opções antes de exibir. */
const QUESTIONS = (function () {
  function q(id, cat, text, c, w1, w2, w3) {
    return {
      id, category: cat, question: text,
      options: [
        { emoji: c[0],  label: c[1],  correct: true  },
        { emoji: w1[0], label: w1[1], correct: false },
        { emoji: w2[0], label: w2[1], correct: false },
        { emoji: w3[0], label: w3[1], correct: false },
      ]
    };
  }

  return [

    // ── 1. ANIMAIS DOMÉSTICOS ──────────────────────────────────────────────
    q(1,'animais_domesticos','Qual animal faz "AU AU"?',
      ['🐶','Cachorro'],['🐱','Gato'],['🐄','Vaca'],['🐸','Sapo']),
    q(2,'animais_domesticos','Qual animal faz "MIAU"?',
      ['🐱','Gato'],['🐶','Cachorro'],['🐟','Peixe'],['🐰','Coelho']),
    q(3,'animais_domesticos','Qual animal ronrona quando está feliz?',
      ['🐱','Gato'],['🐶','Cachorro'],['🐟','Peixe'],['🦜','Papagaio']),
    q(4,'animais_domesticos','Qual animal tem orelhas longas e adora cenoura?',
      ['🐰','Coelho'],['🐱','Gato'],['🐶','Cachorro'],['🐢','Tartaruga']),
    q(5,'animais_domesticos','Qual animal guarda a casa e late?',
      ['🐶','Cachorro'],['🐱','Gato'],['🐰','Coelho'],['🐢','Tartaruga']),
    q(6,'animais_domesticos','Qual animal tem penas coloridas e fica em gaiola?',
      ['🦜','Papagaio'],['🐶','Cachorro'],['🐟','Peixe'],['🐱','Gato']),
    q(7,'animais_domesticos','Qual animal tem carapaça e anda bem devagar?',
      ['🐢','Tartaruga'],['🐰','Coelho'],['🐶','Cachorro'],['🦜','Papagaio']),
    q(8,'animais_domesticos','Qual animal é chamado de "melhor amigo do homem"?',
      ['🐶','Cachorro'],['🐱','Gato'],['🐰','Coelho'],['🐟','Peixe']),
    q(9,'animais_domesticos','Qual animal tem bigode e caça ratinhos?',
      ['🐱','Gato'],['🐶','Cachorro'],['🦜','Papagaio'],['🐢','Tartaruga']),
    q(10,'animais_domesticos','Qual animal nada em aquário dentro de casa?',
      ['🐟','Peixe'],['🐱','Gato'],['🐶','Cachorro'],['🐰','Coelho']),

    // ── 2. ANIMAIS SELVAGENS ───────────────────────────────────────────────
    q(11,'animais_selvagens','Qual é o rei da selva?',
      ['🦁','Leão'],['🐘','Elefante'],['🐯','Tigre'],['🦒','Girafa']),
    q(12,'animais_selvagens','Qual animal tem tromba longa?',
      ['🐘','Elefante'],['🦁','Leão'],['🦒','Girafa'],['🐊','Jacaré']),
    q(13,'animais_selvagens','Qual animal tem pescoço muito longo?',
      ['🦒','Girafa'],['🐘','Elefante'],['🦁','Leão'],['🐻','Urso']),
    q(14,'animais_selvagens','Qual animal tem listras pretas e laranja?',
      ['🐯','Tigre'],['🦁','Leão'],['🐆','Leopardo'],['🐻','Urso']),
    q(15,'animais_selvagens','Qual animal tem listras e parece um cavalo?',
      ['🦓','Zebra'],['🐴','Cavalo'],['🐯','Tigre'],['🦌','Veado']),
    q(16,'animais_selvagens','Qual animal tem bolso na barriga?',
      ['🦘','Canguru'],['🐨','Coala'],['🐼','Panda'],['🦙','Lhama']),
    q(17,'animais_selvagens','Qual animal come bambu e é preto e branco?',
      ['🐼','Panda'],['🦁','Leão'],['🐘','Elefante'],['🦘','Canguru']),
    q(18,'animais_selvagens','Qual animal tem chifre no nariz?',
      ['🦏','Rinoceronte'],['🐘','Elefante'],['🦒','Girafa'],['🐊','Jacaré']),
    q(19,'animais_selvagens','Qual animal pula de árvore em árvore?',
      ['🐒','Macaco'],['🦁','Leão'],['🐘','Elefante'],['🐊','Jacaré']),
    q(20,'animais_selvagens','Qual animal tem penas rosas e fica numa perna só?',
      ['🦩','Flamingo'],['🦅','Águia'],['🦜','Papagaio'],['🦆','Pato']),

    // ── 3. ANIMAIS MARINHOS ────────────────────────────────────────────────
    q(21,'animais_marinhos','Qual animal marinho tem 8 tentáculos?',
      ['🐙','Polvo'],['🦈','Tubarão'],['🐬','Golfinho'],['🦞','Lagosta']),
    q(22,'animais_marinhos','Qual animal tem grandes nadadeiras e é muito perigoso?',
      ['🦈','Tubarão'],['🐬','Golfinho'],['🐋','Baleia'],['🦭','Foca']),
    q(23,'animais_marinhos','Qual animal marinho é simpático e salta fora d\'água?',
      ['🐬','Golfinho'],['🦈','Tubarão'],['🐙','Polvo'],['🦑','Lula']),
    q(24,'animais_marinhos','Qual é o maior animal que vive no mar?',
      ['🐋','Baleia'],['🦈','Tubarão'],['🐬','Golfinho'],['🦭','Foca']),
    q(25,'animais_marinhos','Qual animal marinho tem 5 braços em forma de estrela?',
      ['⭐','Estrela-do-mar'],['🐙','Polvo'],['🦑','Lula'],['🦀','Caranguejo']),
    q(26,'animais_marinhos','Qual animal marinho tem pinças e anda de lado?',
      ['🦀','Caranguejo'],['🦞','Lagosta'],['🦂','Escorpião'],['🐙','Polvo']),
    q(27,'animais_marinhos','Qual animal marinho é transparente e queima a pele?',
      ['🪼','Água-viva'],['🐙','Polvo'],['🦑','Lula'],['🐚','Caracol']),
    q(28,'animais_marinhos','Qual animal marinho tem "cavalo" no nome?',
      ['🐴','Cavalo-marinho'],['🦈','Tubarão'],['🐬','Golfinho'],['🐙','Polvo']),
    q(29,'animais_marinhos','Qual animal marinho tem antenas e é muito saboroso?',
      ['🦞','Lagosta'],['🦀','Caranguejo'],['🐙','Polvo'],['🦑','Lula']),
    q(30,'animais_marinhos','Qual animal nada mas parece um pássaro?',
      ['🐧','Pinguim'],['🦅','Águia'],['🦆','Pato'],['🦢','Cisne']),

    // ── 4. ANIMAIS DA FAZENDA ─────────────────────────────────────────────
    q(31,'animais_fazenda','Qual animal da fazenda nos dá leite?',
      ['🐄','Vaca'],['🐷','Porco'],['🐔','Galinha'],['🐴','Cavalo']),
    q(32,'animais_fazenda','Qual animal acorda todos com "COCORICÓ"?',
      ['🐓','Galo'],['🐔','Galinha'],['🦆','Pato'],['🐄','Vaca']),
    q(33,'animais_fazenda','Qual animal da fazenda tem lã quentinha?',
      ['🐑','Ovelha'],['🐐','Cabra'],['🐄','Vaca'],['🐷','Porco']),
    q(34,'animais_fazenda','Qual animal da fazenda põe ovos?',
      ['🐔','Galinha'],['🐄','Vaca'],['🐑','Ovelha'],['🐷','Porco']),
    q(35,'animais_fazenda','Qual animal é usado para cavalgar?',
      ['🐴','Cavalo'],['🐄','Vaca'],['🐷','Porco'],['🐑','Ovelha']),
    q(36,'animais_fazenda','Qual animal da fazenda faz "QUACK QUACK"?',
      ['🦆','Pato'],['🐔','Galinha'],['🐓','Galo'],['🦃','Peru']),
    q(37,'animais_fazenda','Qual animal da fazenda tem focinho e é rosado?',
      ['🐷','Porco'],['🐄','Vaca'],['🐑','Ovelha'],['🐴','Cavalo']),
    q(38,'animais_fazenda','Qual pequeno animal da fazenda produz mel?',
      ['🐝','Abelha'],['🦋','Borboleta'],['🐛','Lagarta'],['🐞','Joaninha']),
    q(39,'animais_fazenda','Qual animal tem chifres e empurra as pessoas?',
      ['🐂','Touro'],['🐄','Vaca'],['🐑','Ovelha'],['🐐','Cabra']),
    q(40,'animais_fazenda','Qual animal da fazenda faz "MÉ MÉ"?',
      ['🐑','Ovelha'],['🐄','Vaca'],['🐴','Cavalo'],['🐷','Porco']),

    // ── 5. INSETOS E PEQUENOS ANIMAIS ─────────────────────────────────────
    q(41,'insetos','Qual inseto faz mel delicioso?',
      ['🐝','Abelha'],['🦋','Borboleta'],['🐞','Joaninha'],['🐜','Formiga']),
    q(42,'insetos','Qual inseto tem asas coloridas e bonitas?',
      ['🦋','Borboleta'],['🐝','Abelha'],['🐞','Joaninha'],['🦗','Grilo']),
    q(43,'insetos','Qual inseto é vermelho com pontinhos pretos?',
      ['🐞','Joaninha'],['🦋','Borboleta'],['🐜','Formiga'],['🐝','Abelha']),
    q(44,'insetos','Qual pequeno animal constrói teias para pegar comida?',
      ['🕷️','Aranha'],['🐜','Formiga'],['🦗','Grilo'],['🐝','Abelha']),
    q(45,'insetos','Qual inseto vira borboleta depois de um tempo?',
      ['🐛','Lagarta'],['🐜','Formiga'],['🦗','Grilo'],['🐝','Abelha']),
    q(46,'insetos','Qual inseto canta de noite?',
      ['🦗','Grilo'],['🐝','Abelha'],['🦋','Borboleta'],['🐞','Joaninha']),
    q(47,'insetos','Qual inseto mora em colmeia e tem rainha?',
      ['🐝','Abelha'],['🐜','Formiga'],['🦗','Grilo'],['🦋','Borboleta']),
    q(48,'insetos','Qual pequeno animal tem 8 patas?',
      ['🕷️','Aranha'],['🐜','Formiga'],['🦗','Grilo'],['🐝','Abelha']),
    q(49,'insetos','Qual inseto pula muito alto e tem asas?',
      ['🦗','Gafanhoto'],['🐝','Abelha'],['🐛','Lagarta'],['🐞','Joaninha']),
    q(50,'insetos','Qual pequeno animal tem concha e deixa um rastro brilhante?',
      ['🐌','Caracol'],['🐜','Formiga'],['🕷️','Aranha'],['🐛','Lagarta']),

    // ── 6. PÁSSAROS ────────────────────────────────────────────────────────
    q(51,'passaros','Qual pássaro não consegue voar?',
      ['🐧','Pinguim'],['🦅','Águia'],['🦜','Papagaio'],['🐦','Pardal']),
    q(52,'passaros','Qual pássaro tem cauda colorida e longa como um leque?',
      ['🦚','Pavão'],['🦜','Papagaio'],['🦩','Flamingo'],['🦅','Águia']),
    q(53,'passaros','Qual pássaro bate o bico na árvore para encontrar comida?',
      ['🐦','Pica-pau'],['🦜','Papagaio'],['🦅','Águia'],['🐧','Pinguim']),
    q(54,'passaros','Qual pássaro fica de pé em uma perna só?',
      ['🦩','Flamingo'],['🦅','Águia'],['🐧','Pinguim'],['🦢','Cisne']),
    q(55,'passaros','Qual pássaro é símbolo da paz?',
      ['🕊️','Pomba'],['🦅','Águia'],['🦜','Papagaio'],['🦚','Pavão']),
    q(56,'passaros','Qual pássaro faz "HUU HUU" durante a noite?',
      ['🦉','Coruja'],['🦜','Papagaio'],['🐧','Pinguim'],['🦢','Cisne']),
    q(57,'passaros','Qual pássaro tem pescoço longo e é elegante?',
      ['🦢','Cisne'],['🐧','Pinguim'],['🦩','Flamingo'],['🦅','Águia']),
    q(58,'passaros','Qual pássaro repete o que a gente fala?',
      ['🦜','Papagaio'],['🦉','Coruja'],['🦢','Cisne'],['🐧','Pinguim']),
    q(59,'passaros','Qual pássaro voa muito alto e tem visão aguçada?',
      ['🦅','Águia'],['🦜','Papagaio'],['🦉','Coruja'],['🐧','Pinguim']),
    q(60,'passaros','Qual pássaro é pequeninho e tem o peitinho vermelho?',
      ['🐦','Pintassilgo'],['🦅','Águia'],['🦜','Papagaio'],['🦩','Flamingo']),

    // ── 7. DINOSSAUROS ────────────────────────────────────────────────────
    q(61,'dinossauros','Qual dinossauro tinha pescoço muito, muito longo?',
      ['🦕','Braquiossauro'],['🦖','T-Rex'],['🐊','Crocodilo'],['🦎','Lagarto']),
    q(62,'dinossauros','Qual dinossauro era carnívoro e tinha bracinhos pequenos?',
      ['🦖','T-Rex'],['🦕','Braquiossauro'],['🦎','Lagarto'],['🐊','Crocodilo']),
    q(63,'dinossauros','Qual dinossauro tinha três chifres na cabeça?',
      ['🦏','Triceratops'],['🦖','T-Rex'],['🦕','Braquiossauro'],['🐉','Dragão']),
    q(64,'dinossauros','Qual dinossauro tinha placas ósseas nas costas?',
      ['🦎','Estegossauro'],['🦖','T-Rex'],['🦕','Braquiossauro'],['🐊','Crocodilo']),
    q(65,'dinossauros','Qual dinossauro voava no céu pré-histórico?',
      ['🦅','Pterossauro'],['🦕','Braquiossauro'],['🦖','T-Rex'],['🦋','Borboleta']),
    q(66,'dinossauros','Como se chama o período dos dinossauros?',
      ['⏳','Jurássico'],['❄️','Gelo'],['🌊','Mar'],['🔥','Fogo']),
    q(67,'dinossauros','Qual dinossauro vivia na água e tinha pescoço longo?',
      ['🐍','Plesiosaurus'],['🦕','Braquiossauro'],['🦖','T-Rex'],['🐊','Crocodilo']),
    q(68,'dinossauros','Qual dinossauro era pequeno, rápido e inteligente?',
      ['🦎','Velociraptor'],['🦖','T-Rex'],['🦕','Braquiossauro'],['🐊','Crocodilo']),
    q(69,'dinossauros','Qual dinossauro tinha cauda com marreta?',
      ['🪨','Anquilossauro'],['🦖','T-Rex'],['🦕','Braquiossauro'],['🦎','Estegossauro']),
    q(70,'dinossauros','O que os cientistas estudam para saber sobre dinossauros?',
      ['🦴','Fósseis'],['📚','Livros'],['🔭','Telescópio'],['🧪','Química']),

    // ── 8. FRUTAS ─────────────────────────────────────────────────────────
    q(71,'frutas','Qual fruta é vermelha e tem sementes por fora?',
      ['🍓','Morango'],['🍎','Maçã'],['🍒','Cereja'],['🍉','Melancia']),
    q(72,'frutas','Qual fruta tem casca amarela e é curva?',
      ['🍌','Banana'],['🍋','Limão'],['🍑','Pêssego'],['🍊','Tangerina']),
    q(73,'frutas','Qual fruta é redonda e vermelha com caroço dentro?',
      ['🍎','Maçã'],['🍅','Tomate'],['🍒','Cereja'],['🍓','Morango']),
    q(74,'frutas','Qual fruta é roxa e cresce em cacho?',
      ['🍇','Uva'],['🫐','Mirtilo'],['🍆','Berinjela'],['🟣','Ameixa']),
    q(75,'frutas','Qual fruta é laranja por dentro e por fora?',
      ['🍊','Laranja'],['🍋','Limão'],['🍑','Pêssego'],['🥭','Manga']),
    q(76,'frutas','Qual fruta é grande, verde por fora e vermelha por dentro?',
      ['🍉','Melancia'],['🍈','Melão'],['🥝','Kiwi'],['🍐','Pera']),
    q(77,'frutas','Qual fruta tem espinhos por fora e é amarela por dentro?',
      ['🍍','Abacaxi'],['🍋','Limão'],['🥭','Manga'],['🍈','Melão']),
    q(78,'frutas','Qual fruta é pequena, amarela e muito azeda?',
      ['🍋','Limão'],['🍌','Banana'],['🍊','Laranja'],['🍎','Maçã']),
    q(79,'frutas','Qual fruta é tropical, amarela e super doce?',
      ['🥭','Manga'],['🍌','Banana'],['🍋','Limão'],['🍊','Laranja']),
    q(80,'frutas','Qual fruta é pequena, vermelha e cresce em cerejeira?',
      ['🍒','Cereja'],['🍓','Morango'],['🍎','Maçã'],['🫐','Mirtilo']),

    // ── 9. VEGETAIS ───────────────────────────────────────────────────────
    q(81,'vegetais','Qual vegetal é laranja e cresce debaixo da terra?',
      ['🥕','Cenoura'],['🍊','Laranja'],['🥔','Batata'],['🌽','Milho']),
    q(82,'vegetais','Qual vegetal é verde e parece uma arvorezinha?',
      ['🥦','Brócolis'],['🌿','Hortelã'],['🥬','Alface'],['🌱','Muda']),
    q(83,'vegetais','Qual vegetal é redondo e vermelho na salada?',
      ['🍅','Tomate'],['🍎','Maçã'],['🫑','Pimentão'],['🧅','Cebola']),
    q(84,'vegetais','Qual vegetal é roxo e tem o mesmo nome de uma cor?',
      ['🍆','Berinjela'],['🟣','Ameixa'],['🫐','Mirtilo'],['🧅','Cebola']),
    q(85,'vegetais','Qual vegetal é branco e faz chorar quando cortamos?',
      ['🧅','Cebola'],['🧄','Alho'],['🥔','Batata'],['🌽','Milho']),
    q(86,'vegetais','Qual vegetal é verde e comprido como um barco?',
      ['🥒','Pepino'],['🥬','Alface'],['🌿','Erva'],['🥦','Brócolis']),
    q(87,'vegetais','Qual vegetal são bolinhas verdes dentro de uma vagem?',
      ['🫛','Ervilha'],['🍏','Uva verde'],['🥬','Alface'],['🥦','Brócolis']),
    q(88,'vegetais','Qual vegetal tem folhas verdes e vai na salada?',
      ['🥬','Alface'],['🌿','Salsinha'],['🥦','Brócolis'],['🌱','Muda']),
    q(89,'vegetais','Qual vegetal é amarelo e tem "cabelo" de seda?',
      ['🌽','Milho'],['🍌','Banana'],['🍋','Limão'],['🧅','Cebola']),
    q(90,'vegetais','Qual vegetal tem a forma de um coração e é vermelho?',
      ['🫑','Pimentão vermelho'],['🍅','Tomate'],['🍓','Morango'],['🍎','Maçã']),

    // ── 10. NATUREZA E PLANTAS ────────────────────────────────────────────
    q(91,'natureza','Qual parte da planta fica debaixo da terra?',
      ['🌱','Raiz'],['🍃','Folha'],['🌸','Flor'],['🌲','Tronco']),
    q(92,'natureza','O que acontece com as flores quando chove?',
      ['💧','Bebem água'],['🔥','Secam'],['❄️','Congelam'],['💨','Voam']),
    q(93,'natureza','Qual parte colorida das flores atrai as borboletas?',
      ['🌸','Pétalas'],['🍃','Folhas'],['🌱','Raízes'],['🪵','Caule']),
    q(94,'natureza','Qual planta tem espinhos e não precisa de muita água?',
      ['🌵','Cacto'],['🌲','Pinheiro'],['🌴','Palmeira'],['🌿','Samambaia']),
    q(95,'natureza','O que a abelha tira das flores para fazer mel?',
      ['🌸','Néctar'],['💧','Água'],['🍯','Mel'],['🟡','Pólen']),
    q(96,'natureza','Como se chama a semente que cai e pode virar uma árvore?',
      ['🌰','Semente'],['🍃','Folha'],['🌸','Flor'],['🍎','Fruto']),
    q(97,'natureza','Qual é a cor da maioria das folhas das árvores?',
      ['🟢','Verde'],['🟡','Amarelo'],['🟠','Laranja'],['🔴','Vermelho']),
    q(98,'natureza','O que as plantas precisam para crescer, além de água?',
      ['☀️','Luz do sol'],['🌙','Lua'],['⭐','Estrelas'],['🌧️','Tempestade']),
    q(99,'natureza','Como se chama a parte marrom e alta das árvores?',
      ['🪵','Tronco'],['🌱','Raiz'],['🍃','Galho'],['🌸','Copa']),
    q(100,'natureza','O que as árvores soltam que faz bem para nós respirarmos?',
      ['💨','Oxigênio'],['💧','Água'],['🔥','Calor'],['❄️','Frio']),

    // ── 11. ESTAÇÕES DO ANO ───────────────────────────────────────────────
    q(101,'estacoes','Em qual estação as folhas caem das árvores?',
      ['🍂','Outono'],['🌸','Primavera'],['☀️','Verão'],['❄️','Inverno']),
    q(102,'estacoes','Em qual estação faz mais calor e vamos à praia?',
      ['☀️','Verão'],['🍂','Outono'],['🌸','Primavera'],['❄️','Inverno']),
    q(103,'estacoes','Em qual estação as flores brotam e tudo fica colorido?',
      ['🌸','Primavera'],['☀️','Verão'],['🍂','Outono'],['❄️','Inverno']),
    q(104,'estacoes','Em qual estação faz mais frio e pode nevar?',
      ['❄️','Inverno'],['🍂','Outono'],['🌸','Primavera'],['☀️','Verão']),
    q(105,'estacoes','Qual estação vem logo depois do verão?',
      ['🍂','Outono'],['❄️','Inverno'],['🌸','Primavera'],['☀️','Verão']),
    q(106,'estacoes','Em qual estação as árvores ficam sem folhas?',
      ['❄️','Inverno'],['🍂','Outono'],['🌸','Primavera'],['☀️','Verão']),
    q(107,'estacoes','Quantas estações do ano existem?',
      ['4️⃣','Quatro'],['3️⃣','Três'],['2️⃣','Duas'],['6️⃣','Seis']),
    q(108,'estacoes','Em qual estação os dias são mais longos e as noites mais curtas?',
      ['☀️','Verão'],['❄️','Inverno'],['🍂','Outono'],['🌸','Primavera']),
    q(109,'estacoes','Qual estação vem depois do inverno?',
      ['🌸','Primavera'],['☀️','Verão'],['🍂','Outono'],['❄️','Inverno']),
    q(110,'estacoes','Em qual estação o carnaval acontece no Brasil?',
      ['☀️','Verão'],['🍂','Outono'],['🌸','Primavera'],['❄️','Inverno']),

    // ── 12. CLIMA E TEMPO ─────────────────────────────────────────────────
    q(111,'clima','O que cai do céu quando está chovendo?',
      ['🌧️','Chuva'],['❄️','Neve'],['🌪️','Vento'],['⚡','Raio']),
    q(112,'clima','O que forma um arco colorido no céu depois da chuva?',
      ['🌈','Arco-íris'],['☀️','Sol'],['🌙','Lua'],['⭐','Estrela']),
    q(113,'clima','O que cobre o chão quando faz muito frio lá fora?',
      ['❄️','Neve'],['🌧️','Chuva'],['🌫️','Neblina'],['🌪️','Vento']),
    q(114,'clima','Como se chama o ar que sopra e balança as árvores?',
      ['💨','Vento'],['🌧️','Chuva'],['❄️','Neve'],['⚡','Raio']),
    q(115,'clima','O que aparece no céu de noite, redondo e brilhante?',
      ['🌙','Lua'],['⭐','Estrela'],['☀️','Sol'],['🌈','Arco-íris']),
    q(116,'clima','O que acontece quando há muitos raios e trovões?',
      ['⛈️','Tempestade'],['❄️','Neve'],['🌈','Arco-íris'],['☀️','Sol forte']),
    q(117,'clima','Como se chama a nuvem que desce e fica grudada no chão?',
      ['🌫️','Neblina'],['🌧️','Chuva'],['❄️','Neve'],['💨','Vento']),
    q(118,'clima','O que acontece com a água quando faz muito frio?',
      ['🧊','Congela'],['💧','Evapora'],['🌊','Chove'],['💨','Vira vento']),
    q(119,'clima','O que é a bolinhas de gelo que caem do céu?',
      ['🧊','Granizo'],['❄️','Neve'],['🌧️','Chuva'],['💧','Orvalho']),
    q(120,'clima','Quando está muito quente, o que fazemos para nos refrescar?',
      ['🏊','Nadar'],['🧥','Colocar casaco'],['🔥','Acender fogo'],['❄️','Ficar na neve']),

    // ── 13. CORES ─────────────────────────────────────────────────────────
    q(121,'cores','Qual é a cor do céu num dia ensolarado?',
      ['🔵','Azul'],['🟢','Verde'],['🟡','Amarelo'],['🔴','Vermelho']),
    q(122,'cores','Qual é a cor da grama e das folhas?',
      ['🟢','Verde'],['🟡','Amarelo'],['🔵','Azul'],['🟤','Marrom']),
    q(123,'cores','Qual é a cor do sol?',
      ['🟡','Amarelo'],['🟠','Laranja'],['🔴','Vermelho'],['⚪','Branco']),
    q(124,'cores','Qual é a cor do sangue?',
      ['🔴','Vermelho'],['🟠','Laranja'],['🟣','Roxo'],['🟤','Marrom']),
    q(125,'cores','Qual cor se forma quando misturamos azul e amarelo?',
      ['🟢','Verde'],['🟠','Laranja'],['🟣','Roxo'],['🟤','Marrom']),
    q(126,'cores','Qual é a cor da noite e do carvão?',
      ['⚫','Preto'],['🔵','Azul marinho'],['🟤','Marrom'],['🟣','Roxo']),
    q(127,'cores','Qual é a cor da neve e das nuvens?',
      ['⚪','Branco'],['🔵','Azul'],['🟡','Amarelo'],['⚫','Cinza']),
    q(128,'cores','Qual é a cor da uva roxa e da lavanda?',
      ['🟣','Roxo'],['🔵','Azul'],['🔴','Vermelho'],['🟠','Laranja']),
    q(129,'cores','Qual cor se forma quando misturamos vermelho e amarelo?',
      ['🟠','Laranja'],['🟣','Roxo'],['🟢','Verde'],['🟤','Marrom']),
    q(130,'cores','Qual é a cor do chocolate e da terra?',
      ['🟤','Marrom'],['⚫','Preto'],['🟠','Laranja'],['🔴','Vermelho']),

    // ── 14. FORMAS GEOMÉTRICAS ────────────────────────────────────────────
    q(131,'formas','Qual forma tem apenas 3 lados?',
      ['🔺','Triângulo'],['⬛','Quadrado'],['⬜','Retângulo'],['🔶','Losango']),
    q(132,'formas','Qual forma tem 4 lados todos iguais?',
      ['⬛','Quadrado'],['⬜','Retângulo'],['🔺','Triângulo'],['🔶','Losango']),
    q(133,'formas','Qual forma não tem lados e é redonda?',
      ['⚪','Círculo'],['⬛','Quadrado'],['🔺','Triângulo'],['⬜','Retângulo']),
    q(134,'formas','Qual forma tem 4 lados mas dois deles são maiores?',
      ['⬜','Retângulo'],['⬛','Quadrado'],['🔺','Triângulo'],['🔶','Losango']),
    q(135,'formas','Como se chama a forma com 6 lados iguais igual à célula da abelha?',
      ['🔷','Hexágono'],['🔺','Pentágono'],['⬛','Quadrado'],['⭐','Estrela']),
    q(136,'formas','Qual forma tem 5 pontas e usamos para desenhar no céu?',
      ['⭐','Estrela'],['🔺','Triângulo'],['🔷','Hexágono'],['🔶','Losango']),
    q(137,'formas','Como se chama uma bola em 3D?',
      ['🔵','Esfera'],['⚪','Círculo'],['⬛','Cubo'],['🔺','Cone']),
    q(138,'formas','Como se chama uma caixa com 6 lados iguais?',
      ['📦','Cubo'],['🔵','Esfera'],['🔺','Pirâmide'],['🪨','Pedra']),
    q(139,'formas','Como se chama a forma do ovo?',
      ['🥚','Oval'],['⚪','Círculo'],['⬛','Quadrado'],['🔺','Triângulo']),
    q(140,'formas','Como se chama o formato de uma pizza inteira?',
      ['⚪','Círculo'],['⬛','Quadrado'],['⬜','Retângulo'],['🔺','Triângulo']),

    // ── 15. NÚMEROS E QUANTIDADES ─────────────────────────────────────────
    q(141,'numeros','Quantas patas tem um cachorro?',
      ['4️⃣','4 patas'],['2️⃣','2 patas'],['6️⃣','6 patas'],['8️⃣','8 patas']),
    q(142,'numeros','Quantos dedos tem uma mão?',
      ['5️⃣','5 dedos'],['4️⃣','4 dedos'],['6️⃣','6 dedos'],['3️⃣','3 dedos']),
    q(143,'numeros','Quantos olhos tem uma pessoa?',
      ['2️⃣','2 olhos'],['1️⃣','1 olho'],['4️⃣','4 olhos'],['3️⃣','3 olhos']),
    q(144,'numeros','Quantas rodas tem uma bicicleta?',
      ['2️⃣','2 rodas'],['4️⃣','4 rodas'],['3️⃣','3 rodas'],['1️⃣','1 roda']),
    q(145,'numeros','Quantas patas tem um inseto?',
      ['6️⃣','6 patas'],['4️⃣','4 patas'],['8️⃣','8 patas'],['2️⃣','2 patas']),
    q(146,'numeros','Quantas patas tem uma aranha?',
      ['8️⃣','8 patas'],['6️⃣','6 patas'],['4️⃣','4 patas'],['2️⃣','2 patas']),
    q(147,'numeros','Quantos lados tem um triângulo?',
      ['3️⃣','3 lados'],['4️⃣','4 lados'],['5️⃣','5 lados'],['2️⃣','2 lados']),
    q(148,'numeros','Quanto é 2 + 2?',
      ['4️⃣','4'],['3️⃣','3'],['5️⃣','5'],['2️⃣','2']),
    q(149,'numeros','Quanto é 3 + 1?',
      ['4️⃣','4'],['3️⃣','3'],['5️⃣','5'],['6️⃣','6']),
    q(150,'numeros','Quantos dias tem uma semana?',
      ['7️⃣','7 dias'],['5️⃣','5 dias'],['6️⃣','6 dias'],['8️⃣','8 dias']),

    // ── 16. FAMÍLIA ───────────────────────────────────────────────────────
    q(151,'familia','Quem é a mãe do seu pai ou da sua mãe?',
      ['👵','Avó'],['👩','Tia'],['👧','Prima'],['👩‍🏫','Professora']),
    q(152,'familia','Quem é o irmão do seu pai ou da sua mãe?',
      ['🧑','Tio'],['👴','Avô'],['👦','Primo'],['🧔','Padrinho']),
    q(153,'familia','Como chamamos o filho ou a filha dos nossos tios?',
      ['🧒','Primo ou prima'],['👦','Irmão'],['👧','Irmã'],['👶','Bebê']),
    q(154,'familia','Quem nos cuida, nos ama e é casada com nosso pai?',
      ['🤱','Mãe'],['👵','Avó'],['👩','Tia'],['👩‍🏫','Professora']),
    q(155,'familia','Como chamamos o pai do nosso pai?',
      ['👴','Avô'],['🧔','Tio'],['👨','Pai'],['🧑','Primo']),
    q(156,'familia','Como chamamos o bebê que ainda está na barriga da mamãe?',
      ['🤰','Bebê por vir'],['👶','Bebê recém-nascido'],['🍼','Neném'],['👧','Criança']),
    q(157,'familia','Quem são as pessoas que moram na mesma casa com você?',
      ['👨‍👩‍👧','Família'],['👫','Amigos'],['🏫','Colegas'],['🧑‍🤝‍🧑','Vizinhos']),
    q(158,'familia','Como chamamos o irmão mais novo?',
      ['👶','Irmão caçula'],['👦','Irmão mais velho'],['🧒','Primo'],['👧','Irmã gêmea']),
    q(159,'familia','Quem é o pai da sua mãe?',
      ['👴','Avô'],['🧔','Tio'],['👨','Padrasto'],['🧑','Primo']),
    q(160,'familia','Como chamamos quando dois irmãos nascem juntos ao mesmo tempo?',
      ['👯','Gêmeos'],['👫','Primos'],['👦👧','Irmãos normais'],['🍼🍼','Bebês']),

    // ── 17. EMOÇÕES ───────────────────────────────────────────────────────
    q(161,'emocoes','Como você fica quando ganha um presente?',
      ['😊','Feliz'],['😢','Triste'],['😨','Com medo'],['😤','Bravo']),
    q(162,'emocoes','Como você fica quando perde um brinquedo?',
      ['😢','Triste'],['😊','Feliz'],['😤','Bravo'],['😨','Com medo']),
    q(163,'emocoes','Como você fica quando tem um monstro no sonho?',
      ['😨','Com medo'],['😊','Feliz'],['😢','Triste'],['🤩','Animado']),
    q(164,'emocoes','Como você fica quando alguém pega seu brinquedo sem pedir?',
      ['😤','Bravo'],['😊','Feliz'],['😢','Triste'],['🤩','Animado']),
    q(165,'emocoes','Como você fica quando vai viajar de férias?',
      ['🤩','Animado'],['😢','Triste'],['😨','Com medo'],['😴','Com sono']),
    q(166,'emocoes','Como você fica quando ve algo novo e quer entender?',
      ['🤔','Curioso'],['😊','Feliz'],['😢','Triste'],['😴','Com sono']),
    q(167,'emocoes','Como você fica quando alguém te dá um abraço carinhoso?',
      ['🥰','Amado'],['😨','Com medo'],['😤','Bravo'],['😢','Triste']),
    q(168,'emocoes','Como você fica quando come algo muito gostoso?',
      ['😋','Satisfeito'],['😢','Triste'],['😨','Com medo'],['😤','Bravo']),
    q(169,'emocoes','Como você fica quando consegue fazer algo difícil?',
      ['😎','Orgulhoso'],['😢','Triste'],['😨','Com medo'],['😴','Com sono']),
    q(170,'emocoes','Como você fica quando precisa dormir mas ainda quer brincar?',
      ['😴','Com sono'],['🤩','Animado'],['😊','Feliz'],['😋','Satisfeito']),

    // ── 18. CORPO E SENTIDOS ──────────────────────────────────────────────
    q(171,'corpo','Com o que a gente enxerga as coisas?',
      ['👀','Olhos'],['👂','Ouvidos'],['👃','Nariz'],['👋','Mãos']),
    q(172,'corpo','Com o que a gente ouve música e conversas?',
      ['👂','Ouvidos'],['👀','Olhos'],['👃','Nariz'],['👅','Língua']),
    q(173,'corpo','Com o que a gente cheira flores e comida?',
      ['👃','Nariz'],['👂','Ouvidos'],['👀','Olhos'],['👋','Mãos']),
    q(174,'corpo','Com o que a gente come e fala?',
      ['👅','Boca'],['👀','Olhos'],['👂','Ouvidos'],['👃','Nariz']),
    q(175,'corpo','Com o que a gente abraça as pessoas?',
      ['💪','Braços'],['🦵','Pernas'],['👆','Dedos'],['🦶','Pés']),
    q(176,'corpo','Com o que a gente chuta a bola?',
      ['🦵','Pernas e pés'],['💪','Braços'],['👋','Mãos'],['🤜','Punhos']),
    q(177,'corpo','Qual parte do corpo fica no alto, onde está o cérebro?',
      ['🧠','Cabeça'],['💪','Braço'],['🦵','Perna'],['🫀','Peito']),
    q(178,'corpo','O que fica dentro do peito e bate sem parar?',
      ['🫀','Coração'],['🧠','Cérebro'],['🫁','Pulmão'],['🦴','Osso']),
    q(179,'corpo','Com o que a gente pega e segura as coisas?',
      ['✋','Mãos'],['🦵','Pernas'],['💪','Braços'],['🦶','Pés']),
    q(180,'corpo','Com o que a gente corre e pula?',
      ['🦵','Pernas'],['💪','Braços'],['✋','Mãos'],['🧠','Cabeça']),

    // ── 19. ESCOLA ────────────────────────────────────────────────────────
    q(181,'escola','O que usamos para escrever no papel?',
      ['✏️','Lápis'],['🖍️','Giz de cera'],['🖊️','Caneta'],['🖌️','Pincel']),
    q(182,'escola','O que usamos para apagar o que o lápis escreveu?',
      ['📝','Borracha'],['✂️','Tesoura'],['📏','Régua'],['📐','Compasso']),
    q(183,'escola','O que o professor usa para escrever na parede da sala?',
      ['📋','Quadro e giz'],['✏️','Lápis'],['📄','Papel'],['📚','Livro']),
    q(184,'escola','O que carregamos nas costas com os livros da escola?',
      ['🎒','Mochila'],['👜','Bolsa'],['🧳','Mala'],['📦','Caixa']),
    q(185,'escola','O que usamos para cortar papel com segurança?',
      ['✂️','Tesoura'],['🔪','Faca'],['📏','Régua'],['🖊️','Caneta']),
    q(186,'escola','O que usamos para pintar com cores vivas?',
      ['🖍️','Giz de cera'],['✏️','Lápis'],['📏','Régua'],['📎','Clipe']),
    q(187,'escola','Quem ensina e ajuda as crianças na escola?',
      ['👩‍🏫','Professora'],['👩‍⚕️','Médica'],['👮','Policial'],['👩‍🍳','Cozinheira']),
    q(188,'escola','Como se chama o lugar onde as crianças estudam?',
      ['🏫','Escola'],['🏥','Hospital'],['🏪','Loja'],['🏠','Casa']),
    q(189,'escola','O que usamos para medir o tamanho de coisas?',
      ['📏','Régua'],['✏️','Lápis'],['📎','Clipe'],['📚','Livro']),
    q(190,'escola','O que toca para chamar os alunos para a aula?',
      ['🔔','Sino'],['📯','Trompete'],['🥁','Tambor'],['🎺','Corneta']),

    // ── 20. TRANSPORTES ───────────────────────────────────────────────────
    q(191,'transportes','O que tem 4 rodas, motor e leva a família?',
      ['🚗','Carro'],['🚌','Ônibus'],['🚂','Trem'],['🚁','Helicóptero']),
    q(192,'transportes','O que voa pelo céu e leva muitos passageiros?',
      ['✈️','Avião'],['🚀','Foguete'],['🚁','Helicóptero'],['🎈','Balão']),
    q(193,'transportes','O que tem 2 rodas e pedais, sem motor?',
      ['🚲','Bicicleta'],['🛵','Moto'],['🚗','Carro'],['🛴','Patinete']),
    q(194,'transportes','O que anda em trilhos de ferro?',
      ['🚂','Trem'],['🚗','Carro'],['🚌','Ônibus'],['🚁','Helicóptero']),
    q(195,'transportes','O que flutua e viaja na água?',
      ['⛵','Barco'],['🚗','Carro'],['🚲','Bicicleta'],['✈️','Avião']),
    q(196,'transportes','O que tem motor mas só 2 rodas?',
      ['🛵','Moto'],['🚗','Carro'],['🚲','Bicicleta'],['🛴','Patinete']),
    q(197,'transportes','O que leva muitas pessoas pela cidade com paradas?',
      ['🚌','Ônibus'],['🚗','Carro'],['🚲','Bicicleta'],['🚂','Trem']),
    q(198,'transportes','O que sobe e desce dentro dos prédios?',
      ['🛗','Elevador'],['🚗','Carro'],['🛴','Patinete'],['🚲','Bicicleta']),
    q(199,'transportes','O que voa bem alto sem motor a jato?',
      ['🎈','Balão'],['✈️','Avião'],['🚀','Foguete'],['🚁','Helicóptero']),
    q(200,'transportes','O que carrega muita carga nas estradas?',
      ['🚛','Caminhão'],['🚗','Carro'],['🚌','Ônibus'],['🚂','Trem']),

    // ── 21. PROFISSÕES ────────────────────────────────────────────────────
    q(201,'profissoes','Quem cuida das pessoas doentes?',
      ['👩‍⚕️','Médica'],['👩‍🏫','Professora'],['👮','Policial'],['🧑‍🚒','Bombeiro']),
    q(202,'profissoes','Quem apaga os incêndios e salva pessoas?',
      ['🧑‍🚒','Bombeiro'],['👮','Policial'],['👩‍⚕️','Médica'],['👷','Pedreiro']),
    q(203,'profissoes','Quem ensina as crianças na escola?',
      ['👩‍🏫','Professora'],['👩‍⚕️','Médica'],['👮','Policial'],['🧑‍🍳','Cozinheiro']),
    q(204,'profissoes','Quem protege e mantém a ordem na cidade?',
      ['👮','Policial'],['🧑‍🚒','Bombeiro'],['👩‍⚕️','Médica'],['👷','Pedreiro']),
    q(205,'profissoes','Quem pilota o avião?',
      ['👨‍✈️','Piloto'],['👩‍⚕️','Médica'],['👮','Policial'],['🧑‍🚀','Astronauta']),
    q(206,'profissoes','Quem constrói casas e prédios?',
      ['👷','Pedreiro'],['👮','Policial'],['🧑‍🚒','Bombeiro'],['🧑‍🍳','Cozinheiro']),
    q(207,'profissoes','Quem corta e cuida do cabelo?',
      ['💇','Cabeleireiro'],['👩‍⚕️','Médica'],['🧑‍🍳','Cozinheiro'],['👩‍🏫','Professora']),
    q(208,'profissoes','Quem cozinha nos restaurantes?',
      ['🧑‍🍳','Chef de cozinha'],['👩‍⚕️','Médica'],['👩‍🏫','Professora'],['👮','Policial']),
    q(209,'profissoes','Quem entrega cartas e encomendas na porta de casa?',
      ['📬','Carteiro'],['👮','Policial'],['🧑‍🚒','Bombeiro'],['👷','Pedreiro']),
    q(210,'profissoes','Quem cuida dos animais quando ficam doentes?',
      ['👩‍⚕️','Veterinário'],['👩‍🏫','Professora'],['🧑‍🍳','Cozinheiro'],['👷','Pedreiro']),

    // ── 22. ALIMENTOS E BEBIDAS ───────────────────────────────────────────
    q(211,'alimentos','Qual alimento é feito de leite e tem buracos?',
      ['🧀','Queijo'],['🥛','Leite'],['🍦','Sorvete'],['🥚','Ovo']),
    q(212,'alimentos','Qual bebida é branca e vem da vaca?',
      ['🥛','Leite'],['💧','Água'],['🧃','Suco'],['☕','Café']),
    q(213,'alimentos','Qual alimento é doce, de chocolate, e derrete na boca?',
      ['🍫','Chocolate'],['🍪','Biscoito'],['🍰','Bolo'],['🍬','Bala']),
    q(214,'alimentos','Qual alimento é massa comprida com molho vermelho?',
      ['🍝','Macarrão'],['🍕','Pizza'],['🌮','Taco'],['🍞','Pão']),
    q(215,'alimentos','Qual alimento é feito com farinha e vai ao forno?',
      ['🍞','Pão'],['🍕','Pizza'],['🥞','Panqueca'],['🍪','Biscoito']),
    q(216,'alimentos','Qual bebida é feita espremendo laranjas?',
      ['🧃','Suco de laranja'],['🥛','Leite'],['💧','Água'],['☕','Chá']),
    q(217,'alimentos','Qual alimento é redondo, tem queijo e a gente corta em fatias?',
      ['🍕','Pizza'],['🍔','Hambúrguer'],['🥞','Panqueca'],['🌮','Taco']),
    q(218,'alimentos','Qual alimento tem casca e é frito ou cozido no café da manhã?',
      ['🍳','Ovo'],['🥞','Panqueca'],['🥐','Croissant'],['🥣','Cereal']),
    q(219,'alimentos','Qual sobremesa é fria, colorida e derrete no calor?',
      ['🍦','Sorvete'],['🍰','Bolo'],['🍪','Biscoito'],['🍫','Chocolate']),
    q(220,'alimentos','Qual alimento são bolinhas vermelhas em molho e vai na pizza?',
      ['🍅','Molho de tomate'],['🍓','Morango'],['🍒','Cereja'],['🫐','Mirtilo']),

    // ── 23. ROUPAS E ACESSÓRIOS ───────────────────────────────────────────
    q(221,'roupas','O que colocamos nos pés para sair na rua?',
      ['👟','Sapato ou tênis'],['🧤','Luva'],['🧣','Cachecol'],['🎩','Chapéu']),
    q(222,'roupas','O que colocamos nas mãos quando está muito frio?',
      ['🧤','Luva'],['👟','Tênis'],['🧣','Cachecol'],['🎩','Chapéu']),
    q(223,'roupas','O que colocamos na cabeça para se proteger do frio?',
      ['🎩','Gorro ou touca'],['🧤','Luva'],['👟','Tênis'],['🩳','Short']),
    q(224,'roupas','O que usamos para nadar na piscina?',
      ['🩱','Maio ou sunga'],['🧥','Casaco'],['👗','Vestido'],['🧣','Cachecol']),
    q(225,'roupas','O que colocamos por cima de tudo quando está frio?',
      ['🧥','Casaco'],['👗','Vestido'],['🩱','Maiô'],['🩳','Short']),
    q(226,'roupas','O que colocamos nos pés dentro do sapato?',
      ['🧦','Meia'],['🩴','Sandália'],['👟','Tênis'],['👠','Salto']),
    q(227,'roupas','O que as meninas usam nas festas e é comprido?',
      ['👗','Vestido'],['🩳','Short'],['🧥','Casaco'],['🎩','Chapéu']),
    q(228,'roupas','O que usamos nas pernas e tem zíper ou botão?',
      ['👖','Calça'],['👗','Vestido'],['🩳','Short'],['🧤','Luva']),
    q(229,'roupas','O que cobre o tronco, tem mangas e botões?',
      ['👕','Camisa'],['👖','Calça'],['🧥','Casaco'],['👗','Vestido']),
    q(230,'roupas','O que colocamos nos olhos para proteger do sol?',
      ['🕶️','Óculos de sol'],['🎩','Chapéu'],['🧤','Luva'],['🧣','Cachecol']),

    // ── 24. OBJETOS DA CASA ───────────────────────────────────────────────
    q(231,'objetos_casa','O que usamos para dormir à noite?',
      ['🛏️','Cama'],['🛋️','Sofá'],['🪑','Cadeira'],['🛀','Banheira']),
    q(232,'objetos_casa','O que usamos para sentar confortavelmente na sala?',
      ['🛋️','Sofá'],['🪑','Cadeira'],['🛏️','Cama'],['🚽','Vaso']),
    q(233,'objetos_casa','O que usamos para comer a sopa e o arroz?',
      ['🍽️','Prato'],['🥣','Tigela'],['🥤','Copo'],['🫙','Pote']),
    q(234,'objetos_casa','O que seguramos para beber água e suco?',
      ['🥤','Copo'],['🍽️','Prato'],['🍴','Garfo'],['🥄','Colher']),
    q(235,'objetos_casa','O que usamos para cozinhar o feijão no fogão?',
      ['🫕','Panela'],['🍽️','Prato'],['🥤','Copo'],['🍴','Garfo']),
    q(236,'objetos_casa','O que usamos para varrer o chão da cozinha?',
      ['🧹','Vassoura'],['🪣','Balde'],['🧽','Esponja'],['🪥','Escova']),
    q(237,'objetos_casa','O que mantém a comida fria para não estragar?',
      ['❄️','Geladeira'],['🔥','Fogão'],['📦','Armário'],['🪣','Balde']),
    q(238,'objetos_casa','O que usamos para assistir filmes e desenhos?',
      ['📺','Televisão'],['💻','Computador'],['📻','Rádio'],['📱','Celular']),
    q(239,'objetos_casa','O que abre e fecha a porta da casa?',
      ['🔑','Chave'],['🔒','Cadeado'],['🚪','Porta'],['🪛','Chave de fenda']),
    q(240,'objetos_casa','O que ilumina o quarto quando está escuro?',
      ['💡','Lâmpada'],['🕯️','Vela'],['🔦','Lanterna'],['⭐','Estrela']),

    // ── 25. BRINQUEDOS E DIVERSÃO ─────────────────────────────────────────
    q(241,'brinquedos','Com o que a gente joga futebol?',
      ['⚽','Bola'],['🏏','Taco'],['🎾','Raquete'],['🏒','Hóquei']),
    q(242,'brinquedos','Qual brinquedo voa com o vento e tem linha?',
      ['🪁','Pipa'],['✈️','Avião'],['🎈','Balão'],['🦋','Borboleta']),
    q(243,'brinquedos','Qual brinquedo tem pecinhas coloridas para montar?',
      ['🧱','Blocos de montar'],['🎲','Dado'],['🧩','Quebra-cabeça'],['🎮','Videogame']),
    q(244,'brinquedos','Qual brinquedo é uma boneca com roupinhas?',
      ['🧸','Boneca'],['🎮','Videogame'],['⚽','Bola'],['🧩','Quebra-cabeça']),
    q(245,'brinquedos','Qual brinquedo tem 3 rodas e anda na calçada?',
      ['🛴','Patinete'],['🚲','Bicicleta'],['🛹','Skate'],['🛻','Carrinho']),
    q(246,'brinquedos','Qual é a brincadeira de parquinho que vai para cima e para baixo?',
      ['🎡','Gangorra'],['🎢','Escorregador'],['🎠','Balanço'],['🪀','Ioiô']),
    q(247,'brinquedos','Qual brinquedo pequeno tem rodas e imita carros?',
      ['🚗','Carrinho'],['⚽','Bola'],['🧸','Urso de pelúcia'],['🎲','Dado']),
    q(248,'brinquedos','O que você usa para pintar um desenho bonito?',
      ['🖌️','Pincel e tinta'],['✂️','Tesoura'],['📏','Régua'],['📚','Livro']),
    q(249,'brinquedos','Qual brinquedo tem peças que você encaixa para formar uma figura?',
      ['🧩','Quebra-cabeça'],['🎲','Dado'],['⚽','Bola'],['🧸','Pelúcia']),
    q(250,'brinquedos','Qual brinquedo gira no dedo ou no chão?',
      ['🪀','Pião'],['⚽','Bola'],['🧸','Pelúcia'],['🎲','Dado']),

  ];
})();
