/* Banco de perguntas — 500 questões em 26 categorias
   Formato: q(id, categoria, pergunta, [certa], [errada1], [errada2], [errada3])
   Cada opção é [emoji, label] ou [emoji, label, 'img/options/arquivo.webp']
   Quando há imagem, ela substitui o emoji na tela (emoji ainda serve de fallback).
   O jogo embaralha as opções antes de exibir. */
const QUESTIONS = (function () {
  function q(id, cat, text, c, w1, w2, w3) {
    return {
      id, category: cat, question: text,
      options: [
        { emoji: c[0],  label: c[1],  correct: true,  image: c[2]  },
        { emoji: w1[0], label: w1[1], correct: false, image: w1[2] },
        { emoji: w2[0], label: w2[1], correct: false, image: w2[2] },
        { emoji: w3[0], label: w3[1], correct: false, image: w3[2] },
      ]
    };
  }

  return [

    // ── 1. ANIMAIS DOMÉSTICOS ──────────────────────────────────────────────
    q(1,'animais_domesticos','Qual é o animal que late?',
      ['🐶','Cachorro'],['🐱','Gato'],['🐄','Vaca'],['🐸','Sapo']),
    q(2,'animais_domesticos','Qual animal que mia?',
      ['🐱','Gato'],['🐶','Cachorro'],['🐟','Peixe'],['🐰','Coelho']),
    q(3,'animais_domesticos','Qual animal ronrona quando está feliz?',
      ['🐱','Gato'],['🐶','Cachorro'],['🐟','Peixe'],['🦜','Papagaio','img/options/papagaio.webp']),
    q(4,'animais_domesticos','Qual animal tem orelhas longas e adora cenoura?',
      ['🐰','Coelho'],['🐱','Gato'],['🐶','Cachorro'],['🐢','Tartaruga']),
    q(5,'animais_domesticos','Qual animal guarda a casa e late?',
      ['🐶','Cachorro'],['🐱','Gato'],['🐰','Coelho'],['🐢','Tartaruga']),
    q(6,'animais_domesticos','Qual animal tem penas coloridas e fica em gaiola?',
      ['🦜','Papagaio','img/options/papagaio.webp'],['🐶','Cachorro'],['🐟','Peixe'],['🐱','Gato']),
    q(7,'animais_domesticos','Qual animal tem carapaça e anda bem devagar?',
      ['🐢','Tartaruga'],['🐰','Coelho'],['🐶','Cachorro'],['🦜','Papagaio','img/options/papagaio.webp']),
    q(8,'animais_domesticos','Qual animal é chamado de "melhor amigo do homem"?',
      ['🐶','Cachorro'],['🐱','Gato'],['🐰','Coelho'],['🐟','Peixe']),
    q(9,'animais_domesticos','Qual animal tem bigode e caça ratinhos?',
      ['🐱','Gato'],['🐶','Cachorro'],['🦜','Papagaio','img/options/papagaio.webp'],['🐢','Tartaruga']),
    q(10,'animais_domesticos','Qual animal nada no aquário?',
      ['🐟','Peixe','img/options/peixe_dourado.webp'],['🐱','Gato'],['🐶','Cachorro'],['🐰','Coelho']),

    // ── 2. ANIMAIS SELVAGENS ───────────────────────────────────────────────
    q(11,'animais_selvagens','Qual animal é o rei da selva?',
      ['🦁','Leão'],['🐘','Elefante'],['🐯','Tigre'],['🦒','Girafa']),
    q(12,'animais_selvagens','Qual animal tem tromba longa?',
      ['🐘','Elefante'],['🦁','Leão'],['🦒','Girafa'],['🐊','Jacaré']),
    q(13,'animais_selvagens','Qual animal tem pescoço muito longo?',
      ['🦒','Girafa'],['🐘','Elefante'],['🦁','Leão'],['🐻','Urso']),
    q(14,'animais_selvagens','Qual animal tem listras pretas e laranja?',
      ['🐯','Tigre'],['🦁','Leão'],['🐆','Leopardo'],['🐻','Urso']),
    q(15,'animais_selvagens','Qual animal tem listras e parece um cavalo?',
      ['🦓','Zebra'],['🐴','Cavalo'],['🐯','Tigre'],['🦌','Veado']),
    q(16,'animais_selvagens','Qual animal tem uma bolsa na barriga?',
      ['🦘','Cangurú'],['🐨','Coala'],['🐼','Panda'],['🦙','Lhama']),
    q(17,'animais_selvagens','Qual animal come bambú e é preto e branco?',
      ['🐼','Panda'],['🦁','Leão'],['🐘','Elefante'],['🦘','Cangurú']),
    q(18,'animais_selvagens','Qual animal tem chifre no nariz?',
      ['🦏','Rinoceronte'],['🐘','Elefante'],['🦒','Girafa'],['🐊','Jacaré']),
    q(19,'animais_selvagens','Qual animal pula de árvore em árvore?',
      ['🐒','Macaco'],['🦁','Leão'],['🐘','Elefante'],['🐊','Jacaré']),
    q(20,'animais_selvagens','Qual animal tem penas rosas e fica numa perna só?',
      ['🦩','Flamingo'],['🦅','Águia'],['🦜','Papagaio','img/options/papagaio.webp'],['🦆','Pato']),

    // ── 3. ANIMAIS MARINHOS ────────────────────────────────────────────────
    q(21,'animais_marinhos','Qual animal marinho tem 8 tentáculos?',
      ['🐙','Polvo'],['🦈','Tubarão'],['🐬','Golfinho'],['🦞','Lagosta']),
    q(22,'animais_marinhos','Qual animal tem grandes dentes e é muito perigoso?',
      ['🦈','Tubarão'],['🐬','Golfinho'],['🐋','Baleia'],['🦭','Foca']),
    q(23,'animais_marinhos','Qual animal marinho é inteligente e salta fora da água?',
      ['🐬','Golfinho'],['🦈','Tubarão'],['🐙','Polvo'],['🦑','Lula']),
    q(24,'animais_marinhos','Qual é o maior animal que vive no mar?',
      ['🐋','Baleia'],['🦈','Tubarão'],['🐬','Golfinho'],['🦭','Foca']),
    q(25,'animais_marinhos','Qual animal marinho tem 5 braços?',
      ['⭐','Estrela-do-mar', 'img/options/estrela_do_mar.webp'],['🐙','Polvo'],['🦑','Lula'],['🦀','Caranguejo']),
    q(26,'animais_marinhos','Qual animal marinho tem pinças e anda de lado?',
      ['🦀','Caranguejo'],['🦞','Lagosta'],['🦂','Escorpião'],['🐙','Polvo']),
    q(27,'animais_marinhos','Qual animal marinho é transparente e queima a pele?',
      ['🪼','Água-viva'],['🐙','Polvo'],['🦑','Lula'],['🐚','Caracol']),
    q(28,'animais_marinhos','Qual animal marinho tem "cavalo" no nome?',
      ['🐴','Cavalo-marinho','img/options/cavalo_marinho.webp'],['🦈','Tubarão'],['🐬','Golfinho'],['🐙','Polvo']),
    q(29,'animais_marinhos','Qual animal marinho tem antenas e é muito saboroso?',
      ['🦞','Lagosta'],['🦀','Caranguejo'],['🐙','Polvo'],['🦑','Lula']),
    q(30,'animais_marinhos','Qual animal nada mas parece um pássaro?',
      ['🐧','Pinguim'],['🦅','Águia'],['🦆','Pato'],['🦢','Cisne']),

    // ── 4. ANIMAIS DA FAZENDA ─────────────────────────────────────────────
    q(31,'animais_fazenda','Qual animal da fazenda nos dá leite?',
      ['🐄','Vaca'],['🐷','Porco'],['🐔','Galinha'],['🐴','Cavalo']),
    q(32,'animais_fazenda','Qual animal acorda todos cantando de manhã?',
      ['🐓','Galo'],['🐔','Galinha'],['🦆','Pato'],['🐄','Vaca']),
    q(33,'animais_fazenda','Qual animal da fazenda tem lã quentinha?',
      ['🐑','Ovelha'],['🐐','Cabra'],['🐄','Vaca'],['🐷','Porco']),
    q(34,'animais_fazenda','Qual animal da fazenda põe ovos?',
      ['🐔','Galinha'],['🐄','Vaca'],['🐑','Ovelha'],['🐷','Porco']),
    q(35,'animais_fazenda','Qual animal é usado para cavalgar?',
      ['🐴','Cavalo'],['🐄','Vaca'],['🐷','Porco'],['🐑','Ovelha']),
    q(36,'animais_fazenda','Qual animal da fazenda nada muito bem?',
      ['🦆','Pato'],['🐔','Galinha'],['🐓','Galo'],['🦃','Peru']),
    q(37,'animais_fazenda','Qual animal da fazenda tem focinho e é rosado?',
      ['🐷','Porco'],['🐄','Vaca'],['🐑','Ovelha'],['🐴','Cavalo']),
    q(38,'animais_fazenda','Qual é o pequeno inseto que produz mel?',
      ['🐝','Abelha'],['🦋','Borboleta'],['🐛','Lagarta'],['🐞','Joaninha']),
    q(39,'animais_fazenda','Qual animal tem chifres e gosta de pular nas coisas?',
      ['🐐','Cabra'],['🐂','Touro'],['🐄','Vaca'],['🐑','Ovelha']),
    q(40,'animais_fazenda','Qual animal da fazenda tem lã e é fofinho?',
      ['🐑','Ovelha'],['🐄','Vaca'],['🐴','Cavalo'],['🐷','Porco']),

    // ── 5. INSETOS E PEQUENOS ANIMAIS ─────────────────────────────────────
    q(41,'insetos','Qual inseto faz mel delicioso?',
      ['🐝','Abelha'],['🦋','Borboleta'],['🐞','Joaninha'],['🐜','Formiga']),
    q(42,'insetos','Qual inseto tem asas coloridas e bonitas?',
      ['🦋','Borboleta'],['🐝','Abelha'],['🐞','Joaninha'],['🦗','Grilo']),
    q(43,'insetos','Qual inseto é vermelho com pontinhos pretos?',
      ['🐞','Joaninha'],['🦋','Borboleta'],['🐜','Formiga'],['🐝','Abelha']),
    q(44,'insetos','Qual pequeno animal constrói teias para pegar comida?',
      ['🕷️','Aranha'],['🐜','Formiga'],['🦗','Grilo'],['🐝','Abelha']),
    q(45,'insetos','Qual inseto vira borboleta depois de um tempo?',
      ['🐛','Lagarta'],['🐜','Formiga'],['🦗','Grilo'],['🐝','Abelha']),
    q(46,'insetos','Qual inseto canta de noite?',
      ['🦗','Grilo'],['🐝','Abelha'],['🦋','Borboleta'],['🐞','Joaninha']),
    q(47,'insetos','Qual inseto mora em colméia e tem rainha?',
      ['🐝','Abelha'],['🐜','Formiga'],['🦗','Grilo'],['🦋','Borboleta']),
    q(48,'insetos','Qual pequeno animal tem 8 patas?',
      ['🕷️','Aranha'],['🐜','Formiga'],['🦗','Grilo'],['🐝','Abelha']),
    q(49,'insetos','Qual inseto pula muito alto e tem asas?',
      ['🦗','Gafanhoto'],['🐝','Abelha'],['🐛','Lagarta'],['🐞','Joaninha']),
    q(50,'insetos','Qual pequeno animal tem concha e deixa um rastro brilhante?',
      ['🐌','Caracol'],['🐜','Formiga'],['🕷️','Aranha'],['🐛','Lagarta']),

    // ── 6. PÁSSAROS ────────────────────────────────────────────────────────
    q(51,'passaros','Qual pássaro não consegue voar?',
      ['🐧','Pinguim'],['🦅','Águia'],['🦜','Papagaio','img/options/papagaio.webp'],['🐦','Pardal']),
    q(52,'passaros','Qual pássaro tem cauda colorida e longa como um leque?',
      ['🦚','Pavão'],['🦜','Papagaio','img/options/papagaio.webp'],['🦩','Flamingo'],['🦅','Águia']),
    q(53,'passaros','Qual pássaro bate o bico na árvore para encontrar comida?',
      ['🐦','Pica-pau'],['🦜','Papagaio','img/options/papagaio.webp'],['🦅','Águia'],['🐧','Pinguim']),
    q(54,'passaros','Qual pássaro fica de pé em uma perna só?',
      ['🦩','Flamingo'],['🦅','Águia'],['🐧','Pinguim'],['🦢','Cisne']),
    q(55,'passaros','Qual pássaro é símbolo da paz?',
      ['🕊️','Pomba'],['🦅','Águia'],['🦜','Papagaio','img/options/papagaio.webp'],['🦚','Pavão']),
    q(56,'passaros','Qual pássaro faz tem olhos grandes e voa a noite?',
      ['🦉','Coruja'],['🦜','Papagaio','img/options/papagaio.webp'],['🐧','Pinguim'],['🦢','Cisne']),
    q(57,'passaros','Qual pássaro tem pescoço longo e é elegante?',
      ['🦢','Cisne'],['🐧','Pinguim'],['🦩','Flamingo'],['🦅','Águia']),
    q(58,'passaros','Qual pássaro repete o que a gente fala?',
      ['🦜','Papagaio','img/options/papagaio.webp'],['🦉','Coruja'],['🦢','Cisne'],['🐧','Pinguim']),
    q(59,'passaros','Qual pássaro voa muito alto e tem visão aguçada?',
      ['🦅','Águia'],['🦜','Papagaio','img/options/papagaio.webp'],['🦉','Coruja'],['🐧','Pinguim']),
    q(60,'passaros','Qual pássaro é muito comum nas cidades?',
      ['🕊️','Pardal', 'img/options/pardal.webp'],['🦅','Águia'],['🦜','Papagaio','img/options/papagaio.webp'],['🦩','Flamingo']),

    // ── 7. DINOSSAUROS ────────────────────────────────────────────────────
    q(61,'dinossauros','Qual dinossauro tinha pescoço muito, muito longo?',
      ['🦕','Braquiossauro'],['🦖','T-Rex'],['🐊','Crocodilo'],['🦎','Lagarto']),
    q(62,'dinossauros','Qual dinossauro era carnívoro e tinha bracinhos pequenos?',
      ['🦖','Tiranossauro Rex','img/options/tiranossauro_azul.webp'],['🦕','Braquiossauro'],['🦎','Lagarto'],['🐊','Crocodilo']),
    q(63,'dinossauros','Qual dinossauro tinha três chifres na cabeça?',
      ['🦏','Tricerátops','img/options/triceratops.webp'],['🦖','T-Rex'],['🦕','Braquiossauro'],['🐉','Dragão']),
    q(64,'dinossauros','Qual dinossauro tinha placas ósseas nas costas?',
      ['🦎','Estegossauro'],['🦖','T-Rex'],['🦕','Braquiossauro'],['🐊','Crocodilo']),
    q(65,'dinossauros','Qual dinossauro voava no céu pré-histórico?',
      ['🦅','Pterossauro','img/options/pterodactilo.webp'],['🦕','Braquiossauro'],['🦖','T-Rex'],['🦋','Borboleta']),
    q(66,'dinossauros','Como se chama a era dos dinossauros?',
      ['🦖','Jurássica'],['❄️','Gelo'],['🌊','Mar'],['🔥','Fogo']),
    q(67,'dinossauros','Qual dinossauro vivia na água e tinha pescoço longo?',
      ['🐍','Plesiosaurus'],['🦕','Braquiossauro'],['🦖','T-Rex'],['🐊','Crocodilo']),
    q(68,'dinossauros','Qual dinossauro era pequeno, rápido e inteligente?',
      ['🦎','Velociraptor'],['🦖','T-Rex'],['🦕','Braquiossauro'],['🐊','Crocodilo']),
    q(69,'dinossauros','Qual dinossauro tinha cauda com marreta?',
      ['🪨','Anquilossauro', 'img/options/dino_rabo_marreta.webp'],['🦖','T-Rex'],['🦕','Braquiossauro'],['🦎','Estegossauro']),
    q(70,'dinossauros','O que os cientistas estudam para saber sobre dinossauros?',
      ['🦴','Fósseis','img/options/fossil.webp'],['📚','Livros'],['🔭','Telescópio'],['🧪','Química']),

    // ── 8. FRUTAS ─────────────────────────────────────────────────────────
    q(71,'frutas','Qual fruta é vermelha e tem as sementes por fora?',
      ['🍓','Morango'],['🍎','Maçã'],['🍒','Cereja'],['🍉','Melancia']),
    q(72,'frutas','Qual fruta tem casca amarela e é curva?',
      ['🍌','Banana'],['🍋','Limão'],['🍑','Pêssego'],['🍊','Tangerina']),
    q(73,'frutas','Qual fruta é igual uma marca de celular?',
      ['🍎','Maçã'],['🍅','Tomate'],['🍒','Cereja'],['🍓','Morango']),
    q(74,'frutas','Qual fruta é roxa e cresce em cacho?',
      ['🍇','Uva'],['🫐','Mirtilo'],['🍆','Berinjela'],['🟣','Ameixa']),
    q(75,'frutas','Qual fruta é laranja por dentro e por fora?',
      ['🍊','Laranja'],['🍋','Limão'],['🍑','Pêssego'],['🥭','Manga']),
    q(76,'frutas','Qual fruta é bem grande, verde por fora e vermelha por dentro?',
      ['🍉','Melancía'],['🍈','Melão'],['🥝','Kiwi'],['🍐','Pera']),
    q(77,'frutas','Qual fruta tem espinhos por fora e uma corôa?',
      ['🍍','Abacaxi'],['🍋','Limão'],['🥭','Manga'],['🍈','Melão']),
    q(78,'frutas','Qual fruta é pequena, amarela e muito azeda?',
      ['🍋','Limão'],['🍌','Banana'],['🍊','Laranja'],['🍎','Maçã']),
    q(79,'frutas','Qual fruta é tropical e super doce?',
      ['🥭','Manga'],['🍌','Banana'],['🍋','Limão'],['🍊','Laranja']),
    q(80,'frutas','Qual fruta é pequena, vermelha e tem um carôço bem grande?',
      ['🍒','Cereja'],['🍓','Morango'],['🍎','Maçã'],['🫐','Mirtilo']),

    // ── 9. VEGETAIS ───────────────────────────────────────────────────────
    q(81,'vegetais','Qual vegetal é laranja e cresce debaixo da terra?',
      ['🥕','Cenoura'],['🍊','Laranja'],['🥔','Batata'],['🌽','Milho']),
    q(82,'vegetais','Qual vegetal é verde e parece uma árvorezinha?',
      ['🥦','Brócolis'],['🌿','Hortelã'],['🥬','Alface'],['🌱','Muda']),
    q(83,'vegetais','Qual vegetal é vermelho e comemos na salada?',
      ['🍅','Tomate'],['🍎','Maçã'],['🫑','Pimentão'],['🧅','Cebola']),
    q(84,'vegetais','Qual vegetal é preto ou roxo, e se faz parmegiana?',
      ['🍆','Berinjela'],['🟣','Ameixa'],['🫐','Mirtilo'],['🧅','Cebola']),
    q(85,'vegetais','Qual vegetal faz chorar quando o cortamos?',
      ['🧅','Cebola'],['🧄','Alho'],['🥔','Batata'],['🌽','Milho']),
    q(86,'vegetais','Qual vegetal é verde e comprido como um barco?',
      ['🥒','Pepino'],['🥬','Alface'],['🌿','Erva'],['🥦','Brócolis']),
    q(87,'vegetais','Qual vegetal são bolinhas verdes dentro de uma vagem?',
      ['🫛','Ervilha'],['🍏','Uva verde'],['🥬','Alface'],['🥦','Brócolis']),
    q(88,'vegetais','Qual vegetal tem folhas verdes e vai na salada?',
      ['🥬','Alface'],['🌿','Salsinha'],['🥦','Brócolis'],['🌱','Muda']),
    q(89,'vegetais','Qual vegetal é amarelo e tem "cabelo" de sêda?',
      ['🌽','Milho'],['🍌','Banana'],['🍋','Limão'],['🧅','Cebola']),
    q(90,'vegetais','Qual vegetal podemos escolher verde, amarelo ou vermelho?',
      ['🫑','Pimentão vermelho'],['🍅','Tomate'],['🍓','Morango'],['🍎','Maçã']),

    // ── 10. NATUREZA E PLANTAS ────────────────────────────────────────────
    q(91,'natureza','Qual parte da planta fica debaixo da terra?',
      ['🌱','Raiz','img/options/raiz.webp'],['🍃','Folha'],['🌸','Flor'],['🪵','Tronco']),
    q(92,'natureza','O que acontece com as flores quando chove?',
      ['💧','Bebem água'],['🔥','Secam'],['❄️','Congelam'],['💨','Voam']),
    q(93,'natureza','Qual parte colorida das flores atrai as borboletas?',
      ['🌸','Pétalas'],['🍃','Folhas'],['🌱','Raízes'],['🪵','Caule']),
    q(94,'natureza','Qual planta tem espinhos e não precisa de muita água?',
      ['🌵','Cacto'],['🌲','Pinheiro'],['🌴','Palmeira'],['🌿','Samambaia']),
    q(95,'natureza','O que a abelha tira das flores para fazer mel?',
      ['🌸','Néctar'],['💧','Água'],['🍯','Mel'],['🟡','Pólen']),
    q(96,'natureza','O que plantamos para virar uma nova planta?',
      ['🌰','Semente'],['🍃','Folha'],['🌸','Flor'],['🍎','Fruto']),
    q(97,'natureza','Qual é a cor da maioria das folhas das árvores?',
      ['🟢','Verde'],['🟡','Amarelo'],['🟠','Laranja'],['🔴','Vermelho']),
    q(98,'natureza','O que as plantas precisam para crescer, além de água?',
      ['☀️','Luz do sol'],['🌙','Lua'],['⭐','Estrelas'],['🌧️','Tempestade']),
    q(99,'natureza','Como se chama a parte marrom e alta das árvores?',
      ['🪵','Tronco'],['🌱','Raiz'],['🍃','Galho'],['🌸','Copa']),
    q(100,'natureza','O que as árvores soltam que faz bem para nós respirarmos?',
      ['💨','Oxigênio'],['💧','Água'],['🔥','Calor'],['❄️','Frio']),

    // ── 11. ESTAÇÕES DO ANO ───────────────────────────────────────────────
    q(101,'estacoes','Em qual estação as folhas caem das árvores?',
      ['🍂','Outono'],['🌸','Primavera'],['☀️','Verão'],['❄️','Inverno']),
    q(102,'estacoes','Em qual estação faz mais calor e vamos à praia?',
      ['☀️','Verão'],['🍂','Outono'],['🌸','Primavera'],['❄️','Inverno']),
    q(103,'estacoes','Em qual estação as flores brotam e tudo fica colorido?',
      ['🌸','Primavera'],['☀️','Verão'],['🍂','Outono'],['❄️','Inverno']),
    q(104,'estacoes','Em qual estação faz mais frio e pode nevar?',
      ['❄️','Inverno'],['🍂','Outono'],['🌸','Primavera'],['☀️','Verão']),
    q(105,'estacoes','Qual estação vem logo depois do verão?',
      ['🍂','Outono'],['❄️','Inverno'],['🌸','Primavera'],['☀️','Verão']),
    q(106,'estacoes','Em qual estação as árvores ficam sem folhas?',
      ['❄️','Inverno'],['🍂','Outono'],['🌸','Primavera'],['☀️','Verão']),
    q(107,'estacoes','Quantas estações do ano existem?',
      ['4️⃣','Quatro'],['3️⃣','Três'],['2️⃣','Duas'],['6️⃣','Seis']),
    q(108,'estacoes','Em qual estação os dias são mais longos e as noites mais curtas?',
      ['☀️','Verão'],['❄️','Inverno'],['🍂','Outono'],['🌸','Primavera']),
    q(109,'estacoes','Qual estação vem depois do inverno?',
      ['🌸','Primavera'],['☀️','Verão'],['🍂','Outono'],['❄️','Inverno']),
    q(110,'estacoes','Em qual estação o carnaval acontece no Brasil?',
      ['☀️','Verão'],['🍂','Outono'],['🌸','Primavera'],['❄️','Inverno']),

    // ── 12. CLIMA E TEMPO ─────────────────────────────────────────────────
    q(111,'clima','O que cai do céu quando está chovendo?',
      ['🌧️','Chuva'],['❄️','Neve'],['🌪️','Vento'],['⚡','Raio']),
    q(112,'clima','Como se chama um arco colorido formado no céu depois da chuva?',
      ['🌈','Arco-íris'],['☀️','Sol'],['🌙','Lua'],['⭐','Estrela']),
    q(113,'clima','O que cobre o chão quando faz muito frio lá fora?',
      ['❄️','Neve'],['🌧️','Chuva'],['🌫️','Neblina'],['🌪️','Vento']),
    q(114,'clima','Como se chama o ar que sopra e balança as árvores?',
      ['💨','Vento'],['🌧️','Chuva'],['❄️','Neve'],['⚡','Raio']),
    q(115,'clima','O que aparece no céu de noite, bonita e brilhante?',
      ['🌙','Lua'],['⭐','Estrela'],['☀️','Sol'],['🌈','Arco-íris']),
    q(116,'clima','O que acontece quando há muitos raios e trovões?',
      ['⛈️','Tempestade'],['❄️','Neve'],['🌈','Arco-íris'],['☀️','Sol forte']),
    q(117,'clima','Como se chama a nuvem que desce e fica próxima ao chão?',
      ['🌫️','Neblina'],['🌧️','Chuva'],['❄️','Neve'],['💨','Vento']),
    q(118,'clima','O que acontece com a água quando faz muito frio?',
      ['🧊','Congela'],['💧','Evapora'],['🌊','Chove'],['💨','Vira vento']),
    q(119,'clima','O que são as pedrinhas de gelo que caem do céu?',
      ['🧊','Granizo'],['❄️','Neve'],['🌧️','Chuva'],['💧','Orvalho']),
    q(120,'clima','Quando está muito quente, o que fazemos para nos refrescar?',
      ['🏊','Nadar'],['🧥','Colocar casaco'],['🔥','Acender fogo'],['❄️','Ficar na neve']),

    // ── 13. CORES ─────────────────────────────────────────────────────────
    q(121,'cores','Qual é a cor do céu num dia ensolarado?',
      ['🔵','Azul'],['🟢','Verde'],['🟡','Amarelo'],['🔴','Vermelho']),
    q(122,'cores','Qual é a cor da grama e das folhas?',
      ['🟢','Verde'],['🟡','Amarelo'],['🔵','Azul'],['🟤','Marrom']),
    q(123,'cores','Qual é a cor do sol?',
      ['🟡','Amarelo'],['🟠','Laranja'],['🔴','Vermelho'],['⚪','Branco']),
    q(124,'cores','Qual é a cor do sangue?',
      ['🔴','Vermelho'],['🟠','Laranja'],['🟣','Roxo'],['🟤','Marrom']),
    q(125,'cores','Qual cor se forma quando misturamos azul e amarelo?',
      ['🟢','Verde'],['🟠','Laranja'],['🟣','Roxo'],['🟤','Marrom']),
    q(126,'cores','Qual é a cor da noite e do carvão?',
      ['⚫','Preto'],['🔵','Azul marinho'],['🟤','Marrom'],['🟣','Roxo']),
    q(127,'cores','Qual é a cor da neve e das nuvens?',
      ['⚪','Branco'],['🔵','Azul'],['🟡','Amarelo'],['⚫','Cinza']),
    q(128,'cores','Qual é a cor do suco de uva?',
      ['🟣','Roxo'],['🔵','Azul'],['🔴','Vermelho'],['🟠','Laranja']),
    q(129,'cores','Qual cor se forma quando misturamos vermelho e amarelo?',
      ['🟠','Laranja'],['🟣','Roxo'],['🟢','Verde'],['🟤','Marrom']),
    q(130,'cores','Qual é a cor do chocolate e da terra?',
      ['🟤','Marrom'],['⚫','Preto'],['🟠','Laranja'],['🔴','Vermelho']),

    // ── 14. FORMAS GEOMÉTRICAS ────────────────────────────────────────────
    q(131,'formas','Qual forma tem apenas 3 lados?',
      ['🔺','Triângulo'],['⬛','Quadrado'],['⬜','Retângulo'],['🔶','Losango']),
    q(132,'formas','Qual forma tem 4 lados todos iguais?',
      ['⬛','Quadrado'],['⬜','Retângulo'],['🔺','Triângulo'],['🔶','Losango']),
    q(133,'formas','Qual forma não tem lados e é redonda?',
      ['⚪','Círculo'],['⬛','Quadrado'],['🔺','Triângulo'],['⬜','Retângulo']),
    q(134,'formas','Qual forma tem 4 lados e dois deles são maiores?',
      ['▬','Retângulo','img/options/retangulo.webp'],['⬛','Quadrado'],['🔺','Triângulo'],['🔶','Losango']),
    q(135,'formas','Como se chama a forma do ovo?',
      ['🥚','Oval'],['⭐','Estrela'],['🔺','Pentágono'],['⬛','Quadrado']),
    q(136,'formas','Qual forma tem 5 pontas e usamos para desenhar no céu?',
      ['⭐','Estrela'],['🔺','Triângulo'],['🛑','Hexágono'],['🔶','Losango']),
    q(137,'formas','Como se chama uma bola em 3D?',
      ['🔵','Esfera'],['⚪','Círculo'],['⬛','Cubo'],['🔺','Cone']),
    q(138,'formas','Como se chama uma caixa em 3D?',
      ['🧊','Cubo'],['🔵','Esfera'],['🔺','Pirâmide'],['🪨','Pedra']),
    q(139,'formas','Como se chama a forma do ovo?',
      ['🥚','Oval'],['⚪','Círculo'],['⬛','Quadrado'],['🔺','Triângulo']),
    q(140,'formas','Como se chama o formato de uma pizza inteira?',
      ['⚪','Círculo'],['⬛','Quadrado'],['⬜','Retângulo'],['🔺','Triângulo']),

    // ── 15. NÚMEROS E QUANTIDADES ─────────────────────────────────────────
    q(141,'numeros','Quantas patas tem um cachorro?',
      ['4️⃣','4 patas'],['2️⃣','2 patas'],['6️⃣','6 patas'],['8️⃣','8 patas']),
    q(142,'numeros','Quantos dedos tem uma mão?',
      ['5️⃣','5 dedos'],['4️⃣','4 dedos'],['6️⃣','6 dedos'],['3️⃣','3 dedos']),
    q(143,'numeros','Quantos olhos tem uma pessoa?',
      ['2️⃣','2 olhos'],['1️⃣','1 olho'],['4️⃣','4 olhos'],['3️⃣','3 olhos']),
    q(144,'numeros','Quantas rodas tem uma bicicleta?',
      ['2️⃣','2 rodas'],['4️⃣','4 rodas'],['3️⃣','3 rodas'],['1️⃣','1 roda']),
    q(145,'numeros','Quantas patas tem os insetos?',
      ['6️⃣','6 patas'],['4️⃣','4 patas'],['8️⃣','8 patas'],['2️⃣','2 patas']),
    q(146,'numeros','Quantas patas tem uma aranha?',
      ['8️⃣','8 patas'],['6️⃣','6 patas'],['4️⃣','4 patas'],['2️⃣','2 patas']),
    q(147,'numeros','Quantos lados tem um triângulo?',
      ['3️⃣','3 lados'],['4️⃣','4 lados'],['5️⃣','5 lados'],['2️⃣','2 lados']),
    q(148,'numeros','Quanto é 2 + 2?',
      ['4️⃣','4'],['3️⃣','3'],['5️⃣','5'],['2️⃣','2']),
    q(149,'numeros','Quanto é 3 + 1?',
      ['4️⃣','4'],['3️⃣','3'],['5️⃣','5'],['6️⃣','6']),
    q(150,'numeros','Quantos dias tem uma semana?',
      ['7️⃣','7 dias'],['5️⃣','5 dias'],['6️⃣','6 dias'],['8️⃣','8 dias']),

    // ── 16. FAMÍLIA ───────────────────────────────────────────────────────
    q(151,'familia','Quem é a mãe do seu pai ou da sua mãe?',
      ['👵','Avó'],['👩','Tia'],['👧','Prima'],['👩‍🏫','Professora']),
    q(152,'familia','Quem é o irmão do seu pai ou da sua mãe?',
      ['🧑','Tio'],['👴','Avô'],['👦','Primo'],['🧔','Padrinho']),
    q(153,'familia','Como chamamos o filho ou a filha dos nossos tios?',
      ['🧒','Primo ou prima'],['👦','Irmão'],['👧','Irmã'],['👶','Bebê']),
    q(154,'familia','Quem nos dá carinho e cuida de nós quando nascemos?',
      ['🤱','Mãe'],['👵','Avó'],['👩','Tia'],['👩‍🏫','Professora']),
    q(155,'familia','Como chamamos o pai do nosso pai?',
      ['👴','Avô'],['🧔','Tio'],['👨','Pai'],['🧑','Primo']),
    q(156,'familia','O que os bebês gostam de beber?',
      ['🍼','Mamadeira'],['🧃','Suco'],['🚰','Água'],['🥤','refrigerante']),
    q(157,'familia','Quem são as pessoas que moram na mesma casa com você?',
      ['👨‍👩‍👧','Família'],['👫','Amigos'],['🏫','Colegas'],['🧑‍🤝‍🧑','Vizinhos']),
    q(158,'familia','Como chamamos o irmão mais novo?',
      ['👶','Irmão caçula'],['👦','Irmão mais velho'],['🧒','Primo'],['👧','Irmã gêmea']),
    q(159,'familia','Quem é o pai da sua mãe?',
      ['👴','Avô'],['🧔','Tio'],['👨','Padrasto'],['🧑','Primo']),
    q(160,'familia','Como chamamos quando dois irmãos nascem juntos ao mesmo tempo?',
      ['👯','Gêmeos'],['👫','Primos'],['👦👧','Irmãos normais'],['🍼🍼','Bebês']),

    // ── 17. EMOÇÕES ───────────────────────────────────────────────────────
    q(161,'emocoes','Como você fica quando ganha um presente?',
      ['😊','Feliz'],['😢','Triste'],['😨','Com medo'],['😤','Bravo']),
    q(162,'emocoes','Como você fica quando perde um brinquedo?',
      ['😢','Triste'],['😊','Feliz'],['😤','Bravo'],['😨','Com medo']),
    q(163,'emocoes','Como você fica quando sonha com um monstro?',
      ['😨','Com medo'],['😊','Feliz'],['😢','Triste'],['🤩','Animado']),
    q(164,'emocoes','Como você fica quando alguém pega seu brinquedo sem pedir?',
      ['😤','Bravo'],['😊','Feliz'],['😢','Triste'],['🤩','Animado']),
    q(165,'emocoes','Como você fica quando vai viajar de férias?',
      ['🤩','Animado'],['😢','Triste'],['😨','Com medo'],['😴','Com sono']),
    q(166,'emocoes','Como você fica quando vê algo novo e quér entender?',
      ['🤔','Curioso'],['😊','Feliz'],['😢','Triste'],['😴','Com sono']),
    q(167,'emocoes','Como você fica quando alguém te dá um abraço carinhoso?',
      ['🥰','Amado'],['😨','Com medo'],['😤','Bravo'],['😢','Triste']),
    q(168,'emocoes','Como você fica quando come algo muito gostoso?',
      ['😋','Satisfeito'],['😢','Triste'],['😨','Com medo'],['😤','Bravo']),
    q(169,'emocoes','Como você fica quando consegue fazer algo difícil?',
      ['😎','Orgulhoso'],['😢','Triste'],['😨','Com medo'],['😴','Com sono']),
    q(170,'emocoes','Como você fica quando alguém conta uma historinha pra dormir?',
      ['😴','Com sono'],['🤩','Animado'],['😊','Feliz'],['😋','Satisfeito']),

    // ── 18. CORPO E SENTIDOS ──────────────────────────────────────────────
    q(171,'corpo','Com o que a gente enxerga as coisas?',
      ['👀','Olhos'],['👂','Ouvidos'],['👃','Nariz'],['👋','Mãos']),
    q(172,'corpo','Com o que a gente ouve música e conversas?',
      ['👂','Ouvidos'],['👀','Olhos'],['👃','Nariz'],['👅','Língua']),
    q(173,'corpo','Com o que a gente cheira flores e comida?',
      ['👃','Nariz'],['👂','Ouvidos'],['👀','Olhos'],['👋','Mãos']),
    q(174,'corpo','Com o que a gente come e fala?',
      ['👄','Boca'],['👀','Olhos'],['👂','Ouvidos'],['👃','Nariz']),
    q(175,'corpo','Com o que a gente abraça as pessoas?',
      ['💪','Braços'],['🦵','Pernas'],['👆','Dedos'],['🦶','Pés']),
    q(176,'corpo','Com o que a gente chuta a bola?',
      ['🦶','Pés'],['💪','Braços'],['👋','Mãos'],['🤜','Punhos']),
    q(177,'corpo','Qual parte do corpo fica no alto, onde está o cérebro?',
      ['🤯','Cabeça'],['💪','Braço'],['🦵','Perna'],['🫀','Peito']),
    q(178,'corpo','O que fica dentro do peito e bate sem parar?',
      ['🫀','Coração'],['🧠','Cérebro'],['🫁','Pulmão'],['🦴','Osso']),
    q(179,'corpo','Com o que a gente pega e segura as coisas?',
      ['✋','Mãos'],['🦵','Pernas'],['💪','Braços'],['🦶','Pés']),
    q(180,'corpo','Com o que a gente corre e pula?',
      ['🦵','Pernas'],['💪','Braços'],['✋','Mãos'],['🧠','Cabeça']),

    // ── 19. ESCOLA ────────────────────────────────────────────────────────
    q(181,'escola','Com o quê podemos escrever e apagar depois?',
      ['✏️','Lápis'],['🖍️','Giz de cera'],['🖊️','Caneta'],['🖌️','Pincel']),
    q(182,'escola','O que usamos para apagar o que o lápis escreveu?',
      ['📝','Borracha'],['✂️','Tesoura'],['📏','Régua'],['📐','Compasso']),
    q(183,'escola','O que o professor usa para escrever na parede da sala?',
      ['📋','Lousa e giz'],['✏️','Lápis'],['📄','Papel'],['📚','Livro']),
    q(184,'escola','O que carregamos nas costas com os livros da escola?',
      ['🎒','Mochila'],['👜','Bolsa'],['🧳','Mala'],['📦','Caixa']),
    q(185,'escola','O que usamos para cortar papel com segurança?',
      ['✂️','Tesoura'],['🔪','Faca'],['📏','Régua'],['🖊️','Caneta']),
    q(186,'escola','O que usamos para pintar com cores vivas?',
      ['🖍️','Giz de cera'],['📕','Livro'],['📏','Régua'],['📎','Clipe']),
    q(187,'escola','Quem ensina e ajuda as crianças na escola?',
      ['👩‍🏫','Professora'],['👩‍⚕️','Médica'],['👮','Policial'],['👩‍🍳','Cozinheira']),
    q(188,'escola','Como se chama o lugar onde as crianças estudam?',
      ['🏫','Escola'],['🏥','Hospital'],['🏪','Loja'],['🏠','Casa']),
    q(189,'escola','O que usamos para medir o tamanho de coisas pequenas?',
      ['📏','Régua'],['✏️','Lápis'],['📎','Clipe'],['📚','Livro']),
    q(190,'escola','O que toca para chamar os alunos para a aula?',
      ['🔔','Sino'],['📯','Trompete'],['🥁','Tambor'],['🎺','Corneta']),

    // ── 20. TRANSPORTES ───────────────────────────────────────────────────
    q(191,'transportes','O que tem 4 rodas, motor e leva a família?',
      ['🚗','Carro'],['🚌','Ônibus'],['🚂','Trem'],['🚁','Helicóptero']),
    q(192,'transportes','O que voa pelo céu e leva muitos passageiros?',
      ['✈️','Avião'],['🚀','Foguete'],['🚁','Helicóptero'],['🎈','Balão']),
    q(193,'transportes','O que tem 2 rodas e pedais, sem motor?',
      ['🚲','Bicicleta'],['🛵','Moto'],['🚗','Carro'],['🛴','Patinete']),
    q(194,'transportes','O que anda em trilhos de ferro?',
      ['🚂','Trem'],['🚗','Carro'],['🚌','Ônibus'],['🚁','Helicóptero']),
    q(195,'transportes','O que flutua e viaja na água?',
      ['⛵','Barco'],['🚗','Carro'],['🚲','Bicicleta'],['✈️','Avião']),
    q(196,'transportes','O que tem motor e tem só 2 rodas?',
      ['🛵','Moto'],['🚗','Carro'],['🚲','Bicicleta'],['🛴','Patinete']),
    q(197,'transportes','O que é bem grande e transporta muitas pessoas pela cidade?',
      ['🚌','Ônibus'],['🚗','Carro'],['🚲','Bicicleta'],['🚂','Trem']),
    q(198,'transportes','O que você usa para subir e descer dentro dos prédios?',
      ['🛗','Elevador'],['🚗','Carro'],['🛴','Patinete'],['🚲','Bicicleta']),
    q(199,'transportes','O que o pescador usa para ir pescar no rio ou no mar?',
      ['🚣','Canoa'],['✈️','Avião'],['🚀','Foguete'],['🚁','Helicóptero']),
    q(200,'transportes','O que carrega muita carga nas estradas?',
      ['🚛','Caminhão'],['🚗','Carro'],['🚌','Ônibus'],['🚂','Trem']),

    // ── 21. PROFISSÕES ────────────────────────────────────────────────────
    q(201,'profissoes','Quem cuida das pessoas doentes?',
      ['👩‍⚕️','Médica'],['👩‍🏫','Professora'],['👮','Policial'],['🧑‍🚒','Bombeiro']),
    q(202,'profissoes','Quem apaga os incêndios e salva pessoas?',
      ['🧑‍🚒','Bombeiro'],['👮','Policial'],['👩‍⚕️','Médica'],['👷','Pedreiro']),
    q(203,'profissoes','Quem ensina as crianças na escola?',
      ['👩‍🏫','Professora'],['👩‍⚕️','Médica'],['👮','Policial'],['🧑‍🍳','Cozinheiro']),
    q(204,'profissoes','Quem protege e mantém a ordem na cidade?',
      ['👮','Policial'],['🧑‍🚒','Bombeiro'],['👩‍⚕️','Médica'],['👷','Pedreiro']),
    q(205,'profissoes','Quem pilota o avião?',
      ['👨‍✈️','Piloto'],['👩‍⚕️','Médica'],['👮','Policial'],['🧑‍🚀','Astronauta']),
    q(206,'profissoes','Quem constrói casas e prédios?',
      ['👷','Pedreiro'],['👮','Policial'],['🧑‍🚒','Bombeiro'],['🧑‍🍳','Cozinheiro']),
    q(207,'profissoes','Quem corta e cuida do cabelo?',
      ['💇','Cabeleireiro'],['👩‍⚕️','Médica'],['🧑‍🍳','Cozinheiro'],['👩‍🏫','Professora']),
    q(208,'profissoes','Quem cozinha nos restaurantes?',
      ['🧑‍🍳','Chef de cozinha'],['👩‍⚕️','Médica'],['👩‍🏫','Professora'],['👮','Policial']),
    q(209,'profissoes','Quem entrega cartas e encomendas na porta de casa?',
      ['📬','Carteiro'],['👮','Policial'],['🧑‍🚒','Bombeiro'],['👷','Pedreiro']),
    q(210,'profissoes','Quem cuida dos animais quando ficam doentes?',
      ['👩‍⚕️🐶','Veterinário'],['👩‍🏫','Professora'],['🧑‍🍳','Cozinheiro'],['👷','Pedreiro']),

    // ── 22. ALIMENTOS E BEBIDAS ───────────────────────────────────────────
    q(211,'alimentos','Qual alimento é feito de leite e tem buracos?',
      ['🧀','Queijo'],['🥛','Leite'],['🍦','Sorvete'],['🥚','Ovo']),
    q(212,'alimentos','Qual bebida é branca e vem da vaquinha?',
      ['🥛','Leite'],['💧','Água'],['🧃','Suco'],['☕','Café']),
    q(213,'alimentos','Qual alimento é feito com cacau, e derrete na boca?',
      ['🍫','Chocolate'],['🍪','Biscoito'],['🍰','Bolo'],['🍬','Bala']),
    q(214,'alimentos','Qual alimento é uma massa comprida com molho vermelho?',
      ['🍝','Macarrão'],['🍕','Pizza'],['🌮','Taco'],['🍞','Pão']),
    q(215,'alimentos','Qual alimento é feito na padaria?',
      ['🍞','Pão'],['🍕','Pizza'],['🥞','Panqueca'],['🍦','Sorvete']),
    q(216,'alimentos','Qual bebida é feita espremendo uma fruta?',
      ['🧃','Suco'],['🥛','Leite'],['💧','Água'],['☕','Chá']),
    q(217,'alimentos','Qual alimento é redondo, tem queijo e a gente corta em fatias?',
      ['🍕','Pizza'],['🍔','Hambúrguer'],['🥞','Panqueca'],['🌮','Taco']),
    q(218,'alimentos','Qual alimento tem casca e é frito ou cozido no café da manhã?',
      ['🍳','Ovo'],['🥞','Panqueca'],['🥐','Croissant'],['🥣','Cereal']),
    q(219,'alimentos','Qual sobremesa é gelada, colorida e derrete no calor?',
      ['🍦','Sorvete'],['🍰','Bolo'],['🍪','Biscoito'],['🍫','Chocolate']),
    q(220,'alimentos','Com qual alimento fazemos o molho vermelho da pizza?',
      ['🍅','tomate'],['🍓','Morango'],['🍒','Cereja'],['🫐','Mirtilo']),

    // ── 23. ROUPAS E ACESSÓRIOS ───────────────────────────────────────────
    q(221,'roupas','O que geralmente colocamos nos pés para sair na rua?',
      ['👟','Sapato ou tênis'],['🧤','Luva'],['🧣','Cachecol'],['🎩','Chapéu']),
    q(222,'roupas','O que colocamos nas mãos quando está muito frio?',
      ['🧤','Luva'],['👟','Tênis'],['🧣','Cachecol'],['🎩','Chapéu']),
    q(223,'roupas','O que colocamos na cabeça para se proteger do frio?',
      ['🎩','Gorro ou touca','img/options/gorro.webp'],['🧤','Luva'],['👟','Tênis'],['🩳','Short']),
    q(224,'roupas','O que usamos para nadar na piscina?',
      ['🩱','Maiô ou sunga'],['🧥','Casaco'],['👗','Vestido'],['🧣','Cachecol']),
    q(225,'roupas','O que podemos colocar por cima de tudo quando está frio?',
      ['🧥','Casaco'],['👗','Vestido'],['🩱','Maiô'],['🩳','Short']),
    q(226,'roupas','O que colocamos nos pés dentro do sapato?',
      ['🧦','Meia'],['🩴','Sandália'],['👟','Tênis'],['👠','Salto']),
    q(227,'roupas','O que as meninas usam nas festas e é comprido?',
      ['👗','Vestido'],['🩳','Short'],['🧥','Casaco'],['🎩','Chapéu']),
    q(228,'roupas','O que usamos nas pernas e tem zíper ou botão?',
      ['👖','Calça'],['👗','Vestido'],['🩳','Short'],['🧤','Luva']),
    q(229,'roupas','O que usamos no calor para cobrir o tronco e tem mangas?',
      ['👕','Camisa'],['👖','Calça'],['🧥','Casaco'],['👗','Vestido']),
    q(230,'roupas','O que colocamos nos olhos para proteger do sol?',
      ['🕶️','Óculos de sol'],['🎩','Chapéu'],['🧤','Luva'],['🧣','Cachecol']),

    // ── 24. OBJETOS DA CASA ───────────────────────────────────────────────
    q(231,'objetos_casa','O que usamos para deitar e dormir à noite?',
      ['🛏️','Cama'],['🛋️','Sofá'],['🪑','Cadeira'],['🛀','Banheira']),
    q(232,'objetos_casa','O que usamos para sentar confortavelmente na sala?',
      ['🛋️','Sofá'],['🪑','Cadeira'],['🛏️','Cama'],['🚽','Vaso']),
    q(233,'objetos_casa','Em qual objeto colocamos o arroz e feijão para comer?',
      ['🍽️','Prato'],['🥣','Tigela'],['🥤','Copo'],['🫙','Pote']),
    q(234,'objetos_casa','O que seguramos para beber água e suco?',
      ['🥤','Copo'],['🍽️','Prato'],['🍴','Garfo'],['🥄','Colher']),
    q(235,'objetos_casa','O que usamos para cozinhar o feijão no fogão?',
      ['🫕','Panela'],['🍽️','Prato'],['🥤','Copo'],['🍴','Garfo']),
    q(236,'objetos_casa','O que usamos para varrer o chão da cozinha?',
      ['🧹','Vassoura'],['🪣','Balde'],['🧽','Esponja'],['🪥','Escova']),
    q(237,'objetos_casa','O que mantém a comida fria para não estragar?',
      ['❄️','Geladeira', 'img/options/geladeira.webp'],['🔥','Fogão'],['📦','Armário'],['🪣','Balde']),
    q(238,'objetos_casa','O que podemos usar para ver filmes e desenhos com a família?',
      ['📺','Televisão'],['💻','Computador'],['📻','Rádio'],['📱','Celular']),
    q(239,'objetos_casa','O que abre e fecha a porta da casa?',
      ['🔑','Chave'],['🔒','Cadeado'],['🚪','Porta'],['🪛','Chave de fenda']),
    q(240,'objetos_casa','O que geralmente ilumina o quarto quando está escuro?',
      ['💡','Lâmpada'],['🕯️','Vela'],['🔦','Lanterna'],['⭐','Estrela']),

    // ── 25. BRINQUEDOS E DIVERSÃO ─────────────────────────────────────────
    q(241,'brinquedos','Com o que a gente joga futebol?',
      ['⚽','Bola'],['🏏','Taco'],['🎾','Raquete'],['🏒','Hóquei']),
    q(242,'brinquedos','Qual brinquedo voa com o vento e tem uma linha comprida?',
      ['🪁','Pipa'],['✈️','Avião'],['🎈','Balão'],['🦋','Borboleta']),
    q(243,'brinquedos','Qual brinquedo é de tijolinhos para montar?',
      ['🧱','Blocos de montar'],['🎲','Dado'],['🧩','Quebra-cabeça'],['🎮','Videogame']),
    q(244,'brinquedos','Qual brinquedo pode usar roupinhas?',
      ['🧸','Boneca'],['🎮','Videogame'],['⚽','Bola'],['🧩','Quebra-cabeça']),
    q(245,'brinquedos','Qual desses brinquedos tem 3 rodinhas?',
      ['🛴','Patinete'],['🚲','Bicicleta'],['🛹','Skate'],['🛻','Carrinho']),
    q(246,'brinquedos','Qual é a brincadeira de parquinho que balança cima e para baixo?',
      ['🎠','Balanço', 'img/options/balanco.webp'],['🎡','Gangorra'],['🎢','Escorregador'],['🪀','Ioiô']),
    q(247,'brinquedos','Qual desses brinquedos tem rodinhas?',
      ['🚗','Carrinho'],['⚽','Bola'],['🧸','Urso de pelúcia'],['🎲','Dado']),
    q(248,'brinquedos','O que você usa para pintar um desenho?',
      ['🖌️','Pincel e tinta'],['✂️','Tesoura'],['📏','Régua'],['📚','Livro']),
    q(249,'brinquedos','Qual brinquedo tem muitas e muitas peças para encaixar?',
      ['🧩','Quebra-cabeça'],['🎲','Dado'],['⚽','Bola'],['🧸','Pelúcia']),
    q(250,'brinquedos','Qual brinquedo gira rápido no chão?',
      ['🪀','Pião','img/options/piao.webp'],['⚽','Bola'],['🧸','Pelúcia'],['🎲','Dado']),

    // ── 1b. ANIMAIS DOMÉSTICOS (novas) ────────────────────────────────────────
    q(251,'animais_domesticos','Qual animal pequeno corre numa rodinha?',
      ['🐹','Hamster'],['🐱','Gato'],['🐶','Cachorro'],['🐰','Coelho']),
    q(252,'animais_domesticos','Qual animal de estimação tem penas coloridas e imita vozes?',
      ['🦜','Papagaio','img/options/papagaio.webp'],['🐟','Peixe'],['🐢','Tartaruga'],['🐶','Cachorro']),
    q(253,'animais_domesticos','Qual animal parece um lagarto?',
      ['🦎','Iguana'],['🐢','Tartaruga'],['🐍','Cobra'],['🦜','Papagaio','img/options/papagaio.webp']),
    q(254,'animais_domesticos','Qual animal nada no aquário?',
      ['🐠','Peixinho','img/options/peixe_dourado.webp'],['🦈','Tubarão'],['🐙','Polvo'],['🐸','Sapo']),
    q(255,'animais_domesticos','Qual animal de estimação late e quer passear todo dia?',
      ['🐶','Cachorro'],['🐱','Gato'],['🐰','Coelho'],['🦜','Papagaio','img/options/papagaio.webp']),
    q(256,'animais_domesticos','Qual animal de estimação mia quando quer atenção?',
      ['🐱','Gato'],['🐶','Cachorro'],['🐟','Peixe'],['🐢','Tartaruga']),
    q(257,'animais_domesticos','Qual animal tem orelhas rosadas e pula bastante?',
      ['🐰','Coelho'],['🐱','Gato'],['🐶','Cachorro'],['🐹','Hamster']),
    q(258,'animais_domesticos','Qual animal fica em gaiola e canta bonito?',
      ['🐦','Canário'],['🦜','Papagaio','img/options/papagaio.webp'],['🐧','Pinguim'],['🦅','Águia']),
    q(259,'animais_domesticos','Qual animal tem carapaça e pode viver até 100 anos?',
      ['🐢','Tartaruga'],['🐍','Cobra'],['🦎','Lagarto'],['🐊','Jacaré']),

    // ── 2b. ANIMAIS SELVAGENS (novas) ─────────────────────────────────────────
    q(260,'animais_selvagens','Qual é o animal mais rápido do mundo?',
      ['🐆','Guepardo'],['🦁','Leão'],['🐯','Tigre'],['🐘','Elefante']),
    q(261,'animais_selvagens','Qual animal tem manchas redondas e sobe em árvores?',
      ['🐆','Onça'],['🦁','Leão'],['🐻','Urso'],['🦒','Girafa']),
    q(262,'animais_selvagens','Qual animal vive em grupo chamado de matilha?',
      ['🐺','Lobo'],['🦁','Leão'],['🐻','Urso'],['🦊','Raposa']),
    q(263,'animais_selvagens','Qual animal do Polo Norte é todo branco e nada bem?',
      ['🐻‍❄️','Urso polar'],['🐺','Lobo'],['🐧','Pinguim'],['🦊','Raposa']),
    q(264,'animais_selvagens','Qual animal pequeno tem cauda listrada e anda na floresta?',
      ['🦝','Guaxinim'],['🐿️','Esquilo'],['🦔','Ouriço'],['🐇','Coelho']),
    q(265,'animais_selvagens','Qual animal tem chifres e é um cervo?',
      ['🦌','Veado'],['🐐','Cabra'],['🐏','Carneiro'],['🦏','Rinoceronte']),
    q(266,'animais_selvagens','Qual animal pequeno e laranja tem cauda espessa e vive na floresta?',
      ['🦊','Raposa'],['🐺','Lobo'],['🦝','Guaxinim'],['🐱','Gato']),
    q(267,'animais_selvagens','Qual animal tem espinhos pelo corpo e se enrola em bola?',
      ['🦔','Ouriço'],['🐛','Lagarta'],['🦝','Guaxinim'],['🐇','Coelho']),
    q(268,'animais_selvagens','Qual animal é um mamífero que voa?',
      ['🦇','Morcego'],['🦉','Coruja'],['🐦','Pardal'],['🦅','Águia']),

    // ── 3b. ANIMAIS MARINHOS (novas) ──────────────────────────────────────────
    q(269,'animais_marinhos','Qual animal marinho tem o corpo achatado e nada ondulando?',
      ['🐟','Arraia', 'img/options/arraia.webp'],['🐠','Peixe-palhaço', 'img/options/peixe_palhaco.webp'],['🦈','Tubarão'],['🐙','Polvo']),
    q(270,'animais_marinhos','Qual animal marinho tem concha em espiral e é mole dentro?',
      ['🐚','Caramujo'],['🦀','Caranguejo'],['🦞','Lagosta'],['🦪','Ostra']),
    q(271,'animais_marinhos','Qual animal marinho é o maior de todos e canta no oceano?',
      ['🐋','Baleia'],['🐬','Golfinho'],['🦈','Tubarão'],['🦑','Lula']),
    q(272,'animais_marinhos','Qual animal marinho é o personagem principal do filme "Nemo"?',
      ['🐠','Peixe-palhaço','img/options/peixe_palhaco.webp'],['🐟','Peixe azul'],['🦈','Tubarão'],['🐡','Peixe-balão']),
    q(273,'animais_marinhos','Qual animal marinho tem concha e vive preso nas rochas?',
      ['🦪','Ostra'],['🐚','Caramujo'],['🦀','Caranguejo'],['🦞','Lagosta']),
    q(274,'animais_marinhos','Qual animal marinho tem tentáculos e muda de cor?',
      ['🐙','Polvo'],['🦑','Lula'],['🪼','Água-viva'],['🐟','Peixe','img/options/peixe_dourado.webp']),
    q(275,'animais_marinhos','Qual animal tem penas e nada no mar gelado mas não voa?',
      ['🐧','Pinguim'],['🦢','Cisne'],['🦆','Pato'],['🦩','Flamingo']),
    q(276,'animais_marinhos','Qual animal marinho tem focinho comprido como uma espada?',
      ['🐟','Peixe-espada', 'img/options/sailfish.webp'],['🦈','Tubarão'],['🐬','Golfinho'],['🐙','Polvo']),
    q(277,'animais_marinhos','Qual animal marinho solta uma tinta preta?',
      ['🐙','Polvo'],['🐚','Caramujo'],['🪼','Água-viva'],['🐠','Peixe-palhaço']),

    // ── 4b. ANIMAIS DA FAZENDA (novas) ────────────────────────────────────────
    q(278,'animais_fazenda','Qual animal da fazenda tem lã quentinha?',
      ['🐑','Ovelha'],['🐐','Cabra'],['🐄','Vaca'],['🐴','Cavalo']),
    q(279,'animais_fazenda','Qual animal da fazenda tem chifres curvos e sobe em pedras?',
      ['🐐','Cabra'],['🐑','Ovelha'],['🐄','Vaca'],['🦃','Peru']),
    q(280,'animais_fazenda','Qual animal da fazenda tem focinho rosado e se rola na lama?',
      ['🐷','Porco'],['🐮','Vaca'],['🐑','Ovelha'],['🐴','Cavalo']),
    q(281,'animais_fazenda','Qual animal da fazenda bica o chão e faz COCORICÓ?',
      ['🐓','Galo'],['🐔','Galinha'],['🦆','Pato'],['🦃','Peru']),
    q(282,'animais_fazenda','Qual animal da fazenda carrega coisas?',
      ['🫏','Burro'],['🐴','Cavalo'],['🐄','Vaca'],['🐑','Ovelha']),
    q(283,'animais_fazenda','Qual animal da fazenda tem plumas lindas e é grande?',
      ['🦃','Peru'],['🐔','Galinha'],['🦆','Pato'],['🐓','Galo']),
    q(284,'animais_fazenda','Qual animal da fazenda nada muito bem?',
      ['🦆','Pato'],['🐔','Galinha'],['🦃','Peru'],['🐓','Galo']),
    q(285,'animais_fazenda','Qual animal da fazenda tem cascos e leva cavaleiros?',
      ['🐴','Cavalo'],['🫏','Burro'],['🐄','Vaca'],['🐑','Ovelha']),
    q(286,'animais_fazenda','Qual pequeno animal da fazenda produz mel na colméia?',
      ['🐝','Abelha'],['🦋','Borboleta'],['🐜','Formiga'],['🦗','Grilo']),

    // ── 5b. INSETOS (novas) ───────────────────────────────────────────────────
    q(287,'insetos','Qual inseto parece um helicóptero?',
      ['🚁','Libélula'],['🦋','Borboleta'],['🐝','Abelha'],['🦟','Mosquito']),
    q(288,'insetos','Qual inseto é verde e parece um galho de planta?',
      ['🌿','Bicho-pau'],['🐛','Lagarta'],['🐜','Formiga'],['🦗','Grilo']),
    q(289,'insetos','Qual inseto tem luz na barriga e brilha à noite?',
      ['✨','Vagalume','img/options/vagalume.webp'],['🐝','Abelha'],['🦋','Borboleta'],['🐜','Formiga']),
    q(290,'insetos','Qual inseto constrói formigueiros subterrâneos?',
      ['🐜','Formiga'],['🐝','Abelha'],['🦋','Borboleta'],['🦗','Grilo']),
    q(291,'insetos','Qual inseto tem asas duras e brilhantes?',
      ['🪲','Besouro'],['🦋','Borboleta'],['🐝','Abelha'],['🦗','Grilo']),
    q(292,'insetos','Qual inseto voa e nos pica deixando coceira?',
      ['🦟','Mosquito'],['🐝','Abelha'],['🦋','Borboleta'],['🐜','Formiga']),
    q(293,'insetos','Qual inseto fica parado como se estivesse rezando?',
      ['🙏','Louva-a-deus','img/options/louva_a_deus.webp'],['🐜','Formiga'],['🦗','Grilo'],['🐛','Lagarta']),
    q(294,'insetos','Qual inseto constrói cupinzeiros de terra?',
      ['🏠','Cupim', 'img/options/cupim.webp'],['🐜','Formiga'],['🦟','Mosquito'],['🐝','Abelha']),
    q(295,'insetos','Qual inseto tem listras amarelas e pretas e pode picar?',
      ['🐝','Vespa'],['🦋','Borboleta'],['🐜','Formiga'],['🪲','Besouro']),

    // ── 6b. PÁSSAROS (novas) ──────────────────────────────────────────────────
    q(296,'passaros','Qual pássaro minúsculo bate as asas muito rápido e bebe néctar?',
      ['🐦','Beija-flor', 'img/options/beija_flor.webp'],['🦜','Papagaio','img/options/papagaio.webp'],['🦅','Águia'],['🐧','Pinguim']),
    q(297,'passaros','Qual pássaro tem bico enorme e colorido e vive na floresta tropical?',
      ['🦜','Tucano','img/options/tucano.webp'],['🦅','Águia'],['🐦','Sabiá', 'img/options/passaro_sabia.webp'],['🦢','Cisne']),
    q(298,'passaros','Qual pássaro vive no Pólo Sul, não voa mas nada muito bem?',
      ['🐧','Pinguim'],['🦢','Cisne'],['🦆','Pato'],['🦩','Flamingo']),
    q(299,'passaros','Qual pássaro é branco, tem pescoço longo e é elegante?',
      ['🦢','Cisne'],['🕊️','Pomba'],['🦩','Flamingo'],['🐧','Pinguim']),
    q(300,'passaros','Qual pássaro bate o bico na madeira das árvores para comer?',
      ['🐦','Pica-pau'],['🦜','Papagaio','img/options/papagaio.webp'],['🦅','Águia'],['🦢','Cisne']),
    q(301,'passaros','Qual pássaro faz ninho no telhado e tem pescoço comprido?',
      ['🦢','Cegonha','img/options/cegonha.webp'],['🦩','Flamingo'],['🕊️','Pomba'],['🦅','Águia']),
    q(302,'passaros','Qual pássaro voa muito alto e tem visão aguçada para caçar?',
      ['🦅','Águia'],['🕊️','Pomba'],['🐧','Pinguim'],['🦜','Papagaio','img/options/papagaio.webp']),
    q(303,'passaros','Qual pássaro tem o peitinho vermelho e canta no jardim?',
      ['🐦','Pintarroxo'],['🦜','Papagaio','img/options/papagaio.webp'],['🦢','Cisne'],['🦅','Águia']),
    q(304,'passaros','Qual pássaro brasileiro canta lindo e é símbolo nacional?',
      ['🐦','Sabiá','img/options/passaro_sabia.webp'],['🦜','Papagaio','img/options/papagaio.webp'],['🦅','Águia'],['🐧','Pinguim']),

    // ── 7b. DINOSSAUROS (novas) ───────────────────────────────────────────────
    q(305,'dinossauros','Qual dinossauro tinha espinhos gigantes nas costas como uma vela?',
      ['🦕','Espinossauro','img/options/espinossauro.webp'],['🦖','T-Rex'],['🐊','Crocodilo'],['🦴','Pterodátilo']),
    q(306,'dinossauros','Qual dinossauro corria em bando e caçava junto?',
      ['🦖','Velociraptor'],['🦕','Braquiossauro'],['🐊','Jacaré'],['🦁','Leão']),
    q(307,'dinossauros','Qual dinossauro herbívoro tinha pescoço médio e era enorme?',
      ['🦕','Brontossauro'],['🦖','Velociraptor'],['🐘','Elefante'],['🦒','Girafa']),
    q(308,'dinossauros','Qual dinossauro tinha cabeça enorme e dentes muito afiados?',
      ['🦖','T-Rex', 'img/options/tiranossauro_azul.webp'],['🦕','Diplodoco'],['🐊','Crocodilo'],['🦁','Leão']),
    q(309,'dinossauros','Qual dinossauro nadava bem e tinha pescoço enorme?',
      ['🐊','Plesiossauro', 'img/options/plesiossauro.webp'],['🦕','Brontossauro'],['🦖','Espinossauro'],['🦖','Velociraptor']),
    q(310,'dinossauros','Qual dinossauro tinha crista colorida na cabeça?',
      ['🦕','Parasaurolofus'],['🦖','T-Rex'],['🐊','Jacaré'],['🦣','Mamute']),
    q(311,'dinossauros','Os dinossauros eram répteis como quais animais de hoje?',
      ['🦎','Lagartos'],['🐟','Peixes'],['🐦','Pássaros'],['🐘','Elefantes']),
    q(312,'dinossauros','Como são chamados os ossos de dinossauro que encontramos hoje?',
      ['🦴','Fósseis', 'img/options/fossil.webp'],['💎','Cristais'],['🪨','Pedras comuns'],['🌱','Sementes']),
    q(313,'dinossauros','Qual dinossauro pequeno e esperto caçava com garras afiadas?',
      ['🦖','Velociraptor'],['🦕','Braquiossauro'],['🐊','Crocodilo'],['🦁','Leão']),

    // ── 8b. FRUTAS (novas) ────────────────────────────────────────────────────
    q(314,'frutas','Qual fruta verde por fora tem sementes pretas por dentro?',
      ['🥝','Kiwi'],['🍈','Melão'],['🍐','Pera'],['🍏','Maçã verde']),
    q(315,'frutas','Qual fruta tem casca grossa e água doce dentro?',
      ['🥥','Coco'],['🍉','Melancia'],['🍋','Limão'],['🍊','Laranja']),
    q(316,'frutas','Qual fruta é pequena e mancha as roupas de roxo?',
      ['🫐','Amora'],['🍇','Uva'],['🍓','Morango'],['🍒','Cereja']),
    q(317,'frutas','Qual fruta tropical tem casca espinhosa e uma coroa?',
      ['🍍','Abacaxi'],['🍌','Banana'],['🥭','Manga'],['🍑','Pêssego']),
    q(318,'frutas','Qual fruta pequena e laranja tem casca fácil de tirar?',
      ['🍊','Tangerina'],['🍋','Limão'],['🍑','Damasco'],['🍎','Maçã']),
    q(319,'frutas','Qual fruta tem casca verde, é cremosa e tem um caroço enorme?',
      ['🥑','Abacate'],['🍐','Pera'],['🍈','Melão'],['🥝','Kiwi']),
    q(320,'frutas','Qual fruta tropical é amarela e tem cheiro forte e doce?',
      ['🥭','Manga'],['🍌','Banana'],['🍍','Abacaxi'],['🍑','Pêssego']),
    q(321,'frutas','Qual fruta é vermelha e as sementinhas ficam para fora?',
      ['🍓','Morango'],['🍒','Cereja'],['🫐','Mirtilo'],['🍇','Uva']),
    q(322,'frutas','Qual fruta tem casca peludinha?',
      ['🥝','Kiwi'],['🍈','Graviola'],['🍐','Pera'],['🥥','Coco']),

    // ── 9b. VEGETAIS (novas) ──────────────────────────────────────────────────
    q(323,'vegetais','Qual vegetal tem folhas crocantes e verdes para salada?',
      ['🥬','Alface'],['🥦','Brócolis'],['🌿','Hortelã'],['🍃','Rúcula']),
    q(324,'vegetais','Qual vegetal é amarelo e cresce em espiga?',
      ['🌽','Milho'],['🥕','Cenoura'],['🧅','Cebola'],['🥔','Batata']),
    q(325,'vegetais','Qual vegetal roxo longo é usado na parmegiana?',
      ['🍆','Berinjela'],['🍅','Tomate'],['🥕','Cenoura'],['🥦','Brócolis']),
    q(326,'vegetais','Qual vegetal pequeno e verde fica dentro de uma vagem?',
      ['🫛','Ervilha'],['🥦','Brócolis'],['🥬','Alface'],['🌽','Milho']),
    q(327,'vegetais','Qual vegetal tem cheiro forte e usamos para temperar?',
      ['🧄','Alho'],['🧅','Cebola'],['🥕','Cenoura'],['🥔','Batata']),
    q(328,'vegetais','Qual vegetal é redondo, vermelho e vai no molho?',
      ['🍅','Tomate'],['🫑','Pimentão'],['🍆','Berinjela'],['🥕','Cenoura']),
    q(329,'vegetais','Qual vegetal tem formato de uma árvore pequena?',
      ['🥦','Brócolis'],['🥬','Alface'],['🥕','Cenoura'],['🌽','Milho']),
    q(330,'vegetais','Qual vegetal laranja os coelhos adoram comer?',
      ['🥕','Cenoura'],['🍅','Tomate'],['🧅','Cebola'],['🥔','Batata']),
    q(331,'vegetais','Qual vegetal verde e comprido tem sementes dentro?',
      ['🥒','Pepino'],['🍆','Berinjela'],['🌽','Milho'],['🥦','Brócolis']),

    // ── 10b. NATUREZA (novas) ─────────────────────────────────────────────────
    q(332,'natureza','Como se chama o conjunto de muitas árvores juntas?',
      ['🌳','Floresta','img/options/floresta.webp'],['🌱','Jardim'],['🌵','Deserto'],['🌊','Oceano']),
    q(333,'natureza','O que sai de um vulcão quando ele explode?',
      ['🌋','Lava'],['💧','Água'],['❄️','Gelo'],['🌪️','Vento']),
    q(334,'natureza','Como se chama a terra preta e fértil que as plantas adoram?',
      ['🌱','Húmus'],['🪨','Pedra'],['🏜️','Areia'],['💧','Água']),
    q(335,'natureza','O que cobre o chão da floresta no outono?',
      ['🍂','Folhas caídas'],['🌸','Flores'],['🌱','Grama'],['❄️','Neve']),
    q(336,'natureza','Qual planta flutua na água e tem flor enorme?',
      ['🌸','Vitória-régia'],['🌹','Rosa'],['🌺','Hibisco'],['🌼','Girassol']),
    q(337,'natureza','Qual planta enfeitamos no Natal?',
      ['🎄','Pinheiro', 'img/options/pinheiro.webp'],['🌹','Rosa'],['🌺','Hibisco'],['🌼','Girassol']),
    q(338,'natureza','Como se chama a gotinha de água que aparece nas folhas de manhã?',
      ['💧','Orvalho'],['🌧️','Chuva'],['❄️','Neve'],['🌊','Mar']),
    q(339,'natureza','Qual planta delicada cresce grudada em outras árvores?',
      ['🌺','Orquídea'],['🌹','Rosa'],['🌼','Girassol'],['🌸','Cerejeira']),
    q(340,'natureza','Como se chama a parte colorida da flor que atrai borboletas?',
      ['🌸','Pétala'],['🌿','Folha'],['🌱','Haste'],['🍂','Semente']),

    // ── 11b. ESTAÇÕES DO ANO (novas) ──────────────────────────────────────────
    q(341,'estacoes','Em qual estação usamos casaco e cachecol?',
      ['❄️','Inverno'],['☀️','Verão'],['🌸','Primavera'],['🍂','Outono']),
    q(342,'estacoes','Em qual estação os dias são mais longos e quentes?',
      ['☀️','Verão'],['❄️','Inverno'],['🍂','Outono'],['🌸','Primavera']),
    q(343,'estacoes','Em qual estação as borboletas e flores aparecem mais?',
      ['🌸','Primavera'],['☀️','Verão'],['🍂','Outono'],['❄️','Inverno']),
    q(344,'estacoes','Qual estação vem depois do inverno?',
      ['🌸','Primavera'],['☀️','Verão'],['❄️','Inverno'],['🍂','Outono']),
    q(345,'estacoes','Em qual estação o Natal é celebrado no Brasil?',
      ['☀️','Verão'],['❄️','Inverno'],['🍂','Outono'],['🌸','Primavera']),
    q(346,'estacoes','Em qual estação as crianças adoram ir à praia?',
      ['☀️','Verão'],['❄️','Inverno'],['🌸','Primavera'],['🍂','Outono']),
    q(347,'estacoes','Em qual estação os ursos hibernam e dormem muito?',
      ['❄️','Inverno'],['☀️','Verão'],['🌸','Primavera'],['🍂','Outono']),
    q(348,'estacoes','Em qual estação as flores aparecem?',
      ['🌸','Primavera'],['❄️','Inverno'],['🍂','Outono'],['☀️','Verão']),
    q(349,'estacoes','Em qual estação as mulheres usam biquíni?',
      ['☀️','Verão'],['❄️','Inverno'],['🌸','Primavera'],['🍂','Outono']),

    // ── 12b. CLIMA (novas) ────────────────────────────────────────────────────
    q(350,'clima','O que acontece quando o vento forte e a chuva se juntam?',
      ['⛈️','Tempestade'],['🌧️','Chuva fraca'],['🌫️','Névoa'],['☀️','Sol forte']),
    q(351,'clima','Como se chamam as bolinhas de gelo que caem do céu?',
      ['🧊','Granizo'],['❄️','Neve'],['💧','Chuva'],['⛅','Nuvem']),
    q(352,'clima','O que o sol faz com a poça de água do chão?',
      ['💨','Evapora'],['🌊','Enche mais'],['❄️','Congela'],['🌧️','Chove mais']),
    q(353,'clima','O que é a névoa espessa que cobre tudo de manhã?',
      ['🌫️','Neblina'],['🌧️','Chuva'],['❄️','Neve'],['☀️','Fumaça']),
    q(354,'clima','O que são os raios brilhantes durante uma tempestade?',
      ['⚡','Eletricidade'],['🌧️','Chuva'],['💨','Vento'],['🌊','Água']),
    q(355,'clima','Qual instrumento mede a temperatura do ar?',
      ['🌡️','Termômetro'],['📏','Régua'],['⚖️','Balança'],['🔭','Telescópio']),
    q(356,'clima','Quando a chuva cai e o sol brilha ao mesmo tempo o que aparece?',
      ['🌈','Arco-íris'],['⭐','Estrela'],['🌙','Lua'],['☁️','Nuvem']),
    q(357,'clima','O que cobre as montanhas muito altas mesmo no verão?',
      ['❄️','Neve'],['☀️','Sol quente'],['🌧️','Chuva'],['🌫️','Névoa']),
    q(358,'clima','O que acontece com as nuvens cinzas quando ficam muito pesadas?',
      ['🌧️','Chove'],['☀️','Clareia'],['💨','Venta muito'],['❄️','Neva']),

    // ── 13b. CORES (novas) ────────────────────────────────────────────────────
    q(359,'cores','Qual cor se forma quando misturamos azul e vermelho?',
      ['🟣','Roxo'],['🟠','Laranja'],['🟡','Amarelo'],['🟤','Marrom']),
    q(360,'cores','Qual é a cor da cenoura?',
      ['🟠','Laranja'],['🔴','Vermelho'],['🟡','Amarelo'],['🟢','Verde']),
    q(361,'cores','Qual é a cor do leite?',
      ['⚪','Branco'],['🟡','Amarelo'],['🩶','Cinza'],['🔵','Azul']),
    q(362,'cores','Qual é a cor do limão-siciliano?',
      ['🟡','Amarelo'],['🟢','Verde'],['🟠','Laranja'],['⚪','Branco']),
    q(363,'cores','Qual é a cor da terra da floresta?',
      ['🟤','Marrom'],['⚫','Preto'],['🔴','Vermelho'],['🟡','Amarelo']),
    q(364,'cores','Qual é a cor da lavanda e da violeta?',
      ['🟣','Roxo'],['🔵','Azul'],['🩷','Rosa'],['🟡','Amarelo']),
    q(365,'cores','Qual é a cor da melancia por dentro?',
      ['🔴','Vermelho'],['🟢','Verde'],['🟡','Amarelo'],['🟠','Laranja']),
    q(366,'cores','Qual cor se forma quando misturamos preto e branco?',
      ['🩶','Cinza'],['🟤','Marrom'],['🔵','Azul'],['🟣','Roxo']),
    q(367,'cores','Qual é a cor do flamingo?',
      ['🩷','Rosa'],['🔴','Vermelho'],['🟠','Laranja'],['⚪','Branco']),

    // ── 14b. FORMAS (novas) ───────────────────────────────────────────────────
    q(368,'formas','Qual forma tem 8 lados iguais como o sinal de PARE?',
      ['🛑','Octógono'],['⬜','Quadrado'],['🔺','Triângulo'],['⭕','Círculo']),
    q(369,'formas','Qual é a forma de um ovo?',
      ['🥚','Oval'],['⭕','Círculo'],['⬜','Quadrado'],['🔺','Triângulo']),
    q(370,'formas','Qual é a forma 3D de uma caixa?',
      ['📦','Paralelepípedo'],['⭕','Esfera'],['🔺','Pirâmide'],['🔷','Losango']),
    q(371,'formas','Qual forma tem 4 lados todos iguais?',
      ['⬜','Quadrado'],['📦','Retângulo', 'img/options/retangulo.webp'],['🔺','Triângulo'],['⭕','Círculo']),
    q(372,'formas','Qual é a forma do pneu de carro?',
      ['⭕','Círculo'],['⬜','Quadrado'],['🔺','Triângulo'],['📦','Retângulo', 'img/options/retangulo.webp']),
    q(373,'formas','Qual é a forma de uma caixa de sapato?',
      ['📦','Retângulo', 'img/options/retangulo.webp'],['⬜','Quadrado'],['🔺','Triângulo'],['⭕','Círculo']),
    q(374,'formas','Qual forma tem uma pipa de papel?',
      ['🔷','Losango'],['⬜','Quadrado'],['🔺','Triângulo'],['⭕','Círculo']),
    q(375,'formas','Qual é a forma de uma pirâmide do Egito?',
      ['🔺','Triângulo'],['⬜','Quadrado'],['⭕','Círculo'],['📦','Retângulo']),
    q(376,'formas','Como se chama uma bola em formato tridimensional?',
      ['🌍','Esfera'],['🎲','Cubo'],['🔺','Pirâmide'],['📦','Paralelepípedo']),

    // ── 15b. NÚMEROS (novas) ──────────────────────────────────────────────────
    q(377,'numeros','Quanto é 1 + 1?',
      ['2️⃣','Dois'],['1️⃣','Um'],['3️⃣','Três'],['4️⃣','Quatro']),
    q(378,'numeros','Quantas asas tem uma borboleta?',
      ['4️⃣','Quatro'],['2️⃣','Duas'],['6️⃣','Seis'],['8️⃣','Oito']),
    q(379,'numeros','Quantos meses tem um ano?',
      ['🗓️','Doze'],['☀️','Quatro'],['📅','Seis'],['🌙','Três']),
    q(380,'numeros','Quanto é 5 menos 2?',
      ['3️⃣','Três'],['2️⃣','Dois'],['4️⃣','Quatro'],['5️⃣','Cinco']),
    q(381,'numeros','Quantos lados tem um quadrado?',
      ['4️⃣','Quatro'],['3️⃣','Três'],['5️⃣','Cinco'],['6️⃣','Seis']),
    q(382,'numeros','Quanto é 3 + 3?',
      ['6️⃣','Seis'],['4️⃣','Quatro'],['5️⃣','Cinco'],['7️⃣','Sete']),
    q(383,'numeros','Quantos ovos tem meia dúzia?',
      ['6️⃣','Seis'],['4️⃣','Quatro'],['8️⃣','Oito'],['3️⃣','Três']),
    q(384,'numeros','Quantos dedos temos no total em mãos e pés?',
      ['🖐️','Vinte'],['✋','Dez'],['👐','Quinze'],['🤜','Cinco']),
    q(385,'numeros','Quantas patas tem uma vaca?',
      ['4️⃣','Quatro'],['2️⃣','Duas'],['6️⃣','Seis'],['8️⃣','Oito']),

    // ── 16b. FAMÍLIA (novas) ──────────────────────────────────────────────────
    q(386,'familia','Quem é a irmã da sua mãe?',
      ['👩','Tia'],['👴','Avô'],['👧','Prima'],['🤵','Padrinho']),
    q(387,'familia','Quem é o filho do seu tio?',
      ['🧒','Primo'],['👶','Irmão bebê'],['👩','Tia'],['👴','Avô']),
    q(388,'familia','Como chamamos o pai e a mãe juntos?',
      ['👨‍👩‍👧','Pais'],['👫','Casal'],['👴👵','Avós'],['🤵👰','Noivos']),
    q(389,'familia','Quem pode cuidar das crianças quando os pais trabalham?',
      ['👩‍🍼','Babá'],['👩‍⚕️','Médica'],['👩‍🏫','Professora'],['👮','Policial']),
    q(390,'familia','Quem é o marido da sua tia?',
      ['🤵','Tio'],['👴','Avô'],['👨','Pai'],['🧒','Primo']),
    q(391,'familia','Como chamamos o filho da sua irmã ou irmão?',
      ['🧒','Sobrinho'],['👶','Primo bebê'],['🧔','Cunhado'],['👦','Afilhado']),
    q(392,'familia','Quem é a mãe da sua mãe ou do seu pai?',
      ['👵','Vovó'],['👩','Tia'],['👧','Prima'],['👩‍🍼','Babá']),
    q(393,'familia','O que fazemos juntos quando é aniversário de alguém da família?',
      ['🎉','Celebramos'],['😢','Choramos'],['😴','Dormimos'],['🏃','Fugimos']),
    q(394,'familia','Como se chama o irmão que tem a maior idade?',
      ['👦','Irmão mais velho'],['👴','Avô'],['🤵','Tio'],['👮','Policial']),

    // ── 17b. EMOÇÕES (novas) ──────────────────────────────────────────────────
    q(395,'emocoes','Como você fica quando seu melhor amigo vem brincar?',
      ['😄','Alegre'],['😢','Triste'],['😱','Assustado'],['😴','Com sono']),
    q(396,'emocoes','Como você fica quando cai e machuca o joelho?',
      ['😢','Com dor'],['😄','Feliz'],['😤','Bravo'],['😴','Com sono']),
    q(397,'emocoes','Como você fica quando ouve um barulho alto de surpresa?',
      ['😱','Assustado'],['😊','Calmo'],['🤔','Pensativo'],['😋','Satisfeito']),
    q(398,'emocoes','Como você fica quando ganha elogios da professora?',
      ['😊','Orgulhoso'],['😢','Triste'],['😱','Assustado'],['😤','Bravo']),
    q(399,'emocoes','Como você fica quando vê um cachorrinho muito fofo?',
      ['🥰','Encantado'],['😱','Assustado'],['😢','Triste'],['😤','Bravo']),
    q(400,'emocoes','Como você fica quando fica em casa sem poder brincar lá fora?',
      ['😑','Entediado'],['😊','Feliz'],['🥰','Apaixonado'],['😄','Animado']),
    q(401,'emocoes','Como você fica quando alguém diz que tem um segredo?',
      ['🤔','Curioso'],['😢','Triste'],['😤','Bravo'],['😴','Com sono']),
    q(402,'emocoes','Como você fica quando termina de comer um prato delicioso?',
      ['😋','Satisfeito'],['😢','Triste'],['😱','Assustado'],['😤','Bravo']),
    q(403,'emocoes','Como você fica quando não consegue fazer algo sozinho?',
      ['😤','Frustrado'],['😊','Feliz'],['🥰','Encantado'],['😄','Animado']),

    // ── 18b. CORPO (novas) ────────────────────────────────────────────────────
    q(404,'corpo','Qual parte do corpo serve para morder a maçã?',
      ['😁','Dentes'],['👅','Língua'],['👃','Nariz'],['👂','Orelha']),
    q(405,'corpo','Qual parte do corpo cresce unhas?',
      ['🖐️','Dedos'],['🦵','Pernas'],['👂','Orelhas'],['👀','Olhos']),
    q(406,'corpo','Qual orgão do corpo bate mais rápido quando corremos?',
      ['❤️','Coração'],['🧠','Cérebro'],['🫁','Pulmão'],['🦴','Osso']),
    q(407,'corpo','Qual parte do corpo forma o sorriso?',
      ['😊','Boca'],['👀','Olhos'],['👂','Orelhas'],['👃','Nariz']),
    q(408,'corpo','Qual parte do corpo fica vermelha quando sentimos vergonha?',
      ['😊','Rosto'],['🖐️','Mãos'],['🦵','Pernas'],['👃','Nariz']),
    q(409,'corpo','Qual parte do corpo usamos para empurrar coisas pesadas?',
      ['💪','Braços'],['🦵','Pernas'],['👀','Olhos'],['👂','Orelhas']),
    q(410,'corpo','Qual parte do corpo filtra o sangue e produz o xixi?',
      ['🫘','Rins'],['🫀','Coração'],['🫁','Pulmão'],['🧠','Cérebro']),
    q(411,'corpo','Com qual parte do corpo ouvimos?',
      ['👂','Ouvido'],['🖐️','Mãos'],['👀','Olhos'],['🦵','Pernas']),
    q(412,'corpo','Qual parte do corpo nos ajuda a pensar e aprender?',
      ['🧠','Cérebro'],['❤️','Coração'],['🫁','Pulmão'],['🦴','Osso']),

    // ── 19b. ESCOLA (novas) ───────────────────────────────────────────────────
    q(413,'escola','O que usamos para colar papel e cartolina?',
      ['✒️','Cola'],['✂️','Tesoura'],['📏','Régua'],['✏️','Lápis']),
    q(414,'escola','Onde ficam os livros para todos os alunos lerem?',
      ['📚','Biblioteca'],['🏫','Diretoria'],['🏠','Casa'],['🏪','Loja']),
    q(415,'escola','Qual instrumento faz barulho para chamar os alunos?',
      ['🔔','Sino'],['📯','Corneta'],['🥁','Tambor'],['🎺','Trompete']),
    q(416,'escola','O que você cola na parede da escola para avisar algum coisa?',
      ['📋','Cartaz'],['📺','Televisão'],['💻','Computador'],['📱','Celular']),
    q(417,'escola','O que usamos para pintar com os dedos na aula de arte?',
      ['🖌️','Tinta guache'],['✏️','Lápis'],['📏','Régua'],['✂️','Tesoura']),
    q(418,'escola','O que guardamos nosso lanche para levar à escola?',
      ['🎒','Lancheira'],['📚','Mochila de livros'],['🛍️','Sacola'],['📦','Caixa']),
    q(419,'escola','O que a professora passa para as crianças fazerem em casa?',
      ['📝','Tarefa'],['🎮','Jogo'],['🎨','Pintura livre'],['📺','Filme']),
    q(420,'escola','O que usamos para medir o comprimento das coisas?',
      ['📏','Régua'],['✏️','Lápis'],['🖌️','Pincel'],['✂️','Tesoura']),
    q(421,'escola','Onde as crianças brincam e correm no recreio?',
      ['🌳','Pátio'],['📚','Sala de aula'],['🛁','Banheiro'],['🍽️','Refeitório']),

    // ── 20b. TRANSPORTES (novas) ──────────────────────────────────────────────
    q(422,'transportes','O que tem hélice e voa perto do chão?',
      ['🚁','Helicóptero'],['✈️','Avião'],['🛩️','Planador'],['🚀','Foguete']),
    q(423,'transportes','O que viaja debaixo da água?',
      ['🌊','Submarino', 'img/options/submarino.webp'],['🚢','Navio'],['⛵','Veleiro'],['🚤','Lancha']),
    q(424,'transportes','O que os bombeiros usam para chegar rápido ao incêndio?',
      ['🚒','Caminhão de bombeiro'],['🚑','Ambulância'],['🚓','Viatura policial'],['🚐','Van']),
    q(425,'transportes','O que tem trilhos e passa por baixo das cidades?',
      ['🚇','Metrô'],['🚂','Trem'],['🚌','Ônibus'],['🚗','Carro']),
    q(426,'transportes','O que as pessoas usam para cruzar rios com remos?',
      ['🚣','Canoa'],['⛵','Veleiro'],['🚢','Navio'],['🛥️','Lancha']),
    q(427,'transportes','O que viaja no espaço saindo da Terra com muito fogo?',
      ['🚀','Foguete'],['✈️','Avião'],['🚁','Helicóptero'],['🛸','Disco voador']),
    q(428,'transportes','O que trabalha nos campos e plantações?',
      ['🚜','Trator'],['🚛','Caminhão'],['🚗','Carro'],['🚌','Ônibus']),
    q(429,'transportes','O que as crianças andam no parque com pedais e 3 rodas?',
      ['🚲','Triciclo'],['🛴','Patinete'],['🛹','Skate'],['🏎️','Carrinho de corrida']),
    q(430,'transportes','O que tem muitas rodas e leva carga nas estradas?',
      ['🚛','Caminhão'],['🚌','Ônibus'],['🚗','Carro'],['🚐','Van']),

    // ── 21b. PROFISSÕES (novas) ───────────────────────────────────────────────
    q(431,'profissoes','Quem faz pão quentinho e delicioso de manhã cedo?',
      ['🧑‍🍳','Padeiro'],['👨‍⚕️','Médico'],['👮','Policial'],['👷','Pedreiro']),
    q(432,'profissoes','Quem cuida das plantações e colhe os alimentos no campo?',
      ['🧑‍🌾','Agricultor'],['🧑‍🍳','Cozinheiro'],['👷','Pedreiro'],['👩‍⚕️','Médica']),
    q(433,'profissoes','Quem pinta paredes e casas com rolos coloridos?',
      ['👩‍🎨','Pintor'],['👷','Pedreiro'],['👨‍🔧','Mecânico'],['🧑‍🍳','Cozinheiro']),
    q(434,'profissoes','Quem conserta carros e motores com ferramentas?',
      ['👨‍🔧','Mecânico'],['👷','Pedreiro'],['👩‍🎨','Pintor'],['🧑‍🌾','Agricultor']),
    q(435,'profissoes','Quem arruma o jardim e cuida das plantas e flores?',
      ['🧑‍🌾🌺','Jardineiro'],['🧑‍🌾','Agricultor'],['👨‍🔧 ','Mecânico'],['👩‍🎨','Pintor']),
    q(436,'profissoes','Quem faz roupas usando agulha e linha?',
      ['🧵','Costureira'],['👩‍🎨','Pintora'],['👨‍🔧🌺','Jardineira'],['👨‍🔧','Mecânica']),
    q(437,'profissoes','Quem tira fotos em casamentos e festas?',
      ['📸','Fotógrafo'],['🎥','Cinegrafista'],['🎬','Diretor'],['🎭','Ator']),
    q(438,'profissoes','Quem trabalha jogando bolas ao cesto?',
      ['⛹️‍♀️','Jogador de basquetebol'],['🐾','Veterinário'],['🧑‍🌾','Agricultor'],['👨‍⚕️','Médico']),
    q(439,'profissoes','Quem dirige o ônibus escolar levando as crianças?',
      ['🚌','Motorista'],['👮','Policial'],['👷','Pedreiro'],['🧑‍🍳','Cozinheiro']),

    // ── 22b. ALIMENTOS (novas) ────────────────────────────────────────────────
    q(440,'alimentos','Qual alimento cremoso é feito com leite e tem sabor de frutas?',
      ['🥛','Iogurte'],['🧀','Queijo'],['🧈','Manteiga'],['🍦','Sorvete']),
    q(441,'alimentos','Qual alimento é redondo com buraco no meio e é doce?',
      ['🍩','Rosquinha'],['🍪','Biscoito'],['🎂','Bolo'],['🍰','Torta']),
    q(442,'alimentos','Qual alimento salgado acompanha o feijão no Brasil?',
      ['🍚','Arroz'],['🍝','Macarrão'],['🍞','Pão'],['🌮','Tacos']),
    q(443,'alimentos','Qual alimento são flocos de milho com leite no café da manhã?',
      ['🥣','Cereal'],['🍳','Ovo'],['🥞','Panqueca'],['🍪','Biscoito']),
    q(444,'alimentos','Qual alimento é feito batendo ovos na frigideira?',
      ['🍳','Omelete'],['🥞','Panqueca'],['🥣','Cereal'],['🍪','Biscoito']),
    q(445,'alimentos','Qual alimento quente é feito com macarrão e muito caldo?',
      ['🍜','Sopa'],['🍝','Macarrão seco'],['🍲','Ensopado'],['🫕','Caldeirão']),
    q(446,'alimentos','Qual alimento cremoso é feito com abacate?',
      ['🥑','Guacamole'],['🧀','Queijo'],['🥛','Iogurte'],['🍦','Sorvete']),
    q(447,'alimentos','Qual alimento é feito de cacau e derrete na boca?',
      ['🍫','Chocolate'],['🍬','Bala'],['🍰','Torta'],['🧁','Cupcake']),
    q(448,'alimentos','Qual alimento são grãos que combinam com arroz?',
      ['🫘','Feijão'],['🍚','Arroz'],['🥣','Cereal'],['🌮','Tacos']),

    // ── 23b. ROUPAS (novas) ───────────────────────────────────────────────────
    q(449,'roupas','O que colocamos sobre a cabeça para o sol não bater?',
      ['👒','Chapéu'],['🧤','Luva'],['🧣','Cachecol'],['🕶️','Óculos']),
    q(450,'roupas','O que usamos na cintura para segurar a calça?',
      ['👖','Cinto'],['🧦','Meia'],['👟','Tênis'],['👗','Vestido']),
    q(451,'roupas','O que colocamos no pescoço para enfeitar como acessório?',
      ['📿','Colar'],['🧤','Luva'],['🧦','Meia'],['👟','Tênis']),
    q(452,'roupas','O que colocamos nos pulsos como acessório brilhante?',
      ['✨','Pulseira'],['🧤','Luva'],['🧣','Cachecol'],['👒','Chapéu']),
    q(453,'roupas','O que as bailarinas usam na dança com saia rodada?',
      ['🩰','Tutu'],['👗','Vestido'],['🩱','Maiô'],['👙','Biquíni']),
    q(454,'roupas','O que usamos para ir à praia e tomar banho de mar?',
      ['👙','Maiô ou biquíni'],['👗','Vestido'],['🧥','Casaco'],['👟','Tênis']),
    q(455,'roupas','O que usamos para dormir confortavelmente à noite?',
      ['🛌','Pijama'],['👗','Vestido'],['🧥','Casaco'],['👖','Calça jeans']),
    q(456,'roupas','O que colocamos nos pés dentro do sapato?',
      ['🧦','Meia'],['👟','Tênis'],['🩴','Chinelo'],['👠','Salto alto']),
    q(457,'roupas','O que protege a cabeça do sol no parquinho?',
      ['🧢','Boné'],['👒','Chapéu de palha'],['🎩','Cartola'],['🧣','Cachecol']),

    // ── 24b. OBJETOS DA CASA (novas) ──────────────────────────────────────────
    q(458,'objetos_casa','O que toca quando alguém chega na porta da casa?',
      ['🔔','Campainha'],['🚪','Porta'],['🔑','Chave'],['📱','Celular']),
    q(459,'objetos_casa','O que usamos para alcançar coisas em lugares altos?',
      ['🪜','Escada'],['🛗','Elevador'],['🧗','Corda'],['🛴','Patinete']),
    q(460,'objetos_casa','O que abrimos para sair a água para lavar as mãos?',
      ['🚰','Torneira'],['🪣','Balde'],['🧽','Esponja'],['🧹','Vassoura']),
    q(461,'objetos_casa','O que é que mostra que horas são?',
      ['⏰','Relógio'],['📺','Televisão'],['📱','Celular'],['💡','Lâmpada']),
    q(462,'objetos_casa','O que usamos para fazer espuma ao lavar as mãos?',
      ['🧼','Sabonete'],['🪥','Escova de dentes'],['🧽','Esponja'],['🪣','Balde']),
    q(463,'objetos_casa','O que usamos para esfregar a sujeira?',
      ['🧽','Esponja'],['🧹','Pano de limpeza'],['🪣','Balde'],['🪥','Escova']),
    q(464,'objetos_casa','O que usamos para secar as louças depois de lavar?',
      ['🍽️','Pano de prato'],['🧹','Vassoura'],['🪣','Balde'],['🧽','Esponja']),
    q(465,'objetos_casa','O que aquece o quarto no inverno?',
      ['🌡️','Aquecedor'],['❄️','Ar condicionado'],['💡','Lâmpada'],['📺','Televisão']),
    q(466,'objetos_casa','O que usamos para falar com alguém que está longe?',
      ['📱','Telefone'],['📺','Televisão'],['💡','Lâmpada'],['🔔','Campainha']),

    // ── 25b. BRINQUEDOS (novas) ───────────────────────────────────────────────
    q(467,'brinquedos','Qual brinquedo de parquinho tem cordas e balança?',
      ['🎠','Balanço','img/options/balanco.webp'],['🎡','Gangorra'],['🎢','Escorregador', 'img/options/escorregador.webp'],['🪀','Ioiô']),
    q(468,'brinquedos','Qual brinquedo faz música quando apertamos os botões?',
      ['🎹','Teclado musical'],['🥁','Tambor'],['🎺','Trompete'],['🎸','Guitarra']),
    q(469,'brinquedos','Qual brinquedo permite criar formas?',
      ['🎨','Massinha'],['🖌️','Pincel'],['✏️','Lápis'],['📝','Caderno']),
    q(470,'brinquedos','Qual brinquedo joga com cartas de figuras?',
      ['🃏','Baralho'],['🎲','Dado'],['🧩','Quebra-cabeça'],['🎮','Videogame']),
    q(471,'brinquedos','Qual brinquedo tem areia que escorre enquanto o tempo passa?',
      ['⏳','Ampulheta'],['⏰','Relógio'],['🕰️','Relógio de parede'],['📅','Calendário']),
    q(472,'brinquedos','Qual brinquedo você pode usar um controle?',
      ['🎮','Videogame'],['🩺','Kit médico'],['🎒','Mochila'],['🧸','Ursinho']),
    q(473,'brinquedos','Qual brinquedo tem tijolos coloridos para construir casas?',
      ['🧱','Blocos de montar'],['🎲','Dado'],['🧩','Quebra-cabeça'],['🎮','Videogame']),
    q(474,'brinquedos','Qual brinquedo de parquinho a criança desce escorregando?',
      ['🎢','Escorregador','img/options/escorregador.webp'],['🎡','Roda gigante'],['🎠','Carrossel'],['🎪','Circo']),
    q(475,'brinquedos','Qual brinquedo tem espelho e faz luzes coloridas ao girar?',
      ['🌈','Caleidoscópio'],['🔭','Telescópio'],['🔬','Microscópio'],['💡','Lanterna']),

    // ── 26. ESPAÇO E UNIVERSO (nova categoria) ────────────────────────────────
    q(476,'espaco','Qual planeta é o nosso lar?',
      ['🌍','Terra'],['🌙','Lua'],['🪐','Saturno'],['🔴','Marte']),
    q(477,'espaco','O que ilumina o nosso dia aqui na Terra?',
      ['☀️','Sol'],['🌙','Lua'],['⭐','Estrela'],['🌍','Terra']),
    q(478,'espaco','O que aparece no céu à noite e é grande e brilhante?',
      ['🌙','Lua'],['☀️','Sol'],['⭐','Estrela'],['🌍','Terra']),
    q(479,'espaco','Como se chama a pessoa que vai ao espaço?',
      ['👨‍🚀','Astronauta'],['✈️','Piloto'],['⛵','Marinheiro'],['🚒','Bombeiro']),
    q(480,'espaco','Em que veículo o astronauta vai para o espaço?',
      ['🚀','Foguete'],['✈️','Avião'],['🚁','Helicóptero'],['🛸','Disco voador']),
    q(481,'espaco','Como se chamam os pontinhos brilhantes no céu à noite?',
      ['⭐','Estrelas'],['🌙','Luas'],['🌍','Planetas'],['☀️','Sóis']),
    q(482,'espaco','Qual planeta tem anéis bonitos ao redor?',
      ['🪐','Saturno'],['🌍','Terra'],['🌙','Lua'],['☀️','Sol']),
    q(483,'espaco','Como se chama o espaço enorme onde ficam os planetas?',
      ['🌌','Universo'],['🌍','Terra'],['🌊','Oceano'],['🏔️','Montanha']),
    q(484,'espaco','Qual planeta é vermelho como sangue?',
      ['🔴','Marte', 'img/options/marte.webp'],['🌍','Terra'],['🌙','Lua'],['🪐','Saturno']),
    q(485,'espaco','Qual é o maior planeta do sistema solar?',
      ['🪐','Júpiter'],['🌍','Terra'],['🔴','Marte', 'img/options/marte.webp'],['🟤','Netuno']),
    q(486,'espaco','O que o astronauta usa para respirar no espaço?',
      ['🧑🏻‍🚀','Traje espacial'],['😷','Máscara comum'],['🎽','Camiseta'],['🧥','Casaco']),
    q(487,'espaco','O que um telescópio faz?',
      ['🔭','Ver estrelas longe'],['🔬','Ver coisas pequenas'],['📱','Tirar foto'],['📺','Assistir TV']),
    q(488,'espaco','Qual é o nosso único satélite natural?',
      ['🌙','Lua'],['⭐','Estrela'],['🌍','Terra'],['🪐','Saturno']),
    q(489,'espaco','Como se chama uma luz que risca o céu à noite?',
      ['⭐','Meteoro'],['🌙','Lua'],['☀️','Sol'],['🌌','Galáxia']),
    q(490,'espaco','O que o Sol nos dá além de luz?',
      ['🌡️','Calor'],['💧','Água'],['🌱','Sementes'],['🍎','Comida']),
    q(491,'espaco','Quantos planetas tem o Sistema Solar?',
      ['8️⃣','Oito'],['4️⃣','Quatro'],['6️⃣','Seis'],['🔟','Dez']),
    q(492,'espaco','Qual é o planeta mais frio do Sistema Solar?',
      ['🔵','Netuno'],['🌍','Terra'],['🔴','Marte', 'img/options/marte.webp'],['🔴','Mercúrio']),
    q(493,'espaco','O que acontece com as coisas no espaço sem gravidade?',
      ['🌌','Flutuam'],['⬇️','Caem no chão'],['⬆️','Sobem rápido'],['💥','Explodem']),
    q(494,'espaco','Como se chama uma rocha gigante que viaja pelo espaço?',
      ['☄️','Asteroide'],['🌍','Planeta'],['⭐','Estrela'],['🌙','Satélite']),
    q(495,'espaco','O que é uma galáxia?',
      ['🌌','Bilhões de estrelas juntas'],['🌙','Uma lua grande'],['🪐','Um planeta'],['☀️','Um sol']),
    q(496,'espaco','Qual cor parece ser a nossa estrela, o Sol?',
      ['☀️','Amarelo'],['🔴','Vermelho'],['🔵','Azul'],['🟢','Verde']),
    q(497,'espaco','Que animal foi o primeiro a ir ao espaço?',
      ['🐕','Cachorra Laika'],['🐒','Macaco'],['🐠','Peixe'],['🐦','Pássaro']),
    q(498,'espaco','Qual planeta fica mais perto do Sol?',
      ['🔴','Mercúrio'],['🌍','Terra'],['🔴','Marte', 'img/options/marte.webp'],['🪐','Saturno']),
    q(499,'espaco','O que as agências espaciais lançam para explorar outros planetas?',
      ['🚀','Sondas e foguetes'],['✈️','Aviões'],['🚁','Helicópteros'],['🛥️','Barcos']),
    q(500,'espaco','Como se chama a linha imaginária no meio da Terra?',
      ['🌍','Equador'],['🌊','Oceano'],['🏔️','Montanha'],['❄️','Polo Norte']),

  ];
})();
