/* English translations of QUESTIONS (js/questions.js), keyed by id.
   Structurally independent from questions.js — safe to edit without
   touching the Portuguese data or its emoji/image fields.
   Shape: { q: 'question text', o: ['correct','wrong1','wrong2','wrong3'] }
   o[] mirrors the AUTHORED (pre-shuffle) option order in questions.js.
   Any missing id, or missing/short o[], falls back to the Portuguese text —
   partial coverage is expected and safe (see localizeQuestion() in i18n.js). */
const QUESTIONS_EN = {

  // 1. PETS
  1: { q: 'Which animal barks?', o: ['Dog','Cat','Cow','Frog'] },
  2: { q: 'Which animal meows?', o: ['Cat','Dog','Fish','Rabbit'] },
  3: { q: 'Which animal purrs when it’s happy?', o: ['Cat','Dog','Fish','Parrot'] },
  4: { q: 'Which animal has long ears and loves carrots?', o: ['Rabbit','Cat','Dog','Turtle'] },
  5: { q: 'Which animal guards the house and barks?', o: ['Dog','Cat','Rabbit','Turtle'] },
  6: { q: 'Which animal has colorful feathers and lives in a cage?', o: ['Parrot','Dog','Fish','Cat'] },
  7: { q: 'Which animal has a shell and moves very slowly?', o: ['Turtle','Rabbit','Dog','Parrot'] },
  8: { q: 'Which animal is called "man’s best friend"?', o: ['Dog','Cat','Rabbit','Fish'] },
  9: { q: 'Which animal has whiskers and hunts mice?', o: ['Cat','Dog','Parrot','Turtle'] },
  10: { q: 'Which animal swims in a fish tank?', o: ['Fish','Cat','Dog','Rabbit'] },

  // 2. WILD ANIMALS
  11: { q: 'Which animal is the king of the jungle?', o: ['Lion','Elephant','Tiger','Giraffe'] },
  12: { q: 'Which animal has a long trunk?', o: ['Elephant','Lion','Giraffe','Alligator'] },
  13: { q: 'Which animal has a very long neck?', o: ['Giraffe','Elephant','Lion','Bear'] },
  14: { q: 'Which animal has black and orange stripes?', o: ['Tiger','Lion','Leopard','Bear'] },
  15: { q: 'Which animal has stripes and looks like a horse?', o: ['Zebra','Horse','Tiger','Deer'] },
  16: { q: 'Which animal has a pouch on its belly?', o: ['Kangaroo','Koala','Panda','Llama'] },
  17: { q: 'Which animal eats bamboo and is black and white?', o: ['Panda','Lion','Elephant','Kangaroo'] },
  18: { q: 'Which animal has a horn on its nose?', o: ['Rhino','Elephant','Giraffe','Alligator'] },
  19: { q: 'Which animal jumps from tree to tree?', o: ['Monkey','Lion','Elephant','Alligator'] },
  20: { q: 'Which animal has pink feathers and stands on one leg?', o: ['Flamingo','Eagle','Parrot','Duck'] },

  // 3. SEA ANIMALS
  21: { q: 'Which sea animal has 8 tentacles?', o: ['Octopus','Shark','Dolphin','Lobster'] },
  22: { q: 'Which animal has big teeth and is very dangerous?', o: ['Shark','Dolphin','Whale','Seal'] },
  23: { q: 'Which sea animal is smart and jumps out of the water?', o: ['Dolphin','Shark','Octopus','Squid'] },
  24: { q: 'What is the biggest animal that lives in the sea?', o: ['Whale','Shark','Dolphin','Seal'] },
  25: { q: 'Which sea animal has 5 arms?', o: ['Starfish','Octopus','Squid','Crab'] },
  26: { q: 'Which sea animal has pincers and walks sideways?', o: ['Crab','Lobster','Scorpion','Octopus'] },
  27: { q: 'Which sea animal is see-through and stings your skin?', o: ['Jellyfish','Octopus','Squid','Snail'] },
  28: { q: 'Which sea animal has "horse" in its name?', o: ['Seahorse','Shark','Dolphin','Octopus'] },
  29: { q: 'Which sea animal has antennae and is very tasty?', o: ['Lobster','Crab','Octopus','Squid'] },
  30: { q: 'Which animal swims but looks like a bird?', o: ['Penguin','Eagle','Duck','Swan'] },

  // 4. FARM ANIMALS
  31: { q: 'Which farm animal gives us milk?', o: ['Cow','Pig','Chicken','Horse'] },
  32: { q: 'Which animal wakes everyone up singing in the morning?', o: ['Rooster','Chicken','Duck','Cow'] },
  33: { q: 'Which farm animal has warm wool?', o: ['Sheep','Goat','Cow','Pig'] },
  34: { q: 'Which farm animal lays eggs?', o: ['Chicken','Cow','Sheep','Pig'] },
  35: { q: 'Which animal is used for riding?', o: ['Horse','Cow','Pig','Sheep'] },
  36: { q: 'Which farm animal swims very well?', o: ['Duck','Chicken','Rooster','Turkey'] },
  37: { q: 'Which farm animal has a snout and is pink?', o: ['Pig','Cow','Sheep','Horse'] },
  38: { q: 'What is the small insect that makes honey?', o: ['Bee','Butterfly','Caterpillar','Ladybug'] },
  39: { q: 'Which animal has horns and likes to jump on things?', o: ['Goat','Bull','Cow','Sheep'] },
  40: { q: 'Which farm animal has wool and is fluffy?', o: ['Sheep','Cow','Horse','Pig'] },

  // 5. INSECTS AND SMALL ANIMALS
  41: { q: 'Which insect makes delicious honey?', o: ['Bee','Butterfly','Ladybug','Ant'] },
  42: { q: 'Which insect has colorful, pretty wings?', o: ['Butterfly','Bee','Ladybug','Cricket'] },
  43: { q: 'Which insect is red with little black dots?', o: ['Ladybug','Butterfly','Ant','Bee'] },
  44: { q: 'Which small animal builds webs to catch food?', o: ['Spider','Ant','Cricket','Bee'] },
  45: { q: 'Which insect turns into a butterfly after a while?', o: ['Caterpillar','Ant','Cricket','Bee'] },
  46: { q: 'Which insect sings at night?', o: ['Cricket','Bee','Butterfly','Ladybug'] },
  47: { q: 'Which insect lives in a hive and has a queen?', o: ['Bee','Ant','Cricket','Butterfly'] },
  48: { q: 'Which small animal has 8 legs?', o: ['Spider','Ant','Cricket','Bee'] },
  49: { q: 'Which insect jumps very high and has wings?', o: ['Grasshopper','Bee','Caterpillar','Ladybug'] },
  50: { q: 'Which small animal has a shell and leaves a shiny trail?', o: ['Snail','Ant','Spider','Caterpillar'] },

  // 6. BIRDS
  51: { q: 'Which bird can’t fly?', o: ['Penguin','Eagle','Parrot','Sparrow'] },
  52: { q: 'Which bird has a long, colorful tail like a fan?', o: ['Peacock','Parrot','Flamingo','Eagle'] },
  53: { q: 'Which bird pecks the tree with its beak to find food?', o: ['Woodpecker','Parrot','Eagle','Penguin'] },
  54: { q: 'Which bird stands on just one leg?', o: ['Flamingo','Eagle','Penguin','Swan'] },
  55: { q: 'Which bird is a symbol of peace?', o: ['Dove','Eagle','Parrot','Peacock'] },
  56: { q: 'Which bird has big eyes and flies at night?', o: ['Owl','Parrot','Penguin','Swan'] },
  57: { q: 'Which bird has a long neck and is elegant?', o: ['Swan','Penguin','Flamingo','Eagle'] },
  58: { q: 'Which bird repeats what we say?', o: ['Parrot','Owl','Swan','Penguin'] },
  59: { q: 'Which bird flies very high and has sharp eyesight?', o: ['Eagle','Parrot','Owl','Penguin'] },
  60: { q: 'Which bird is very common in cities?', o: ['Sparrow','Eagle','Parrot','Flamingo'] },

  // 7. DINOSAURS
  61: { q: 'Which dinosaur had a very, very long neck?', o: ['Brachiosaurus','T-Rex','Crocodile','Lizard'] },
  62: { q: 'Which dinosaur was a meat-eater with tiny little arms?', o: ['Tyrannosaurus Rex','Brachiosaurus','Lizard','Crocodile'] },
  63: { q: 'Which dinosaur had three horns on its head?', o: ['Triceratops','T-Rex','Brachiosaurus','Dragon'] },
  64: { q: 'Which dinosaur had bony plates on its back?', o: ['Stegosaurus','T-Rex','Brachiosaurus','Crocodile'] },
  65: { q: 'Which dinosaur flew in the prehistoric sky?', o: ['Pterosaur','Brachiosaurus','T-Rex','Butterfly'] },
  66: { q: 'What is the age of the dinosaurs called?', o: ['Jurassic','Ice','Sea','Fire'] },
  67: { q: 'Which dinosaur lived in the water and had a long neck?', o: ['Plesiosaurus','Brachiosaurus','T-Rex','Crocodile'] },
  68: { q: 'Which dinosaur was small, fast, and smart?', o: ['Velociraptor','T-Rex','Brachiosaurus','Crocodile'] },
  69: { q: 'Which dinosaur had a hammer-like tail?', o: ['Ankylosaurus','T-Rex','Brachiosaurus','Stegosaurus'] },
  70: { q: 'What do scientists study to learn about dinosaurs?', o: ['Fossils','Books','Telescope','Chemistry'] },

  // 8. FRUITS
  71: { q: 'Which fruit is red and has its seeds on the outside?', o: ['Strawberry','Apple','Cherry','Watermelon'] },
  72: { q: 'Which fruit has yellow peel and is curved?', o: ['Banana','Lemon','Peach','Tangerine'] },
  73: { q: 'Which fruit has the same name as a phone brand?', o: ['Apple','Tomato','Cherry','Strawberry'] },
  74: { q: 'Which fruit is purple and grows in bunches?', o: ['Grape','Blueberry','Eggplant','Plum'] },
  75: { q: 'Which fruit is orange inside and out?', o: ['Orange','Lemon','Peach','Mango'] },
  76: { q: 'Which fruit is really big, green outside and red inside?', o: ['Watermelon','Melon','Kiwi','Pear'] },
  77: { q: 'Which fruit has spikes on the outside and a crown?', o: ['Pineapple','Lemon','Mango','Melon'] },
  78: { q: 'Which fruit is small, yellow, and very sour?', o: ['Lemon','Banana','Orange','Apple'] },
  79: { q: 'Which fruit is tropical and super sweet?', o: ['Mango','Banana','Lemon','Orange'] },
  80: { q: 'Which fruit is small, red, and has a big pit?', o: ['Cherry','Strawberry','Apple','Blueberry'] },

  // 9. VEGETABLES
  81: { q: 'Which vegetable is orange and grows underground?', o: ['Carrot','Orange','Potato','Corn'] },
  82: { q: 'Which vegetable is green and looks like a little tree?', o: ['Broccoli','Mint','Lettuce','Sprout'] },
  83: { q: 'Which vegetable is red and we eat it in salad?', o: ['Tomato','Apple','Bell pepper','Onion'] },
  84: { q: 'Which vegetable is black or purple, used in parmesan-style dishes?', o: ['Eggplant','Plum','Blueberry','Onion'] },
  85: { q: 'Which vegetable makes us cry when we cut it?', o: ['Onion','Garlic','Potato','Corn'] },
  86: { q: 'Which vegetable is green and long like a little boat?', o: ['Cucumber','Lettuce','Herb','Broccoli'] },
  87: { q: 'Which vegetable is little green balls inside a pod?', o: ['Pea','Green grape','Lettuce','Broccoli'] },
  88: { q: 'Which vegetable has green leaves and goes in salad?', o: ['Lettuce','Parsley','Broccoli','Sprout'] },
  89: { q: 'Which vegetable is yellow and has silky "hair"?', o: ['Corn','Banana','Lemon','Onion'] },
  90: { q: 'Which vegetable can we pick in green, yellow, or red?', o: ['Bell pepper','Tomato','Strawberry','Apple'] },

  // 10. NATURE AND PLANTS
  91: { q: 'Which part of the plant is underground?', o: ['Root','Leaf','Flower','Trunk'] },
  92: { q: 'What happens to flowers when it rains?', o: ['They drink water','They dry up','They freeze','They fly away'] },
  93: { q: 'Which colorful part of flowers attracts butterflies?', o: ['Petals','Leaves','Roots','Stem'] },
  94: { q: 'Which plant has spikes and doesn’t need much water?', o: ['Cactus','Pine tree','Palm tree','Fern'] },
  95: { q: 'What does the bee take from flowers to make honey?', o: ['Nectar','Water','Honey','Pollen'] },
  96: { q: 'What do we plant to grow a new plant?', o: ['Seed','Leaf','Flower','Fruit'] },
  97: { q: 'What color are most tree leaves?', o: ['Green','Yellow','Orange','Red'] },
  98: { q: 'What do plants need to grow, besides water?', o: ['Sunlight','Moon','Stars','Storm'] },
  99: { q: 'What is the tall, brown part of a tree called?', o: ['Trunk','Root','Branch','Treetop'] },
  100: { q: 'What do trees release that’s good for us to breathe?', o: ['Oxygen','Water','Heat','Cold'] },

  // 11. SEASONS
  101: { q: 'In which season do leaves fall from the trees?', o: ['Fall','Spring','Summer','Winter'] },
  102: { q: 'In which season is it hottest, and we go to the beach?', o: ['Summer','Fall','Spring','Winter'] },
  103: { q: 'In which season do flowers bloom and everything turns colorful?', o: ['Spring','Summer','Fall','Winter'] },
  104: { q: 'In which season is it coldest, and it might snow?', o: ['Winter','Fall','Spring','Summer'] },
  105: { q: 'Which season comes right after summer?', o: ['Fall','Winter','Spring','Summer'] },
  106: { q: 'In which season do trees lose all their leaves?', o: ['Winter','Fall','Spring','Summer'] },
  107: { q: 'How many seasons are there in a year?', o: ['Four','Three','Two','Six'] },
  108: { q: 'In which season are the days longer and the nights shorter?', o: ['Summer','Winter','Fall','Spring'] },
  109: { q: 'Which season comes after winter?', o: ['Spring','Summer','Fall','Winter'] },
  110: { q: 'In which season does Carnival happen in Brazil?', o: ['Summer','Fall','Spring','Winter'] },

  // 12. WEATHER
  111: { q: 'What falls from the sky when it’s raining?', o: ['Rain','Snow','Wind','Lightning'] },
  112: { q: 'What is the colorful arc in the sky after the rain called?', o: ['Rainbow','Sun','Moon','Star'] },
  113: { q: 'What covers the ground when it’s very cold outside?', o: ['Snow','Rain','Fog','Wind'] },
  114: { q: 'What do we call the air that blows and shakes the trees?', o: ['Wind','Rain','Snow','Lightning'] },
  115: { q: 'What appears in the night sky, pretty and shiny?', o: ['Moon','Star','Sun','Rainbow'] },
  116: { q: 'What happens when there’s lots of lightning and thunder?', o: ['Storm','Snow','Rainbow','Strong sun'] },
  117: { q: 'What do we call the cloud that comes down close to the ground?', o: ['Fog','Rain','Snow','Wind'] },
  118: { q: 'What happens to water when it’s very cold?', o: ['It freezes','It evaporates','It rains','It turns to wind'] },
  119: { q: 'What are the little ice pebbles that fall from the sky?', o: ['Hail','Snow','Rain','Dew'] },
  120: { q: 'When it’s very hot, what do we do to cool off?', o: ['Swim','Put on a coat','Light a fire','Stay in the snow'] },

  // 13. COLORS
  121: { q: 'What color is the sky on a sunny day?', o: ['Blue','Green','Yellow','Red'] },
  122: { q: 'What color is grass and leaves?', o: ['Green','Yellow','Blue','Brown'] },
  123: { q: 'What color is the sun?', o: ['Yellow','Orange','Red','White'] },
  124: { q: 'What color is blood?', o: ['Red','Orange','Purple','Brown'] },
  125: { q: 'What color do we get when we mix blue and yellow?', o: ['Green','Orange','Purple','Brown'] },
  126: { q: 'What color is nighttime and coal?', o: ['Black','Navy blue','Brown','Purple'] },
  127: { q: 'What color is snow and clouds?', o: ['White','Blue','Yellow','Gray'] },
  128: { q: 'What color is grape juice?', o: ['Purple','Blue','Red','Orange'] },
  129: { q: 'What color do we get when we mix red and yellow?', o: ['Orange','Purple','Green','Brown'] },
  130: { q: 'What color is chocolate and dirt?', o: ['Brown','Black','Orange','Red'] },

  // 14. SHAPES
  131: { q: 'Which shape has only 3 sides?', o: ['Triangle','Square','Rectangle','Diamond'] },
  132: { q: 'Which shape has 4 equal sides?', o: ['Square','Rectangle','Triangle','Diamond'] },
  133: { q: 'Which shape has no sides and is round?', o: ['Circle','Square','Triangle','Rectangle'] },
  134: { q: 'Which shape has 4 sides, with two of them longer?', o: ['Rectangle','Square','Triangle','Diamond'] },
  135: { q: 'What is the shape of an egg called?', o: ['Oval','Star','Pentagon','Square'] },
  136: { q: 'Which shape has 5 points and we use to draw in the sky?', o: ['Star','Triangle','Hexagon','Diamond'] },
  137: { q: 'What do we call a ball shape in 3D?', o: ['Sphere','Circle','Cube','Cone'] },
  138: { q: 'What do we call a box shape in 3D?', o: ['Cube','Sphere','Pyramid','Rock'] },
  139: { q: 'What is the shape of an egg called?', o: ['Oval','Circle','Square','Triangle'] },
  140: { q: 'What shape is a whole pizza?', o: ['Circle','Square','Rectangle','Triangle'] },

  // 15. NUMBERS AND QUANTITIES
  141: { q: 'How many legs does a dog have?', o: ['4 legs','2 legs','6 legs','8 legs'] },
  142: { q: 'How many fingers does a hand have?', o: ['5 fingers','4 fingers','6 fingers','3 fingers'] },
  143: { q: 'How many eyes does a person have?', o: ['2 eyes','1 eye','4 eyes','3 eyes'] },
  144: { q: 'How many wheels does a bicycle have?', o: ['2 wheels','4 wheels','3 wheels','1 wheel'] },
  145: { q: 'How many legs do insects have?', o: ['6 legs','4 legs','8 legs','2 legs'] },
  146: { q: 'How many legs does a spider have?', o: ['8 legs','6 legs','4 legs','2 legs'] },
  147: { q: 'How many sides does a triangle have?', o: ['3 sides','4 sides','5 sides','2 sides'] },
  148: { q: 'What is 2 + 2?', o: ['4','3','5','2'] },
  149: { q: 'What is 3 + 1?', o: ['4','3','5','6'] },
  150: { q: 'How many days are in a week?', o: ['7 days','5 days','6 days','8 days'] },

  // 16. FAMILY
  151: { q: 'Who is the mother of your dad or mom?', o: ['Grandma','Aunt','Cousin','Teacher'] },
  152: { q: 'Who is the brother of your dad or mom?', o: ['Uncle','Grandpa','Cousin','Godfather'] },
  153: { q: 'What do we call our aunt or uncle’s child?', o: ['Cousin','Brother','Sister','Baby'] },
  154: { q: 'Who gives us love and takes care of us when we’re born?', o: ['Mom','Grandma','Aunt','Teacher'] },
  155: { q: 'What do we call our dad’s dad?', o: ['Grandpa','Uncle','Dad','Cousin'] },
  156: { q: 'What do babies like to drink?', o: ['Baby bottle','Juice','Water','Soda'] },
  157: { q: 'Who are the people who live in the same house as you?', o: ['Family','Friends','Classmates','Neighbors'] },
  158: { q: 'What do we call the youngest sibling?', o: ['Little brother','Older brother','Cousin','Twin sister'] },
  159: { q: 'Who is your mom’s dad?', o: ['Grandpa','Uncle','Stepdad','Cousin'] },
  160: { q: 'What do we call it when two siblings are born together at the same time?', o: ['Twins','Cousins','Regular siblings','Babies'] },

  // 17. EMOTIONS
  161: { q: 'How do you feel when you get a present?', o: ['Happy','Sad','Scared','Angry'] },
  162: { q: 'How do you feel when you lose a toy?', o: ['Sad','Happy','Angry','Scared'] },
  163: { q: 'How do you feel when you dream about a monster?', o: ['Scared','Happy','Sad','Excited'] },
  164: { q: 'How do you feel when someone takes your toy without asking?', o: ['Angry','Happy','Sad','Excited'] },
  165: { q: 'How do you feel when you’re going on vacation?', o: ['Excited','Sad','Scared','Sleepy'] },
  166: { q: 'How do you feel when you see something new and want to understand it?', o: ['Curious','Happy','Sad','Sleepy'] },
  167: { q: 'How do you feel when someone gives you a warm hug?', o: ['Loved','Scared','Angry','Sad'] },
  168: { q: 'How do you feel when you eat something really tasty?', o: ['Satisfied','Sad','Scared','Angry'] },
  169: { q: 'How do you feel when you manage to do something hard?', o: ['Proud','Sad','Scared','Sleepy'] },
  170: { q: 'How do you feel when someone tells you a bedtime story?', o: ['Sleepy','Excited','Happy','Satisfied'] },

  // 18. BODY AND SENSES
  171: { q: 'What do we use to see things?', o: ['Eyes','Ears','Nose','Hands'] },
  172: { q: 'What do we use to hear music and conversations?', o: ['Ears','Eyes','Nose','Tongue'] },
  173: { q: 'What do we use to smell flowers and food?', o: ['Nose','Ears','Eyes','Hands'] },
  174: { q: 'What do we use to eat and talk?', o: ['Mouth','Eyes','Ears','Nose'] },
  175: { q: 'What do we use to hug people?', o: ['Arms','Legs','Fingers','Feet'] },
  176: { q: 'What do we use to kick a ball?', o: ['Feet','Arms','Hands','Fists'] },
  177: { q: 'Which body part is up top, where the brain is?', o: ['Head','Arm','Leg','Chest'] },
  178: { q: 'What is inside your chest and never stops beating?', o: ['Heart','Brain','Lung','Bone'] },
  179: { q: 'What do we use to grab and hold things?', o: ['Hands','Legs','Arms','Feet'] },
  180: { q: 'What do we use to run and jump?', o: ['Legs','Arms','Hands','Head'] },

  // 19. SCHOOL
  181: { q: 'What can we write with and erase afterward?', o: ['Pencil','Crayon','Pen','Paintbrush'] },
  182: { q: 'What do we use to erase what a pencil wrote?', o: ['Eraser','Scissors','Ruler','Compass'] },
  183: { q: 'What does the teacher use to write on the classroom wall?', o: ['Whiteboard and marker','Pencil','Paper','Book'] },
  184: { q: 'What do we carry on our back with our school books?', o: ['Backpack','Purse','Suitcase','Box'] },
  185: { q: 'What do we use to safely cut paper?', o: ['Scissors','Knife','Ruler','Pen'] },
  186: { q: 'What do we use to paint with bright colors?', o: ['Crayon','Book','Ruler','Paperclip'] },
  187: { q: 'Who teaches and helps children at school?', o: ['Teacher','Doctor','Police officer','Cook'] },
  188: { q: 'What do we call the place where children study?', o: ['School','Hospital','Store','House'] },
  189: { q: 'What do we use to measure the size of small things?', o: ['Ruler','Pencil','Paperclip','Book'] },
  190: { q: 'What rings to call the students to class?', o: ['Bell','Trumpet','Drum','Horn'] },

  // 20. TRANSPORTATION
  191: { q: 'What has 4 wheels, an engine, and carries the family?', o: ['Car','Bus','Train','Helicopter'] },
  192: { q: 'What flies in the sky and carries lots of passengers?', o: ['Airplane','Rocket','Helicopter','Balloon'] },
  193: { q: 'What has 2 wheels and pedals, with no engine?', o: ['Bicycle','Motorcycle','Car','Scooter'] },
  194: { q: 'What runs on iron tracks?', o: ['Train','Car','Bus','Helicopter'] },
  195: { q: 'What floats and travels on water?', o: ['Boat','Car','Bicycle','Airplane'] },
  196: { q: 'What has an engine and only 2 wheels?', o: ['Motorcycle','Car','Bicycle','Scooter'] },
  197: { q: 'What is really big and carries lots of people around the city?', o: ['Bus','Car','Bicycle','Train'] },
  198: { q: 'What do you use to go up and down inside buildings?', o: ['Elevator','Car','Scooter','Bicycle'] },
  199: { q: 'What does a fisherman use to go fishing in the river or sea?', o: ['Canoe','Airplane','Rocket','Helicopter'] },
  200: { q: 'What carries lots of cargo on the roads?', o: ['Truck','Car','Bus','Train'] },

  // 21. OCCUPATIONS
  201: { q: 'Who takes care of sick people?', o: ['Doctor','Teacher','Police officer','Firefighter'] },
  202: { q: 'Who puts out fires and saves people?', o: ['Firefighter','Police officer','Doctor','Construction worker'] },
  203: { q: 'Who teaches children at school?', o: ['Teacher','Doctor','Police officer','Cook'] },
  204: { q: 'Who protects and keeps order in the city?', o: ['Police officer','Firefighter','Doctor','Construction worker'] },
  205: { q: 'Who flies the airplane?', o: ['Pilot','Doctor','Police officer','Astronaut'] },
  206: { q: 'Who builds houses and buildings?', o: ['Construction worker','Police officer','Firefighter','Cook'] },
  207: { q: 'Who cuts and takes care of hair?', o: ['Hairdresser','Doctor','Cook','Teacher'] },
  208: { q: 'Who cooks at restaurants?', o: ['Chef','Doctor','Teacher','Police officer'] },
  209: { q: 'Who delivers letters and packages to your door?', o: ['Mail carrier','Police officer','Firefighter','Construction worker'] },
  210: { q: 'Who takes care of animals when they get sick?', o: ['Veterinarian','Teacher','Cook','Construction worker'] },

  // 22. FOOD AND DRINKS
  211: { q: 'Which food is made from milk and has holes in it?', o: ['Cheese','Milk','Ice cream','Egg'] },
  212: { q: 'Which drink is white and comes from the cow?', o: ['Milk','Water','Juice','Coffee'] },
  213: { q: 'Which food is made with cocoa and melts in your mouth?', o: ['Chocolate','Cookie','Cake','Candy'] },
  214: { q: 'Which food is long pasta with red sauce?', o: ['Spaghetti','Pizza','Taco','Bread'] },
  215: { q: 'Which food is made at the bakery?', o: ['Bread','Pizza','Pancake','Ice cream'] },
  216: { q: 'Which drink is made by squeezing a fruit?', o: ['Juice','Milk','Water','Tea'] },
  217: { q: 'Which food is round, has cheese, and we cut it into slices?', o: ['Pizza','Hamburger','Pancake','Taco'] },
  218: { q: 'Which food has a shell and is fried or boiled for breakfast?', o: ['Egg','Pancake','Croissant','Cereal'] },
  219: { q: 'Which dessert is cold, colorful, and melts in the heat?', o: ['Ice cream','Cake','Cookie','Chocolate'] },
  220: { q: 'Which food do we use to make pizza’s red sauce?', o: ['Tomato','Strawberry','Cherry','Blueberry'] },

  // 23. CLOTHES AND ACCESSORIES
  221: { q: 'What do we usually put on our feet to go outside?', o: ['Shoes or sneakers','Gloves','Scarf','Hat'] },
  222: { q: 'What do we put on our hands when it’s very cold?', o: ['Gloves','Sneakers','Scarf','Hat'] },
  223: { q: 'What do we put on our head to protect from the cold?', o: ['Beanie or hat','Gloves','Sneakers','Shorts'] },
  224: { q: 'What do we wear to swim in the pool?', o: ['Swimsuit or trunks','Coat','Dress','Scarf'] },
  225: { q: 'What can we put on over everything when it’s cold?', o: ['Coat','Dress','Swimsuit','Shorts'] },
  226: { q: 'What do we put on our feet inside our shoes?', o: ['Socks','Sandals','Sneakers','Heels'] },
  227: { q: 'What do girls wear to parties that is long?', o: ['Dress','Shorts','Coat','Hat'] },
  228: { q: 'What do we wear on our legs that has a zipper or button?', o: ['Pants','Dress','Shorts','Gloves'] },
  229: { q: 'What do we wear in the heat to cover our torso, with sleeves?', o: ['Shirt','Pants','Coat','Dress'] },
  230: { q: 'What do we put on our eyes to protect from the sun?', o: ['Sunglasses','Hat','Gloves','Scarf'] },

  // 24. HOUSEHOLD OBJECTS
  231: { q: 'What do we use to lie down and sleep at night?', o: ['Bed','Sofa','Chair','Bathtub'] },
  232: { q: 'What do we use to sit comfortably in the living room?', o: ['Sofa','Chair','Bed','Toilet'] },
  233: { q: 'What do we put rice and beans in to eat?', o: ['Plate','Bowl','Cup','Container'] },
  234: { q: 'What do we hold to drink water and juice?', o: ['Cup','Plate','Fork','Spoon'] },
  235: { q: 'What do we use to cook beans on the stove?', o: ['Pot','Plate','Cup','Fork'] },
  236: { q: 'What do we use to sweep the kitchen floor?', o: ['Broom','Bucket','Sponge','Brush'] },
  237: { q: 'What keeps food cold so it doesn’t spoil?', o: ['Fridge','Stove','Cabinet','Bucket'] },
  238: { q: 'What can we use to watch movies and cartoons with the family?', o: ['TV','Computer','Radio','Phone'] },
  239: { q: 'What opens and closes the front door?', o: ['Key','Padlock','Door','Screwdriver'] },
  240: { q: 'What usually lights up the room when it’s dark?', o: ['Lamp','Candle','Flashlight','Star'] },

  // 25. TOYS AND FUN
  241: { q: 'What do we use to play soccer?', o: ['Ball','Bat','Racket','Hockey stick'] },
  242: { q: 'Which toy flies with the wind and has a long string?', o: ['Kite','Airplane','Balloon','Butterfly'] },
  243: { q: 'Which toy is made of little bricks to build with?', o: ['Building blocks','Dice','Puzzle','Video game'] },
  244: { q: 'Which toy can wear little outfits?', o: ['Doll','Video game','Ball','Puzzle'] },
  245: { q: 'Which of these toys has 3 little wheels?', o: ['Scooter','Bicycle','Skateboard','Toy car'] },
  246: { q: 'Which playground toy goes up and down?', o: ['See-saw','Swing','Slide','Yo-yo'] },
  247: { q: 'Which of these toys has little wheels?', o: ['Toy car','Ball','Teddy bear','Dice'] },
  248: { q: 'What do you use to paint a drawing?', o: ['Paintbrush and paint','Scissors','Ruler','Book'] },
  249: { q: 'Which toy has lots and lots of pieces to fit together?', o: ['Puzzle','Dice','Ball','Teddy bear'] },
  250: { q: 'Which toy spins fast on the ground?', o: ['Spinning top','Ball','Teddy bear','Dice'] },

  // 1b. PETS (new)
  251: { q: 'Which small animal runs on a little wheel?', o: ['Hamster','Cat','Dog','Rabbit'] },
  252: { q: 'Which pet has colorful feathers and mimics voices?', o: ['Parrot','Fish','Turtle','Dog'] },
  253: { q: 'Which animal looks like a lizard?', o: ['Iguana','Turtle','Snake','Parrot'] },
  254: { q: 'Which animal swims in a fish tank?', o: ['Little fish','Shark','Octopus','Frog'] },
  255: { q: 'Which pet barks and wants to go for a walk every day?', o: ['Dog','Cat','Rabbit','Parrot'] },
  256: { q: 'Which pet meows when it wants attention?', o: ['Cat','Dog','Fish','Turtle'] },
  257: { q: 'Which animal has pink ears and hops a lot?', o: ['Rabbit','Cat','Dog','Hamster'] },
  258: { q: 'Which animal lives in a cage and sings beautifully?', o: ['Canary','Parrot','Penguin','Eagle'] },
  259: { q: 'Which animal has a shell and can live up to 100 years?', o: ['Turtle','Snake','Lizard','Alligator'] },

  // 2b. WILD ANIMALS (new)
  260: { q: 'What is the fastest animal in the world?', o: ['Cheetah','Lion','Tiger','Elephant'] },
  261: { q: 'Which animal has round spots and climbs trees?', o: ['Jaguar','Lion','Bear','Giraffe'] },
  262: { q: 'Which animal lives in a group called a pack?', o: ['Wolf','Lion','Bear','Fox'] },
  263: { q: 'Which North Pole animal is all white and swims well?', o: ['Polar bear','Wolf','Penguin','Fox'] },
  264: { q: 'Which small animal has a striped tail and lives in the forest?', o: ['Raccoon','Squirrel','Hedgehog','Rabbit'] },
  265: { q: 'Which animal has antlers and was Bambi in a Disney movie?', o: ['Deer','Goat','Ram','Rhino'] },
  266: { q: 'Which small orange animal has a bushy tail and lives in the forest?', o: ['Fox','Wolf','Raccoon','Cat'] },
  267: { q: 'Which animal has spikes all over its body and curls into a ball?', o: ['Hedgehog','Caterpillar','Raccoon','Rabbit'] },
  268: { q: 'Which animal is a flying mammal?', o: ['Bat','Owl','Sparrow','Eagle'] },

  // 3b. SEA ANIMALS (new)
  269: { q: 'Which sea animal has a flat body and swims by rippling?', o: ['Stingray','Clownfish','Shark','Octopus'] },
  270: { q: 'Which sea animal has a spiral shell and is soft inside?', o: ['Snail','Crab','Lobster','Oyster'] },
  271: { q: 'Which sea animal is the biggest of all and sings in the ocean?', o: ['Whale','Dolphin','Shark','Squid'] },
  272: { q: 'Which sea animal is the main character in the movie "Nemo"?', o: ['Clownfish','Blue fish','Shark','Pufferfish'] },
  273: { q: 'Which sea animal has a shell and lives stuck to rocks?', o: ['Oyster','Snail','Crab','Lobster'] },
  274: { q: 'Which sea animal has tentacles and changes color?', o: ['Octopus','Squid','Jellyfish','Fish'] },
  275: { q: 'Which animal has feathers and swims in the icy sea but can’t fly?', o: ['Penguin','Swan','Duck','Flamingo'] },
  276: { q: 'Which sea animal has a long snout like a sword?', o: ['Swordfish','Shark','Dolphin','Octopus'] },
  277: { q: 'Which sea animal squirts black ink?', o: ['Octopus','Snail','Jellyfish','Clownfish'] },

  // 4b. FARM ANIMALS (new)
  278: { q: 'Which farm animal has warm wool?', o: ['Sheep','Goat','Cow','Horse'] },
  279: { q: 'Which farm animal has curved horns and climbs on rocks?', o: ['Goat','Sheep','Cow','Turkey'] },
  280: { q: 'Which farm animal has a pink snout and rolls in the mud?', o: ['Pig','Cow','Sheep','Horse'] },
  281: { q: 'Which farm animal pecks the ground and goes COCK-A-DOODLE-DOO?', o: ['Rooster','Chicken','Duck','Turkey'] },
  282: { q: 'Which farm animal carries things?', o: ['Donkey','Horse','Cow','Sheep'] },
  283: { q: 'Which farm animal has beautiful feathers and is big?', o: ['Turkey','Chicken','Duck','Rooster'] },
  284: { q: 'Which farm animal swims very well?', o: ['Duck','Chicken','Turkey','Rooster'] },
  285: { q: 'Which farm animal has hooves and carries riders?', o: ['Horse','Donkey','Cow','Sheep'] },
  286: { q: 'Which small farm animal makes honey in a hive?', o: ['Bee','Butterfly','Ant','Cricket'] },

  // 5b. INSECTS (new)
  287: { q: 'Which insect looks like a helicopter?', o: ['Dragonfly','Butterfly','Bee','Mosquito'] },
  288: { q: 'Which insect is green and looks like a plant twig?', o: ['Stick insect','Caterpillar','Ant','Cricket'] },
  289: { q: 'Which insect has a light in its belly and glows at night?', o: ['Firefly','Bee','Butterfly','Ant'] },
  290: { q: 'Which insect builds underground anthills?', o: ['Ant','Bee','Butterfly','Cricket'] },
  291: { q: 'Which insect has hard, shiny wings?', o: ['Beetle','Butterfly','Bee','Cricket'] },
  292: { q: 'Which insect flies and bites us, leaving an itch?', o: ['Mosquito','Bee','Butterfly','Ant'] },
  293: { q: 'Which insect stays still like it’s praying?', o: ['Praying mantis','Ant','Cricket','Caterpillar'] },
  294: { q: 'Which insect builds dirt termite mounds?', o: ['Termite','Ant','Mosquito','Bee'] },
  295: { q: 'Which insect has yellow and black stripes and can sting?', o: ['Wasp','Butterfly','Ant','Beetle'] },

  // 6b. BIRDS (new)
  296: { q: 'Which tiny bird flaps its wings super fast and drinks nectar?', o: ['Hummingbird','Parrot','Eagle','Penguin'] },
  297: { q: 'Which bird has a huge, colorful beak and lives in the rainforest?', o: ['Toucan','Eagle','Thrush','Swan'] },
  298: { q: 'Which bird lives at the South Pole, can’t fly, but swims very well?', o: ['Penguin','Swan','Duck','Flamingo'] },
  299: { q: 'Which bird is white, has a long neck, and is elegant?', o: ['Swan','Dove','Flamingo','Penguin'] },
  300: { q: 'Which bird pecks tree wood with its beak to eat?', o: ['Woodpecker','Parrot','Eagle','Swan'] },
  301: { q: 'Which bird nests on rooftops and has a long neck?', o: ['Stork','Flamingo','Dove','Eagle'] },
  302: { q: 'Which bird flies very high and has sharp eyesight for hunting?', o: ['Eagle','Dove','Penguin','Parrot'] },
  303: { q: 'Which bird has a little red chest and sings in the garden?', o: ['Robin','Parrot','Swan','Eagle'] },
  304: { q: 'Which Brazilian bird sings beautifully and is a national symbol?', o: ['Thrush','Parrot','Eagle','Penguin'] },

  // 7b. DINOSAURS (new)
  305: { q: 'Which dinosaur had giant spikes on its back like a sail?', o: ['Spinosaurus','T-Rex','Crocodile','Pterodactyl'] },
  306: { q: 'Which dinosaur ran in packs and hunted together?', o: ['Velociraptor','Brachiosaurus','Alligator','Lion'] },
  307: { q: 'Which plant-eating dinosaur had a medium neck and was huge?', o: ['Brontosaurus','Velociraptor','Elephant','Giraffe'] },
  308: { q: 'Which dinosaur had a huge head and very sharp teeth?', o: ['T-Rex','Diplodocus','Crocodile','Lion'] },
  309: { q: 'Which dinosaur swam well and had a huge neck?', o: ['Plesiosaurus','Brontosaurus','Spinosaurus','Velociraptor'] },
  310: { q: 'Which dinosaur had a colorful crest on its head?', o: ['Parasaurolophus','T-Rex','Alligator','Mammoth'] },
  311: { q: 'Dinosaurs were reptiles like which animals today?', o: ['Lizards','Fish','Birds','Elephants'] },
  312: { q: 'What do we call dinosaur bones that we find today?', o: ['Fossils','Crystals','Ordinary rocks','Seeds'] },
  313: { q: 'Which small, clever dinosaur hunted with sharp claws?', o: ['Velociraptor','Brachiosaurus','Crocodile','Lion'] },

  // 8b. FRUITS (new)
  314: { q: 'Which fruit is green outside with black seeds inside?', o: ['Kiwi','Melon','Pear','Green apple'] },
  315: { q: 'Which fruit has thick skin and sweet water inside?', o: ['Coconut','Watermelon','Lemon','Orange'] },
  316: { q: 'Which fruit is small and stains clothes purple?', o: ['Blackberry','Grape','Strawberry','Cherry'] },
  317: { q: 'Which tropical fruit has spiky skin and a crown?', o: ['Pineapple','Banana','Mango','Peach'] },
  318: { q: 'Which small, orange fruit has easy-to-peel skin?', o: ['Tangerine','Lemon','Apricot','Apple'] },
  319: { q: 'Which fruit has green skin, is creamy, and has a huge pit?', o: ['Avocado','Pear','Melon','Kiwi'] },
  320: { q: 'Which tropical fruit is yellow with a strong, sweet smell?', o: ['Mango','Banana','Pineapple','Peach'] },
  321: { q: 'Which fruit is red with its tiny seeds on the outside?', o: ['Strawberry','Cherry','Blueberry','Grape'] },
  322: { q: 'Which fruit has fuzzy skin?', o: ['Kiwi','Soursop','Pear','Coconut'] },

  // 9b. VEGETABLES (new)
  323: { q: 'Which vegetable has crunchy, green leaves for salad?', o: ['Lettuce','Broccoli','Mint','Arugula'] },
  324: { q: 'Which vegetable is yellow and grows on a cob?', o: ['Corn','Carrot','Onion','Potato'] },
  325: { q: 'Which long, purple vegetable is used in parmesan-style dishes?', o: ['Eggplant','Tomato','Carrot','Broccoli'] },
  326: { q: 'Which small, green vegetable is found inside a pod?', o: ['Pea','Broccoli','Lettuce','Corn'] },
  327: { q: 'Which vegetable has a strong smell and we use it for seasoning?', o: ['Garlic','Onion','Carrot','Potato'] },
  328: { q: 'Which vegetable is round, red, and goes in sauce?', o: ['Tomato','Bell pepper','Eggplant','Carrot'] },
  329: { q: 'Which vegetable is shaped like a little tree?', o: ['Broccoli','Lettuce','Carrot','Corn'] },
  330: { q: 'Which orange vegetable do rabbits love to eat?', o: ['Carrot','Tomato','Onion','Potato'] },
  331: { q: 'Which long, green vegetable has seeds inside?', o: ['Cucumber','Eggplant','Corn','Broccoli'] },

  // 10b. NATURE (new)
  332: { q: 'What do we call a large group of trees together?', o: ['Forest','Garden','Desert','Ocean'] },
  333: { q: 'What comes out of a volcano when it erupts?', o: ['Lava','Water','Ice','Wind'] },
  334: { q: 'What do we call the dark, fertile soil that plants love?', o: ['Humus','Rock','Sand','Water'] },
  335: { q: 'What covers the forest floor in the fall?', o: ['Fallen leaves','Flowers','Grass','Snow'] },
  336: { q: 'Which plant floats on water and has a huge flower?', o: ['Water lily','Rose','Hibiscus','Sunflower'] },
  337: { q: 'Which plant do we decorate at Christmas?', o: ['Pine tree','Rose','Hibiscus','Sunflower'] },
  338: { q: 'What do we call the little water drop that appears on leaves in the morning?', o: ['Dew','Rain','Snow','Sea'] },
  339: { q: 'Which delicate plant grows attached to other trees?', o: ['Orchid','Rose','Sunflower','Cherry blossom'] },
  340: { q: 'What do we call the colorful part of a flower that attracts butterflies?', o: ['Petal','Leaf','Stem','Seed'] },

  // 11b. SEASONS (new)
  341: { q: 'In which season do we wear a coat and scarf?', o: ['Winter','Summer','Spring','Fall'] },
  342: { q: 'In which season are the days longer and warmer?', o: ['Summer','Winter','Fall','Spring'] },
  343: { q: 'In which season do butterflies and flowers show up the most?', o: ['Spring','Summer','Fall','Winter'] },
  344: { q: 'Which season comes after winter?', o: ['Spring','Summer','Winter','Fall'] },
  345: { q: 'In which season is Christmas celebrated in Brazil?', o: ['Summer','Winter','Fall','Spring'] },
  346: { q: 'In which season do kids love going to the beach?', o: ['Summer','Winter','Spring','Fall'] },
  347: { q: 'In which season do bears hibernate and sleep a lot?', o: ['Winter','Summer','Spring','Fall'] },
  348: { q: 'In which season do flowers appear?', o: ['Spring','Winter','Fall','Summer'] },
  349: { q: 'In which season do women wear bikinis?', o: ['Summer','Winter','Spring','Fall'] },

  // 12b. WEATHER (new)
  350: { q: 'What happens when strong wind and rain come together?', o: ['Storm','Light rain','Mist','Strong sun'] },
  351: { q: 'What do we call the little ice balls that fall from the sky?', o: ['Hail','Snow','Rain','Cloud'] },
  352: { q: 'What does the sun do to a puddle on the ground?', o: ['It evaporates it','It fills it up more','It freezes it','It rains more'] },
  353: { q: 'What is the thick mist that covers everything in the morning?', o: ['Fog','Rain','Snow','Smoke'] },
  354: { q: 'What are the bright flashes during a storm?', o: ['Lightning','Rain','Wind','Water'] },
  355: { q: 'What instrument measures air temperature?', o: ['Thermometer','Ruler','Scale','Telescope'] },
  356: { q: 'When rain falls and the sun shines at the same time, what appears?', o: ['Rainbow','Star','Moon','Cloud'] },
  357: { q: 'What covers very tall mountains even in summer?', o: ['Snow','Warm sun','Rain','Mist'] },
  358: { q: 'What happens to gray clouds when they get too heavy?', o: ['It rains','It clears up','It gets very windy','It snows'] },

  // 13b. COLORS (new)
  359: { q: 'What color do we get when we mix blue and red?', o: ['Purple','Orange','Yellow','Brown'] },
  360: { q: 'What color is a carrot?', o: ['Orange','Red','Yellow','Green'] },
  361: { q: 'What color is milk?', o: ['White','Yellow','Gray','Blue'] },
  362: { q: 'What color is a Sicilian lemon?', o: ['Yellow','Green','Orange','White'] },
  363: { q: 'What color is forest soil?', o: ['Brown','Black','Red','Yellow'] },
  364: { q: 'What color is lavender and violet?', o: ['Purple','Blue','Pink','Yellow'] },
  365: { q: 'What color is watermelon inside?', o: ['Red','Green','Yellow','Orange'] },
  366: { q: 'What color do we get when we mix black and white?', o: ['Gray','Brown','Blue','Purple'] },
  367: { q: 'What color is a flamingo?', o: ['Pink','Red','Orange','White'] },

  // 14b. SHAPES (new)
  368: { q: 'Which shape has 8 equal sides like a STOP sign?', o: ['Octagon','Square','Triangle','Circle'] },
  369: { q: 'What is the shape of an egg?', o: ['Oval','Circle','Square','Triangle'] },
  370: { q: 'What is the 3D shape of a box?', o: ['Rectangular prism','Sphere','Pyramid','Diamond'] },
  371: { q: 'Which shape has 4 equal sides?', o: ['Square','Rectangle','Triangle','Circle'] },
  372: { q: 'What shape is a car tire?', o: ['Circle','Square','Triangle','Rectangle'] },
  373: { q: 'What shape is a shoebox?', o: ['Rectangle','Square','Triangle','Circle'] },
  374: { q: 'What shape is a paper kite?', o: ['Diamond','Square','Triangle','Circle'] },
  375: { q: 'What is the shape of an Egyptian pyramid?', o: ['Triangle','Square','Circle','Rectangle'] },
  376: { q: 'What do we call a ball in 3D shape?', o: ['Sphere','Cube','Pyramid','Rectangular prism'] },

  // 15b. NUMBERS (new)
  377: { q: 'What is 1 + 1?', o: ['Two','One','Three','Four'] },
  378: { q: 'How many wings does a butterfly have?', o: ['Four','Two','Six','Eight'] },
  379: { q: 'How many months are in a year?', o: ['Twelve','Four','Six','Three'] },
  380: { q: 'What is 5 minus 2?', o: ['Three','Two','Four','Five'] },
  381: { q: 'How many sides does a square have?', o: ['Four','Three','Five','Six'] },
  382: { q: 'What is 3 + 3?', o: ['Six','Four','Five','Seven'] },
  383: { q: 'How many eggs are in half a dozen?', o: ['Six','Four','Eight','Three'] },
  384: { q: 'How many fingers and toes do we have in total?', o: ['Twenty','Ten','Fifteen','Five'] },
  385: { q: 'How many legs does a cow have?', o: ['Four','Two','Six','Eight'] },

  // 16b. FAMILY (new)
  386: { q: 'Who is your mom’s sister?', o: ['Aunt','Grandpa','Cousin','Godfather'] },
  387: { q: 'Who is your uncle’s son?', o: ['Cousin','Baby brother','Aunt','Grandpa'] },
  388: { q: 'What do we call dad and mom together?', o: ['Parents','Couple','Grandparents','Bride and groom'] },
  389: { q: 'Who can take care of children when their parents are working?', o: ['Babysitter','Doctor','Teacher','Police officer'] },
  390: { q: 'Who is your aunt’s husband?', o: ['Uncle','Grandpa','Dad','Cousin'] },
  391: { q: 'What do we call your sister or brother’s child?', o: ['Nephew','Baby cousin','Brother-in-law','Godson'] },
  392: { q: 'Who is the mother of your mom or dad?', o: ['Grandma','Aunt','Cousin','Babysitter'] },
  393: { q: 'What do we do together when it’s someone in the family’s birthday?', o: ['Celebrate','Cry','Sleep','Run away'] },
  394: { q: 'What do we call the oldest sibling?', o: ['Older brother','Grandpa','Uncle','Police officer'] },

  // 17b. EMOTIONS (new)
  395: { q: 'How do you feel when your best friend comes to play?', o: ['Cheerful','Sad','Scared','Sleepy'] },
  396: { q: 'How do you feel when you fall and hurt your knee?', o: ['In pain','Happy','Angry','Sleepy'] },
  397: { q: 'How do you feel when you hear a loud, surprising noise?', o: ['Startled','Calm','Thoughtful','Satisfied'] },
  398: { q: 'How do you feel when your teacher praises you?', o: ['Proud','Sad','Scared','Angry'] },
  399: { q: 'How do you feel when you see a really cute puppy?', o: ['Delighted','Scared','Sad','Angry'] },
  400: { q: 'How do you feel when you’re stuck at home and can’t play outside?', o: ['Bored','Happy','In love','Excited'] },
  401: { q: 'How do you feel when someone says they have a secret?', o: ['Curious','Sad','Angry','Sleepy'] },
  402: { q: 'How do you feel when you finish eating a delicious meal?', o: ['Satisfied','Sad','Scared','Angry'] },
  403: { q: 'How do you feel when you can’t do something on your own?', o: ['Frustrated','Happy','Delighted','Excited'] },

  // 18b. BODY (new)
  404: { q: 'Which body part do we use to bite an apple?', o: ['Teeth','Tongue','Nose','Ear'] },
  405: { q: 'Which body part grows nails?', o: ['Fingers','Legs','Ears','Eyes'] },
  406: { q: 'Which body organ beats faster when we run?', o: ['Heart','Brain','Lung','Bone'] },
  407: { q: 'Which body part forms a smile?', o: ['Mouth','Eyes','Ears','Nose'] },
  408: { q: 'Which body part turns red when we feel embarrassed?', o: ['Face','Hands','Legs','Nose'] },
  409: { q: 'Which body part do we use to push heavy things?', o: ['Arms','Legs','Eyes','Ears'] },
  410: { q: 'Which body part filters the blood and makes pee?', o: ['Kidneys','Heart','Lung','Brain'] },
  411: { q: 'Which body part do we hear with?', o: ['Ear','Hands','Eyes','Legs'] },
  412: { q: 'Which body part helps us think and learn?', o: ['Brain','Heart','Lung','Bone'] },

  // 19b. SCHOOL (new)
  413: { q: 'What do we use to glue paper and poster board?', o: ['Glue','Scissors','Ruler','Pencil'] },
  414: { q: 'Where are the books kept for all students to read?', o: ['Library',"Principal's office",'House','Store'] },
  415: { q: 'Which instrument makes noise to call the students?', o: ['Bell','Horn','Drum','Trumpet'] },
  416: { q: 'What do you stick on the school wall to announce something?', o: ['Poster','TV','Computer','Phone'] },
  417: { q: 'What do we use to finger-paint in art class?', o: ['Finger paint','Pencil','Ruler','Scissors'] },
  418: { q: 'What do we keep our snack in to take to school?', o: ['Lunch box','School backpack','Bag','Box'] },
  419: { q: 'What does the teacher give the kids to do at home?', o: ['Homework','Game','Free drawing','Movie'] },
  420: { q: 'What do we use to measure the length of things?', o: ['Ruler','Pencil','Paintbrush','Scissors'] },
  421: { q: 'Where do kids play and run during recess?', o: ['Playground','Classroom','Bathroom','Cafeteria'] },

  // 20b. TRANSPORTATION (new)
  422: { q: 'What has a propeller and flies close to the ground?', o: ['Helicopter','Airplane','Glider','Rocket'] },
  423: { q: 'What travels underwater?', o: ['Submarine','Ship','Sailboat','Speedboat'] },
  424: { q: 'What do firefighters use to get to a fire quickly?', o: ['Fire truck','Ambulance','Police car','Van'] },
  425: { q: 'What has tracks and runs underneath cities?', o: ['Subway','Train','Bus','Car'] },
  426: { q: 'What do people use to cross rivers with paddles?', o: ['Canoe','Sailboat','Ship','Speedboat'] },
  427: { q: 'What travels through space, leaving Earth with lots of fire?', o: ['Rocket','Airplane','Helicopter','Flying saucer'] },
  428: { q: 'What works in fields and crops?', o: ['Tractor','Truck','Car','Bus'] },
  429: { q: 'What do kids ride in the park with pedals and 3 wheels?', o: ['Tricycle','Scooter','Skateboard','Race car'] },
  430: { q: 'What has lots of wheels and carries cargo on the roads?', o: ['Truck','Bus','Car','Van'] },

  // 21b. OCCUPATIONS (new)
  431: { q: 'Who makes warm, delicious bread early in the morning?', o: ['Baker','Doctor','Police officer','Construction worker'] },
  432: { q: 'Who takes care of crops and harvests food in the fields?', o: ['Farmer','Cook','Construction worker','Doctor'] },
  433: { q: 'Who paints walls and houses with colorful rollers?', o: ['Painter','Construction worker','Mechanic','Cook'] },
  434: { q: 'Who fixes cars and engines with tools?', o: ['Mechanic','Construction worker','Painter','Farmer'] },
  435: { q: 'Who tidies the garden and takes care of plants and flowers?', o: ['Gardener','Farmer','Mechanic','Painter'] },
  436: { q: 'Who makes clothes using needle and thread?', o: ['Seamstress','Painter','Gardener','Mechanic'] },
  437: { q: 'Who takes photos at weddings and parties?', o: ['Photographer','Cameraman','Director','Actor'] },
  438: { q: 'Who works by throwing balls into a hoop?', o: ['Basketball player','Veterinarian','Farmer','Doctor'] },
  439: { q: 'Who drives the school bus carrying the kids?', o: ['Driver','Police officer','Construction worker','Cook'] },

  // 22b. FOOD (new)
  440: { q: 'Which creamy food is made with milk and has fruit flavor?', o: ['Yogurt','Cheese','Butter','Ice cream'] },
  441: { q: 'Which food is round with a hole in the middle and is sweet?', o: ['Donut','Cookie','Cake','Pie'] },
  442: { q: 'Which savory food goes with beans in Brazil?', o: ['Rice','Pasta','Bread','Tacos'] },
  443: { q: 'Which breakfast food is corn flakes with milk?', o: ['Cereal','Egg','Pancake','Cookie'] },
  444: { q: 'Which food is made by beating eggs in a pan?', o: ['Omelet','Pancake','Cereal','Cookie'] },
  445: { q: 'Which hot food is made with noodles and lots of broth?', o: ['Soup','Dry pasta','Stew','Cauldron'] },
  446: { q: 'Which creamy food is made with avocado?', o: ['Guacamole','Cheese','Yogurt','Ice cream'] },
  447: { q: 'Which food is made from cocoa and melts in your mouth?', o: ['Chocolate','Candy','Pie','Cupcake'] },
  448: { q: 'Which food is beans that go well with rice?', o: ['Beans','Rice','Cereal','Tacos'] },

  // 23b. CLOTHES (new)
  449: { q: 'What do we put on our head so the sun doesn’t hit us?', o: ['Hat','Gloves','Scarf','Sunglasses'] },
  450: { q: 'What do we wear at the waist to hold up our pants?', o: ['Belt','Socks','Sneakers','Dress'] },
  451: { q: 'What do we put on our neck to decorate as an accessory?', o: ['Necklace','Gloves','Socks','Sneakers'] },
  452: { q: 'What do we put on our wrists as a shiny accessory?', o: ['Bracelet','Gloves','Scarf','Hat'] },
  453: { q: 'What do ballerinas wear to dance, with a flared skirt?', o: ['Tutu','Dress','Swimsuit','Bikini'] },
  454: { q: 'What do we wear to go to the beach and swim in the sea?', o: ['Swimsuit or trunks','Dress','Coat','Sneakers'] },
  455: { q: 'What do we wear to sleep comfortably at night?', o: ['Pajamas','Dress','Coat','Jeans'] },
  456: { q: 'What do we put on our feet inside our shoes?', o: ['Socks','Sneakers','Slippers','High heels'] },
  457: { q: 'What protects your head from the sun at the playground?', o: ['Cap','Straw hat','Top hat','Scarf'] },

  // 24b. HOUSEHOLD OBJECTS (new)
  458: { q: 'What rings when someone arrives at the front door?', o: ['Doorbell','Door','Key','Phone'] },
  459: { q: 'What do we use to reach things up high?', o: ['Ladder','Elevator','Rope','Scooter'] },
  460: { q: 'What do we turn on for water to come out and wash our hands?', o: ['Faucet','Bucket','Sponge','Broom'] },
  461: { q: 'What shows us what time it is?', o: ['Clock','TV','Phone','Lamp'] },
  462: { q: 'What do we use to make suds when washing our hands?', o: ['Soap','Toothbrush','Sponge','Bucket'] },
  463: { q: 'What do we use to scrub away dirt?', o: ['Sponge','Cleaning cloth','Bucket','Brush'] },
  464: { q: 'What do we use to dry dishes after washing?', o: ['Dish towel','Broom','Bucket','Sponge'] },
  465: { q: 'What heats the room in winter?', o: ['Heater','Air conditioner','Lamp','TV'] },
  466: { q: 'What do we use to talk to someone far away?', o: ['Phone','TV','Lamp','Doorbell'] },

  // 25b. TOYS (new)
  467: { q: 'Which playground toy has ropes and swings?', o: ['Swing','See-saw','Slide','Yo-yo'] },
  468: { q: 'Which toy makes music when we press the buttons?', o: ['Toy keyboard','Drum','Trumpet','Guitar'] },
  469: { q: 'Which toy lets you create shapes?', o: ['Play-dough','Paintbrush','Pencil','Notebook'] },
  470: { q: 'Which toy is played with picture cards?', o: ['Deck of cards','Dice','Puzzle','Video game'] },
  471: { q: 'Which toy has sand that flows as time passes?', o: ['Hourglass','Clock','Wall clock','Calendar'] },
  472: { q: 'Which toy do you use a controller for?', o: ['Video game','Doctor kit','Backpack','Teddy bear'] },
  473: { q: 'Which toy has colorful bricks to build houses?', o: ['Building blocks','Dice','Puzzle','Video game'] },
  474: { q: 'Which playground toy do kids slide down?', o: ['Slide','Ferris wheel','Carousel','Circus'] },
  475: { q: 'Which toy has a mirror and makes colorful lights when you spin it?', o: ['Kaleidoscope','Telescope','Microscope','Flashlight'] },

  // 26. SPACE AND UNIVERSE (new category)
  476: { q: 'Which planet is our home?', o: ['Earth','Moon','Saturn','Mars'] },
  477: { q: 'What lights up our day here on Earth?', o: ['Sun','Moon','Star','Earth'] },
  478: { q: 'What appears in the night sky, big and bright?', o: ['Moon','Sun','Star','Earth'] },
  479: { q: 'What do we call the person who goes to space?', o: ['Astronaut','Pilot','Sailor','Firefighter'] },
  480: { q: 'In which vehicle does an astronaut go to space?', o: ['Rocket','Airplane','Helicopter','Flying saucer'] },
  481: { q: 'What do we call the tiny bright dots in the night sky?', o: ['Stars','Moons','Planets','Suns'] },
  482: { q: 'Which planet has beautiful rings around it?', o: ['Saturn','Earth','Moon','Sun'] },
  483: { q: 'What do we call the huge space where the planets are?', o: ['Universe','Earth','Ocean','Mountain'] },
  484: { q: 'Which planet is red like blood?', o: ['Mars','Earth','Moon','Saturn'] },
  485: { q: 'What is the biggest planet in the solar system?', o: ['Jupiter','Earth','Mars','Neptune'] },
  486: { q: 'What does an astronaut wear to breathe in space?', o: ['Space suit','Regular mask','T-shirt','Coat'] },
  487: { q: 'What does a telescope do?', o: ['See faraway stars','See tiny things','Take photos','Watch TV'] },
  488: { q: 'What is our only natural satellite?', o: ['Moon','Star','Earth','Saturn'] },
  489: { q: 'What do we call a light that streaks across the night sky?', o: ['Meteor','Moon','Sun','Galaxy'] },
  490: { q: 'What does the Sun give us besides light?', o: ['Heat','Water','Seeds','Food'] },
  491: { q: 'How many planets are in the Solar System?', o: ['Eight','Four','Six','Ten'] },
  492: { q: 'What is the coldest planet in the Solar System?', o: ['Neptune','Earth','Mars','Mercury'] },
  493: { q: 'What happens to things in space without gravity?', o: ['They float','They fall to the ground','They rise fast','They explode'] },
  494: { q: 'What do we call a giant rock that travels through space?', o: ['Asteroid','Planet','Star','Satellite'] },
  495: { q: 'What is a galaxy?', o: ['Billions of stars together','A big moon','A planet','A sun'] },
  496: { q: 'What color does our star, the Sun, appear to be?', o: ['Yellow','Red','Blue','Green'] },
  497: { q: 'Which animal was the first to go to space?', o: ['Laika the dog','Monkey','Fish','Bird'] },
  498: { q: 'Which planet is closest to the Sun?', o: ['Mercury','Earth','Mars','Saturn'] },
  499: { q: 'What do space agencies launch to explore other planets?', o: ['Probes and rockets','Airplanes','Helicopters','Boats'] },
  500: { q: 'What do we call the imaginary line around the middle of the Earth?', o: ['Equator','Ocean','Mountain','North Pole'] },

  // 1c. PETS (new batch 2)
  501: { q: 'Which small pet curls into a ball and has soft spikes when scared?', o: ['Pet hedgehog','Rabbit','Hamster','Cat'] },
  502: { q: 'Which pet stores food in its cheeks to eat later?', o: ['Hamster','Dog','Cat','Rabbit'] },
  503: { q: 'Which pet loves chasing balls of yarn rolling on the floor?', o: ['Cat','Dog','Turtle','Fish'] },
  504: { q: 'Which pet likes to bury little bones in the yard to save for later?', o: ['Dog','Cat','Parrot','Hamster'] },
  505: { q: 'Which round, fluffy little animal lives in groups and makes squeaking whistle sounds?', o: ['Guinea pig','Rabbit','Mouse','Squirrel'] },
  506: { q: 'Which pet can change color to match its surroundings?', o: ['Chameleon','Turtle','Snake','Frog'] },
  507: { q: 'What do we call the glass house full of water where pet fish live?', o: ['Fish tank','Cage','Doghouse','Anthill'] },
  508: { q: 'Which pet can learn tricks like sitting and giving its paw?', o: ['Dog','Cat','Turtle','Hamster'] },
  509: { q: 'Which pet sleeps most of the day, almost 15 hours?', o: ['Cat','Dog','Rabbit','Fish'] },
  510: { q: 'Which long, playful pet loves hiding in tunnels and burrows?', o: ['Ferret','Hamster','Rabbit','Squirrel'] },

  // 2c. WILD ANIMALS (new batch 2)
  511: { q: 'Which giant wild animal has a hump of fat on its back to survive the desert?', o: ['Camel','Giraffe','Rhino','Elephant'] },
  512: { q: 'Which wild animal sleeps about 20 hours a day clinging to eucalyptus branches?', o: ['Koala','Panda','Sloth','Monkey'] },
  513: { q: 'What is the world\'s largest rodent, very common in Brazil near rivers and lakes?', o: ['Capybara','Squirrel','Hamster','Mouse'] },
  514: { q: 'What is the largest cat in the Americas, with a coat full of rosette-shaped spots?', o: ['Jaguar','Tiger','Lion','Leopard'] },
  515: { q: 'Which giant wild animal has a huge mouth and spends the day in water to cool off?', o: ['Hippo','Elephant','Rhino','Alligator'] },
  516: { q: 'Which wild animal beats its chest with its hands to show strength?', o: ['Gorilla','Monkey','Bear','Orangutan'] },
  517: { q: 'What is the slowest animal in the world, spending its life hanging upside down in trees?', o: ['Sloth','Koala','Monkey','Kangaroo'] },
  518: { q: 'Which wild animal has pointy ears with tufts of fur and lives in cold forests?', o: ['Lynx','Tiger','Lion','Fox'] },
  519: { q: 'Which wild animal has a very long, sticky tongue for eating ants and termites?', o: ['Anteater','Hedgehog','Koala','Sloth'] },
  520: { q: 'Which wild animal can shed its entire skin as it grows?', o: ['Snake','Lizard','Frog','Turtle'] },

  // 3c. SEA ANIMALS (new batch 2)
  521: { q: 'Which sea animal swims thousands of kilometers and returns to the very beach where it was born to lay its eggs?', o: ['Sea turtle','Dolphin','Shark','Octopus'] },
  522: { q: 'Which sea animal claps its flippers and slides on its belly across the ice?', o: ['Seal','Penguin','Whale','Otter'] },
  523: { q: 'Which sea animal has a long spiral horn and is called the "unicorn of the sea"?', o: ['Narwhal','Dolphin','Whale','Shark'] },
  524: { q: 'Which sea animal is huge, very gentle, and spends the day eating water plants?', o: ['Manatee','Whale','Seal','Dolphin'] },
  525: { q: 'Which sea animal has two long white tusks and lives in icy waters?', o: ['Walrus','Seal','Penguin','Whale'] },
  526: { q: 'Which sea animal can give electric shocks to defend itself?', o: ['Electric eel','Octopus','Crab','Pufferfish'] },
  527: { q: 'Which little fish can leap out of the water and glide as if it were flying?', o: ['Flying fish','Dolphin','Shark','Clownfish'] },
  528: { q: 'What forms the colorful reefs where little fish love to swim and hide?', o: ['Coral','Rock','Seaweed','Shell'] },
  529: { q: 'Which dolphin is pink and lives in the rivers of the Amazon rainforest?', o: ['Amazon river dolphin','Dolphin','Alligator','Manatee'] },
  530: { q: 'Which small sea animal flicks its tail to jump backward when startled?', o: ['Shrimp','Crab','Lobster','Sea snail'] },

  // 4c. FARM ANIMALS (new batch 2)
  531: { q: 'What do we call a baby cow?', o: ['Calf','Piglet','Foal','Lamb'] },
  532: { q: 'What do we call a baby pig?', o: ['Piglet','Calf','Kid goat','Chick'] },
  533: { q: 'What do we call a baby chicken?', o: ['Chick','Calf','Piglet','Foal'] },
  534: { q: 'What do we call a baby horse?', o: ['Foal','Calf','Kid goat','Lamb'] },
  535: { q: 'What do we call a baby goat?', o: ['Kid goat','Lamb','Piglet','Chick'] },
  536: { q: 'Which farm bird hisses loudly to scare off strangers and guards the property?', o: ['Goose','Duck','Turkey','Chicken'] },
  537: { q: 'Which small farm bird lays tiny little eggs?', o: ['Quail','Chicken','Turkey','Goose'] },
  538: { q: 'Which animal helps the farmer round up the sheep into a flock?', o: ['Sheepdog','Cat','Horse','Duck'] },
  539: { q: 'Which farm animal pulls the cart and helps plow the land?', o: ['Ox','Cow','Horse','Goat'] },
  540: { q: 'Which farm animal chews its food twice to digest it better?', o: ['Cow','Pig','Chicken','Horse'] },

  // 5c. INSECTS (new batch 2)
  541: { q: 'Which insect is so strong it can push a ball bigger than its own body?', o: ['Dung beetle','Ladybug','Cricket','Ant'] },
  542: { q: 'Which insect looks like a butterfly but flies at night, drawn to light?', o: ['Moth','Butterfly','Bee','Mosquito'] },
  543: { q: 'Which insect makes a loud, high-pitched sound on hot summer days?', o: ['Cicada','Cricket','Bee','Butterfly'] },
  544: { q: 'Which tiny insect jumps very high in dogs\' and cats\' fur?', o: ['Flea','Ant','Caterpillar','Ladybug'] },
  545: { q: 'Which little creature has a very long body and lots and lots of tiny legs?', o: ['Centipede','Ant','Slug','Spider'] },
  546: { q: 'What do we call the bee that rules the whole hive and lays all the eggs?', o: ['Queen bee','Worker bee','Ant','Butterfly'] },
  547: { q: 'Which insect spins a cocoon of soft silk before turning into a moth?', o: ['Silkworm','Caterpillar','Spider','Slug'] },
  548: { q: 'Which insect releases a strong smell when it feels threatened?', o: ['Stink bug','Bee','Cricket','Ladybug'] },
  549: { q: 'Which ant cuts little pieces of leaves and carries them on its back to the anthill?', o: ['Leafcutter ant','Ant','Bee','Grasshopper'] },
  550: { q: 'Which tiny insect likes to eat wool clothes stored in the closet?', o: ['Clothes moth','Flea','Caterpillar','Spider'] },

  // 6c. BIRDS (new batch 2)
  551: { q: 'Which huge, colorful bird lives in the Amazon rainforest and is a symbol of Brazil?', o: ['Macaw','Parrot','Flamingo','Peacock'] },
  552: { q: 'Which little bird builds its nest out of mud and travels to very far places?', o: ['Swallow','Penguin','Dove','Sparrow'] },
  553: { q: 'Which bird eats animals that have already died and helps keep nature clean?', o: ['Vulture','Eagle','Owl','Parrot'] },
  554: { q: 'Which bird has a huge beak with a pouch to store the fish it catches?', o: ['Pelican','Penguin','Flamingo','Duck'] },
  555: { q: 'What is the largest bird in the world — it can\'t fly but runs very fast?', o: ['Ostrich','Penguin','Flamingo','Turkey'] },
  556: { q: 'Which Brazilian bird loudly cries its own name to warn other animals of danger?', o: ['Southern lapwing','Sparrow','Dove','Eagle'] },
  557: { q: 'Which small yellow bird sings beautifully and is very common as a caged pet?', o: ['Canary','Parrot','Sparrow','Penguin'] },
  558: { q: 'Which bird flies near the sea and loves diving to catch little fish?', o: ['Seagull','Penguin','Flamingo','Duck'] },
  559: { q: 'Which Brazilian bird sings a call that sounds like it\'s saying its own name?', o: ['Great kiskadee','Rufous hornero','Sparrow','Canary'] },
  560: { q: 'Which bird of prey hunts other small animals using very sharp claws?', o: ['Hawk','Eagle','Owl','Vulture'] },

  // 7c. DINOSAURS (new batch 2)
  561: { q: 'What was the largest dinosaur ever found, discovered in Argentina?', o: ['Argentinosaurus','Brachiosaurus','T-Rex','Diplodocus'] },
  562: { q: 'How were baby dinosaurs born?', o: ['From eggs','From a bottle','From seeds','Fully grown, out of nowhere'] },
  563: { q: 'What fell from the sky and helped make the dinosaurs disappear from Earth?', o: ['A giant asteroid','A lot of rain','A snowflake','A balloon'] },
  564: { q: 'Which dinosaur had a sharp, spike-shaped thumb?', o: ['Iguanodon','Triceratops','T-Rex','Stegosaurus'] },
  565: { q: 'What do we call the person who studies dinosaur bones and assembles the skeletons?', o: ['Paleontologist','Teacher','Doctor','Chef'] },
  566: { q: 'Where can we see giant dinosaur skeletons assembled?', o: ['Natural history museum','School','Hospital','Castle'] },
  567: { q: 'Which carnivorous dinosaur was as small as a chicken?', o: ['Compsognathus','T-Rex','Brachiosaurus','Triceratops'] },
  568: { q: 'What do we call dinosaurs that ate only plants, without hunting other animals?', o: ['Herbivores','Carnivores','Omnivores','Extinct'] },
  569: { q: 'What do we call dinosaurs that hunted and ate meat from other animals?', o: ['Carnivores','Herbivores','Omnivores','Egg-layers'] },
  570: { q: 'Which small dinosaur had two crests on its head and is famous in movies?', o: ['Dilophosaurus','Velociraptor','Parasaurolophus','Ankylosaurus'] },

  // 8c. FRUITS (new batch 2)
  571: { q: 'Which fruit is pink inside, very Brazilian, and used to make guava paste?', o: ['Guava','Apple','Orange','Strawberry'] },
  572: { q: 'Which is one of the biggest fruits in the world, huge with lots of sweet segments inside?', o: ['Jackfruit','Pineapple','Watermelon','Banana'] },
  573: { q: 'Which Brazilian fruit has its nut growing on the outside, at its tip?', o: ['Cashew fruit','Cherry','Peach','Grape'] },
  574: { q: 'Which fruit is full of red, juicy little seeds inside, like tiny jewels?', o: ['Pomegranate','Apple','Grape','Orange'] },
  575: { q: 'Which fruit is shaped like a bell, thinner on top and wider at the bottom?', o: ['Pear','Apple','Banana','Peach'] },
  576: { q: 'Which tiny red fruit is made of many little bumps stuck together?', o: ['Raspberry','Strawberry','Grape','Cherry'] },
  577: { q: 'Which small, blue-purple fruit is about the size of a pea?', o: ['Blueberry','Grape','Strawberry','Cherry'] },
  578: { q: 'Which large, round fruit has a net-patterned rind and sweet orange flesh?', o: ['Melon','Watermelon','Pineapple','Mango'] },
  579: { q: 'Which fruit is purple outside and pink, sweet as honey, inside?', o: ['Fig','Grape','Peach','Guava'] },
  580: { q: 'Which fruit has a rough red skin but is white and sweet inside?', o: ['Lychee','Coconut','Melon','Peach'] },

  // 9c. VEGETABLES (new batch 2)
  581: { q: 'Which round orange vegetable do we use to decorate for Halloween and make sweets?', o: ['Pumpkin','Tomato','Carrot','Broccoli'] },
  582: { q: 'Which vegetable grows underground and can become French fries?', o: ['Potato','Carrot','Onion','Sweet potato'] },
  583: { q: 'Which reddish-purple vegetable can stain your hands and even your mouth when you eat it?', o: ['Beet','Carrot','Tomato','Potato'] },
  584: { q: 'Which dark green leaf is used to make Brazilian feijoada?', o: ['Collard greens','Lettuce','Broccoli','Bell pepper'] },
  585: { q: 'Which round vegetable is made of many leaves wrapped around each other?', o: ['Cabbage','Collard greens','Broccoli','Lettuce'] },
  586: { q: 'Which long green vegetable looks like a cucumber but with lighter skin?', o: ['Zucchini','Cucumber','Bell pepper','Broccoli'] },
  587: { q: 'Which green vegetable gets a bit slimy when cooked?', o: ['Okra','Corn','Pea','Eggplant'] },
  588: { q: 'Which sweet orange vegetable also grows underground, like the potato?', o: ['Sweet potato','Potato','Carrot','Onion'] },
  589: { q: 'Which mild-flavored, light green vegetable is very common in Brazilian cooking?', o: ['Chayote','Cucumber','Collard greens','Eggplant'] },
  590: { q: 'Which small vegetable is red outside, white inside, and has a spicy taste?', o: ['Radish','Garlic','Carrot','Tomato'] },

  // 10c. NATURE (new batch 2)
  591: { q: 'Which living thing grows on the forest floor, with some types edible and others poisonous?', o: ['Mushroom','Flower','Leaf','Sprout'] },
  592: { q: 'What do we call the soft green layer that grows on damp, shady rocks and tree trunks?', o: ['Moss','Mushroom','Leaf','Cactus'] },
  593: { q: 'Which plant grows very fast and is the panda\'s favorite food?', o: ['Bamboo','Pine tree','Tree','Leaf'] },
  594: { q: 'Which little creature lives inside the soil and helps make it fertile for plants to grow?', o: ['Earthworm','Caterpillar','Slug','Ant'] },
  595: { q: 'What do we call water falling from a great height, forming a beautiful drop in the mountains?', o: ['Waterfall','Mountain','Desert','Volcano'] },
  596: { q: 'What do we call a very tall landform that can even have snow on top?', o: ['Mountain','River','Desert','Volcano'] },
  597: { q: 'Which place is very dry, very hot by day and very cold by night, with almost no rain?', o: ['Desert','Forest','Mountain','River'] },
  598: { q: 'What do we call it when a bee carries pollen from flower to flower, helping new plants grow?', o: ['Pollination','Germination','Photosynthesis','Hibernation'] },
  599: { q: 'What do we call the fresh water that flows from the mountains until it reaches the sea?', o: ['River','Mountain','Volcano','Desert'] },
  600: { q: 'What does a little seed do, breaking its shell, so the plant can start to grow?', o: ['Germination','Pollination','Photosynthesis','Autumn'] },

  // 11c. SEASONS (new batch 2)
  601: { q: 'In which season do fruit trees become full of little white and pink blossoms?', o: ['Spring','Summer','Autumn','Winter'] },
  602: { q: 'In which season do many birds migrate, flying to warmer places?', o: ['Autumn','Summer','Spring','Winter'] },
  603: { q: 'In which season do we wear sunscreen and a hat to avoid getting too much sun?', o: ['Summer','Autumn','Spring','Winter'] },
  604: { q: 'In which season do the days get shorter and it gets dark much earlier?', o: ['Winter','Summer','Spring','Autumn'] },
  605: { q: 'In which season do families often make warm soup to stay cozy?', o: ['Winter','Summer','Autumn','Spring'] },
  606: { q: 'In which season are bird nests often full of newly hatched chicks?', o: ['Spring','Winter','Autumn','Summer'] },
  607: { q: 'In which season do we use a fan or air conditioner to cool the house?', o: ['Summer','Winter','Spring','Autumn'] },
  608: { q: 'In which season do chestnuts and nuts fall from the trees and can be gathered?', o: ['Autumn','Spring','Summer','Winter'] },
  609: { q: 'In which season do families often plant a garden because the soil is ready for new seeds?', o: ['Spring','Autumn','Winter','Summer'] },
  610: { q: 'In which season do Brazil\'s "Festas Juninas" happen, with bonfires and folk dancing?', o: ['Winter','Summer','Spring','Autumn'] },

  // 12c. WEATHER (new batch 2)
  611: { q: 'What do we use to avoid getting wet when it\'s raining?', o: ['Umbrella','Coat','T-shirt','Sunglasses'] },
  612: { q: 'What do we call it when it doesn\'t rain for a long time and the ground becomes dry and cracked?', o: ['Drought','Rain','Snow','Fog'] },
  613: { q: 'What do we call a very light, pleasant wind that we feel on our face?', o: ['Breeze','Windstorm','Storm','Snow'] },
  614: { q: 'What do we feel in the air when it\'s heavy and sticky, even without rain?', o: ['Humidity','Wind','Dry heat','Rain'] },
  615: { q: 'What do we call the moment the sun disappears over the horizon and the sky turns orange and pink?', o: ['Sunset','Sunrise','Moon','Star'] },
  616: { q: 'What do we call the moment the sun appears again, early in the morning?', o: ['Sunrise','Sunset','Moon','Rain'] },
  617: { q: 'What do we call the tropical season with lots of heavy rain almost every day?', o: ['Rainy season','Drought','Snow','Windstorm'] },
  618: { q: 'What do we call the very strong wind that can knock down trees and even roofs?', o: ['Windstorm','Breeze','Light rain','Sun'] },
  619: { q: 'What do we call the puddle that forms on the ground after heavy rain?', o: ['Puddle','Glacier','Ice','Rainbow'] },
  620: { q: 'What do we call the phenomenon of colorful lights dancing in the night sky near the North Pole?', o: ['Northern lights','Rainbow','Lightning','Fog'] },

  // 13c. COLORS (new batch 2)
  621: { q: 'What color is a ripe banana?', o: ['Yellow','Green','Red','Purple'] },
  622: { q: 'What is the most common color of a pair of jeans?', o: ['Blue','Green','Black','Brown'] },
  623: { q: 'What color is a ripe strawberry?', o: ['Red','Yellow','Green','Purple'] },
  624: { q: 'What is the most common color of cotton candy?', o: ['Pink','Purple','Red','White'] },
  625: { q: 'Which shiny, metallic color looks like gold?', o: ['Golden','Silver','Yellow','Brown'] },
  626: { q: 'Which shiny, metallic color looks shiny gray?', o: ['Silver','Golden','White','Black'] },
  627: { q: 'Which color looks like a tropical sea, a mix of blue and green?', o: ['Turquoise','Blue','Green','Purple'] },
  628: { q: 'What do we call the group of colors that remind us of fire and sun, like red, orange and yellow?', o: ['Warm colors','Cool colors','Neutral colors','Pastel colors'] },
  629: { q: 'What do we call the group of colors that remind us of ice and the sea, like blue, green and purple?', o: ['Cool colors','Warm colors','Bright colors','Dark colors'] },
  630: { q: 'When we mix paint of every color together, which very dark color usually forms?', o: ['Black','White','Brown','Purple'] },

  // 14c. SHAPES (new batch 2)
  631: { q: 'Which shape has 5 sides, like the little house we draw with a pointy roof?', o: ['Pentagon','Square','Triangle','Hexagon'] },
  632: { q: 'Which shape has 6 equal sides, like the honeycomb cells made by bees?', o: ['Hexagon','Pentagon','Square','Star'] },
  633: { q: 'Which 3D shape looks like an ice cream cone or a party hat?', o: ['Cone','Sphere','Cube','Cylinder'] },
  634: { q: 'Which 3D shape looks like a soda can or a pipe?', o: ['Cylinder','Cone','Cube','Sphere'] },
  635: { q: 'Which shape looks like half a circle, like a rainbow or a watermelon slice cut in half?', o: ['Semicircle','Circle','Star','Triangle'] },
  636: { q: 'Which shape looks like the drawing of love, usually painted red or pink?', o: ['Heart','Star','Circle','Triangle'] },
  637: { q: 'Which shape has a wide base at the bottom and gets narrower at the top, like a goblet?', o: ['Trapezoid','Square','Rectangle','Triangle'] },
  638: { q: 'What shape are the slices of a pizza after it\'s cut?', o: ['Triangle','Circle','Square','Rectangle'] },
  639: { q: 'Which 3D shape looks like a soccer ball, perfectly round on every side?', o: ['Sphere','Cube','Cylinder','Cone'] },
  640: { q: 'Which 3D shape looks like a shoebox or a brick, similar to a cube but with different-length sides?', o: ['Rectangular block','Cube','Sphere','Cone'] },

  // 15c. NUMBERS (new batch 2)
  641: { q: 'How much is 4 + 1?', o: ['5','4','6','3'] },
  642: { q: 'How much is 10 - 5?', o: ['5','10','4','6'] },
  643: { q: 'How many toes do we have on both feet together?', o: ['10','5','20','8'] },
  644: { q: 'Which number is bigger: 7 or 4?', o: ['7','4','3','5'] },
  645: { q: 'How many eggs are in a whole dozen?', o: ['12','6','10','20'] },
  646: { q: 'What do we call a number that can be split into two equal groups, like 2, 4, 6 and 8?', o: ['Even','Odd','Zero','Infinity'] },
  647: { q: 'What do we call a number that CANNOT be split into two equal groups, like 1, 3, 5 and 7?', o: ['Odd','Even','Zero','Half'] },
  648: { q: 'How many legs does a chicken have?', o: ['2','4','6','8'] },
  649: { q: 'If I have 5 candies and eat 2, how many are left?', o: ['3','2','4','5'] },
  650: { q: 'How many sides does a pentagon have?', o: ['5','4','6','3'] },

  // 16c. FAMILY (new batch 2)
  651: { q: 'What do we call the woman chosen to be your spiritual guardian, usually present at a baptism?', o: ['Godmother','Godfather','Grandmother','Aunt'] },
  652: { q: 'What do we call the man chosen to be your spiritual guardian, usually present at a baptism?', o: ['Godfather','Godmother','Grandfather','Uncle'] },
  653: { q: 'What do we call the father of your grandfather or grandmother?', o: ['Great-grandfather','Grandfather','Father','Cousin'] },
  654: { q: 'What do we call it when a family decides to care for and love a child not biologically their own?', o: ['Adoption','Birth','Wedding','Birthday'] },
  655: { q: 'What do we call the drawing that shows all a family\'s relatives, like the branches of a tree?', o: ['Family tree','Photo album','Recipe book','Map'] },
  656: { q: 'What is the family name everyone shares, usually coming from the father or mother?', o: ['Surname','Address','Birthday','Phone number'] },
  657: { q: 'What do we call the special celebration when two people promise their love and start living together as spouses?', o: ['Wedding','Birthday','Graduation','Christmas'] },
  658: { q: 'What do we call the brother or sister of your husband or wife?', o: ['Brother-in-law or sister-in-law','Cousin','Uncle','Grandfather'] },
  659: { q: 'What do we call the mother of your husband or wife?', o: ['Mother-in-law','Mother','Aunt','Grandmother'] },
  660: { q: 'Who usually tells old family stories and remembers what the past was like?', o: ['Grandparents','Baby','Cousin','Nanny'] },

  // 17c. EMOTIONS (new batch 2)
  661: { q: 'How do you feel when you really want to cry in front of other people?', o: ['Embarrassment','Anger','Joy','Sadness'] },
  662: { q: 'How do you feel when your sibling or friend gets a new toy and you don\'t?', o: ['Jealousy','Joy','Calm','Gratitude'] },
  663: { q: 'How do you feel when someone helps you and you want to thank them from the heart?', o: ['Gratitude','Anger','Jealousy','Fear'] },
  664: { q: 'How do you feel when you face your fear of the dark and go into the room anyway?', o: ['Courage','Fear','Sadness','Sleepiness'] },
  665: { q: 'How do you feel after crying a lot and finally settling down?', o: ['Calm','Anger','Fear','Excitement'] },
  666: { q: 'How do you feel when you don\'t understand the instructions of a new game?', o: ['Confusion','Joy','Calm','Courage'] },
  667: { q: 'How do you feel on the first day of school, with butterflies in your stomach?', o: ['Nervousness','Calm','Joy','Sleepiness'] },
  668: { q: 'What do we call that longing to see again someone we love who is far away?', o: ['Longing','Anger','Joy','Fear'] },
  669: { q: 'How do you feel when you look for a lost toy and finally find it?', o: ['Relief','Sadness','Anger','Fear'] },
  670: { q: 'How do you feel when you see someone in need and want to take care of them?', o: ['Compassion','Jealousy','Anger','Fear'] },

  // 18c. BODY (new batch 2)
  671: { q: 'Which body part fills with air when we take a deep breath?', o: ['Lungs','Heart','Stomach','Brain'] },
  672: { q: 'Which body part receives food after we swallow it, and helps digest it?', o: ['Stomach','Lungs','Heart','Brain'] },
  673: { q: 'What supports our body and is made of bones?', o: ['Skeleton','Muscles','Blood','Heart'] },
  674: { q: 'What lies beneath the skin and gives us strength to lift things?', o: ['Muscles','Skeleton','Blood','Lungs'] },
  675: { q: 'What is the largest organ of the body, covering everything outside and feeling touch, cold and heat?', o: ['Skin','Hair','Muscles','Skeleton'] },
  676: { q: 'What grows on our head and can be cut, dyed or combed?', o: ['Hair','Skin','Eyes','Nose'] },
  677: { q: 'Which part of the leg bends when we sit down or climb stairs?', o: ['Knee','Elbow','Foot','Hand'] },
  678: { q: 'Which part of the arm bends when we bring food up to our mouth?', o: ['Elbow','Knee','Hand','Foot'] },
  679: { q: 'Which part of the body is behind our torso, opposite the belly?', o: ['Back','Belly','Leg','Arm'] },
  680: { q: 'What is that funny little spot right in the middle of our belly?', o: ['Belly button','Eye','Ear','Nose'] },

  // 19c. SCHOOL (new batch 2)
  681: { q: 'Where do students write their lessons, in a bunch of pages bound together?', o: ['Notebook','Book','Backpack','Pencil'] },
  682: { q: 'Where do we keep the pencil, markers and eraser inside the backpack?', o: ['Pencil case','Backpack','Notebook','Lunchbox'] },
  683: { q: 'What do we use to color drawings, made of colored wax?', o: ['Crayon','Scissors','Ruler','Pen'] },
  684: { q: 'What do we use to sharpen the pencil tip again after it breaks?', o: ['Pencil sharpener','Scissors','Eraser','Ruler'] },
  685: { q: 'Who is the person responsible for the whole school, who makes the most important decisions?', o: ['Principal','Teacher','Student','Cook'] },
  686: { q: 'What do students usually wear that matches, with the school\'s color and symbol?', o: ['School uniform','Backpack','Lunchbox','Notebook'] },
  687: { q: 'What do we use to know the day, month and year, with every day marked?', o: ['Calendar','Ruler','Clock','Book'] },
  688: { q: 'Which round object shows the map of the whole world, with all the continents and oceans?', o: ['Globe','Ball','Balloon','Yo-yo'] },
  689: { q: 'What do we call the friend who studies in the same class as you?', o: ['Classmate','Teacher','Principal','Family'] },
  690: { q: 'What do we call the special celebration when we finish a stage of school, like kindergarten?', o: ['Graduation','Birthday','Christmas','Halloween'] },

  // 20c. TRANSPORTATION (new batch 2)
  691: { q: 'Which vehicle with two small wheels do we push along with one foot on the ground?', o: ['Scooter','Skateboard','Bicycle','Tricycle'] },
  692: { q: 'Which vehicle is a board with small wheels, used for doing tricks in the street?', o: ['Skateboard','Scooter','Bicycle','Roller skates'] },
  693: { q: 'Which vehicle climbs mountains hanging from a cable, carrying people inside a cabin?', o: ['Cable car','Helicopter','Airplane','Elevator'] },
  694: { q: 'Which vehicle glides over the snow, sometimes pulled by dogs or reindeer?', o: ['Sled','Skateboard','Bicycle','Sailboat'] },
  695: { q: 'Which vehicle flies very slowly, is huge and colorful, and uses fire to rise into the air?', o: ['Hot air balloon','Airplane','Helicopter','Rocket'] },
  696: { q: 'Which vehicle has a loud siren and quickly takes injured people to the hospital?', o: ['Ambulance','Fire truck','Taxi','Bus'] },
  697: { q: 'Which vehicle do we call and pay for to get a quick ride across the city?', o: ['Taxi','Bus','Ambulance','Car'] },
  698: { q: 'Which vehicle used to be pulled by horses long ago, before cars existed?', o: ['Horse-drawn cart','Car','Truck','Tractor'] },
  699: { q: 'Which vehicle uses the wind blowing into a big sail to move across the water?', o: ['Sailboat','Ship','Canoe','Motorboat'] },
  700: { q: 'Which huge vehicle travels across the ocean for several days, carrying hundreds of vacationing passengers?', o: ['Cruise ship','Sailboat','Canoe','Motorboat'] },

  // 21c. OCCUPATIONS (new batch 2)
  701: { q: 'Who takes care of our teeth and teaches us how to brush them properly?', o: ['Dentist','Doctor','Teacher','Hairdresser'] },
  702: { q: 'Who studies the law and defends people in court?', o: ['Lawyer','Police officer','Teacher','Doctor'] },
  703: { q: 'Who designs and calculates how to build bridges, buildings and machines?', o: ['Engineer','Construction worker','Mechanic','Painter'] },
  704: { q: 'Who does experiments in a laboratory to discover new things about the world?', o: ['Scientist','Doctor','Teacher','Photographer'] },
  705: { q: 'Who performs in movies and plays, portraying characters?', o: ['Atriz/Actor','Singer','Writer','Photographer'] },
  706: { q: 'Who sings at concerts and records songs we hear on the radio?', o: ['Singer','Atriz/Actor','Writer','Cook'] },
  707: { q: 'Who writes the storybooks we love to read?', o: ['Writer','Singer','Atriz/Actor','Photographer'] },
  708: { q: 'Who prepares medicine and works at the pharmacy?', o: ['Pharmacist','Doctor','Veterinarian','Dentist'] },
  709: { q: 'Who safely repairs the wires and electrical system of the house?', o: ['Electrician','Mechanic','Construction worker','Plumber'] },
  710: { q: 'Who keeps an eye on swimmers at the pool or beach, ready to help in emergencies?', o: ['Lifeguard','Police officer','Firefighter','Doctor'] },

  // 22c. FOOD (new batch 2)
  711: { q: 'Which white food is the main side dish for beans on the Brazilian plate?', o: ['Rice','Beans','Pasta','Bread'] },
  712: { q: 'Which food is a mix of raw vegetables, usually seasoned with olive oil and lemon?', o: ['Salad','Pizza','Burger','Soup'] },
  713: { q: 'Which round ground-meat food is served inside a bun with cheese and lettuce?', o: ['Burger','Pizza','Hot dog','Sandwich'] },
  714: { q: 'Which food is made of corn that "pops" when heated and becomes a fluffy snack?', o: ['Popcorn','Chocolate','Cookie','Donut'] },
  715: { q: 'Which sweet, golden food is made by bees inside the hive?', o: ['Honey','Butter','Jam','Milk'] },
  716: { q: 'Which creamy yellow food is made by churning cream, great for spreading on bread?', o: ['Butter','Cheese','Honey','Ice cream'] },
  717: { q: 'Which sweet food made of fruit cooked with sugar do we spread on bread in the morning?', o: ['Jam','Honey','Butter','Guacamole'] },
  718: { q: 'Which Brazilian food is made on the grill, with meats cooked over hot coals?', o: ['Barbecue','Pizza','Pasta','Soup'] },
  719: { q: 'Which round little Brazilian food, made of cassava starch, is common at breakfast?', o: ['Tapioca','Pancake','Bread','Waffle'] },
  720: { q: 'Which Brazilian bread roll is made with cheese and cassava starch, filling the house with a delicious smell?', o: ['Cheese bread','Bread','Croissant','Donut'] },

  // 23c. CLOTHES (new batch 2)
  721: { q: 'Which formal piece of clothing do men wear around the neck, tied in a knot, for special occasions?', o: ['Necktie','Scarf','T-shirt','Cap'] },
  722: { q: 'Which piece of clothing covers only from the waist down, without being pants or a full dress?', o: ['Skirt','Pants','Dress','Shorts'] },
  723: { q: 'Which short piece of clothing covers the legs to the knee, great for hot days?', o: ['Shorts','Pants','Skirt','Swimsuit'] },
  724: { q: 'Which open, strappy footwear do we wear in summer and at the beach?', o: ['Sandal','Sneakers','Boot','Shoe'] },
  725: { q: 'Which tall, closed footwear protects the feet from rain or snow?', o: ['Boot','Sandal','Sneakers','Socks'] },
  726: { q: 'What do cooks and parents wear over their clothes to avoid getting dirty while cooking?', o: ['Apron','Coat','T-shirt','Scarf'] },
  727: { q: 'What do we wear so our clothes don\'t get wet when we go out in heavy rain?', o: ['Raincoat','Gloves','Cap','Sunglasses'] },
  728: { q: 'What do we wear to become another character at parties, like Carnival?', o: ['Costume','Dress','T-shirt','Swimsuit'] },
  729: { q: 'Which comfortable, sporty footwear do we wear to run and play ball?', o: ['Sneakers','Sandal','Boot','Shoe'] },
  730: { q: 'Which round accessory do we wear on our finger, sometimes used at weddings?', o: ['Ring','Necklace','Bracelet','Crown'] },

  // 24c. HOUSEHOLD OBJECTS (new batch 2)
  731: { q: 'What do we use to cut meat on the plate during a meal?', o: ['Knife','Fork','Spoon','Plate'] },
  732: { q: 'What do we use to bring food from the plate to our mouth, by spearing it?', o: ['Fork','Knife','Spoon','Plate'] },
  733: { q: 'Which appliance heats up food quickly, spinning the plate inside?', o: ['Microwave','Fridge','Washing machine','TV'] },
  734: { q: 'Which appliance washes clothes by itself, just add soap and water?', o: ['Washing machine','Fridge','Microwave','Broom'] },
  735: { q: 'What do we put under our head in bed to sleep more comfortably?', o: ['Pillow','Sofa','Mirror','Rug'] },
  736: { q: 'What do we use to cover ourselves and stay warm while we sleep?', o: ['Blanket','Sofa','Mirror','Towel'] },
  737: { q: 'Where do we look at ourselves to comb our hair and check our outfit?', o: ['Mirror','Door','Lightbulb','TV'] },
  738: { q: 'What lies soft on the living room floor so we don\'t feel the cold floor on our feet?', o: ['Rug','Sofa','Bed','Mirror'] },
  739: { q: 'Where do we store folded or hanging clothes inside the bedroom?', o: ['Closet','Door','Bed','Sofa'] },
  740: { q: 'Which appliance blends fruit with water or milk to make smoothies and juices?', o: ['Blender','Fridge','Microwave','Washing machine'] },

  // 25c. TOYS (new batch 2)
  741: { q: 'Which toy goes up and down on a little string as we flick our wrist?', o: ['Yo-yo','Spinning top','Kite','Ball'] },
  742: { q: 'Which toy is a hoop we spin around our waist to keep it from falling?', o: ['Hula hoop','Yo-yo','Kite','Ball'] },
  743: { q: 'Which small, round, colorful glass toy do we use to play by aiming at other little balls?', o: ['Marble','Ball','Yo-yo','Spinning top'] },
  744: { q: 'Which toy is soft and cuddly, and many kids hug it to fall asleep?', o: ['Teddy bear','Doll','Puzzle','Balloon'] },
  745: { q: 'Which toy has tiles with numbered dots that we match together to form sequences?', o: ['Dominoes','Cards','Board game','Puzzle'] },
  746: { q: 'Which toy is played on a board, moving pieces across squares until reaching the end?', o: ['Board game','Cards','Dominoes','Puzzle'] },
  747: { q: 'Which hand puppet comes to life when we put our fingers inside it to make funny voices?', o: ['Puppet','Doll','Teddy bear','Action figure'] },
  748: { q: 'Which toy has little wheels attached to your feet, used for gliding around on skates?', o: ['Roller skates','Scooter','Skateboard','Bicycle'] },
  749: { q: 'Which toy figure looks like a hero or action character, with arms and legs that move?', o: ['Action figure','Doll','Teddy bear','Robot'] },
  750: { q: 'Which beach toy do we use to build sandcastles?', o: ['Bucket and spade','Ball','Kite','Puzzle'] },

  // 26c. SPACE (new batch 2)
  751: { q: 'Which is the second planet from the Sun, considered the hottest of all because of its thick atmosphere?', o: ['Venus','Mars','Saturn','Earth'] },
  752: { q: 'Which planet spins "lying on its side," different from all the other planets?', o: ['Uranus','Saturn','Neptune','Jupiter'] },
  753: { q: 'What do we call the region in space with so much gravity that not even light can escape it?', o: ['Black hole','Comet','Shooting star','Saturn'] },
  754: { q: 'What is the name of the galaxy where our Solar System is located, with Earth and all the planets?', o: ['Milky Way','Universe','Solar System','Constellation'] },
  755: { q: 'What do we call the laboratory that orbits the Earth, where astronauts live and work?', o: ['Space station','Rocket','Telescope','Astronaut'] },
  756: { q: 'Which space object has a core of ice and dust, and forms a bright tail as it nears the Sun?', o: ['Comet','Asteroid','Shooting star','Moon'] },
  757: { q: 'What do we call each different shape the Moon seems to have in the sky, like full, waning or crescent?', o: ['Moon phase','Sun','Star','Comet'] },
  758: { q: 'What do we call a group of stars that together form a picture in the sky, like a bear or a hunter?', o: ['Constellation','Milky Way','Planet','Comet'] },
  759: { q: 'Why do things fall when we drop them on Earth, instead of floating like in space?', o: ['Gravity','Wind','Sunlight','Magnet'] },
  760: { q: 'What do we call the person who studies celestial bodies, stars and planets through science?', o: ['Astronomer','Astronaut','Teacher','Scientist'] },

};
